# Generated by Django 5.2.10 on 2026-02-13 16:55

from django.db import migrations

import core.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0027_action_item_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dswresult",
            name="data",
            field=core.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="triageresult",
            name="cleaned_csv",
            field=core.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="triageresult",
            name="report_markdown",
            field=core.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="triageresult",
            name="summary_json",
            field=core.encryption.EncryptedTextField(),
        ),
    ]
