# Generated by Django 5.2.10 on 2026-02-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0034_remove_valuestreammap_vsm_has_single_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuestreammap",
            name="metric_snapshots",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{timestamp, lead_time, process_time, pce, takt_time, step_count, inventory_count}]",
            ),
        ),
    ]
