# Generated by Django 5.2.12 on 2026-03-03 23:08

from django.db import migrations, models


def migrate_rca_statuses(apps, schema_editor):
    """Migrate old RCA statuses to new state machine values."""
    RCASession = apps.get_model("agents_api", "RCASession")
    mapping = {
        "in_progress": "investigating",
        "review": "root_cause_identified",
        "complete": "closed",
    }
    for old_status, new_status in mapping.items():
        RCASession.objects.filter(status=old_status).update(status=new_status)


def reverse_rca_statuses(apps, schema_editor):
    """Reverse: map new statuses back to old ones."""
    RCASession = apps.get_model("agents_api", "RCASession")
    mapping = {
        "investigating": "in_progress",
        "root_cause_identified": "review",
        "verified": "review",
        "closed": "complete",
    }
    for new_status, old_status in mapping.items():
        RCASession.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0047_add_spc_measurement_to_fmearow"),
    ]

    operations = [
        migrations.AddField(
            model_name="fmea",
            name="scoring_method",
            field=models.CharField(
                choices=[
                    ("rpn", "Risk Priority Number"),
                    ("ap", "Action Priority (AIAG/VDA)"),
                ],
                default="rpn",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fmearow",
            name="control_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prevent", "Prevention"),
                    ("detect", "Detection"),
                    ("both", "Prevention & Detection"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fmearow",
            name="detection_controls",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fmearow",
            name="failure_mode_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("form", "Form"),
                    ("fit", "Fit"),
                    ("function", "Function"),
                    ("safety", "Safety"),
                    ("regulatory", "Regulatory"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fmearow",
            name="prevention_controls",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rcasession",
            name="reopen_reason",
            field=models.TextField(
                blank=True, help_text="Reason for reopening a closed session"
            ),
        ),
        # Widen max_length first so data migration can write new values
        migrations.AlterField(
            model_name="rcasession",
            name="status",
            field=models.CharField(default="draft", max_length=25),
        ),
        # Data migration: convert old statuses to new
        migrations.RunPython(migrate_rca_statuses, reverse_rca_statuses),
        # Now apply the new choices
        migrations.AlterField(
            model_name="rcasession",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("investigating", "Investigating"),
                    ("root_cause_identified", "Root Cause Identified"),
                    ("verified", "Verified"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=25,
            ),
        ),
    ]
