# Generated by Django 5.2.12 on 2026-03-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0058_add_ishikawa_and_ce_matrix"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Problem",
        ),
    ]
