# Generated by Django 5.2.12 on 2026-03-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0073_a3_notebook_link"),
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlleddocument",
            name="linked_process_nodes",
            field=models.ManyToManyField(
                blank=True,
                help_text="ProcessNodes this document's procedures cover — enables PC→graph evidence",
                related_name="controlled_documents",
                to="graph.processnode",
            ),
        ),
        migrations.AddField(
            model_name="measurementequipment",
            name="linked_process_node",
            field=models.ForeignKey(
                blank=True,
                help_text="ProcessNode of type 'measurement' or 'equipment' this record represents",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measurement_equipment",
                to="graph.processnode",
            ),
        ),
    ]
