# Generated by Django 5.2.12 on 2026-03-29 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0075_qms_graph_node_links"),
        ("graph", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("prototype", "Prototype"),
                            ("pre_launch", "Pre-Launch"),
                            ("production", "Production"),
                        ],
                        default="production",
                        max_length=20,
                    ),
                ),
                (
                    "process_name",
                    models.CharField(
                        blank=True,
                        help_text="Process or operation this plan covers",
                        max_length=300,
                    ),
                ),
                ("part_number", models.CharField(blank=True, max_length=100)),
                ("revision", models.CharField(default="1.0", max_length=20)),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "iso_clause",
                    models.CharField(blank=True, default="8.5.1", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_graph",
                    models.ForeignKey(
                        blank=True,
                        help_text="ProcessGraph this control plan monitors",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_plans",
                        to="graph.processgraph",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_plans",
                        to="agents_api.site",
                    ),
                ),
            ],
            options={
                "db_table": "iso_control_plans",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlPlanItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "process_step",
                    models.CharField(
                        help_text="Operation or process step name", max_length=300
                    ),
                ),
                (
                    "characteristic",
                    models.CharField(
                        help_text="What is being measured (dimension, property, attribute)",
                        max_length=300,
                    ),
                ),
                (
                    "characteristic_type",
                    models.CharField(
                        choices=[("product", "Product"), ("process", "Process")],
                        default="product",
                        max_length=20,
                    ),
                ),
                (
                    "is_special",
                    models.BooleanField(
                        default=False,
                        help_text="Special characteristic (safety, regulatory, fit/function)",
                    ),
                ),
                (
                    "control_method",
                    models.CharField(
                        choices=[
                            ("spc", "SPC Control Chart"),
                            ("inspection", "Inspection"),
                            ("gage", "Gage/Measurement"),
                            ("visual", "Visual Check"),
                            ("functional", "Functional Test"),
                            ("automated", "Automated Monitoring"),
                            ("other", "Other"),
                        ],
                        default="inspection",
                        max_length=20,
                    ),
                ),
                (
                    "measurement_technique",
                    models.CharField(
                        blank=True,
                        help_text="Specific instrument or technique",
                        max_length=300,
                    ),
                ),
                (
                    "sample_size",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '5 pieces', '100%', 'n=30'",
                        max_length=100,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'every hour', 'per lot', 'per shift'",
                        max_length=100,
                    ),
                ),
                (
                    "spec_usl",
                    models.FloatField(
                        blank=True, help_text="Upper spec limit", null=True
                    ),
                ),
                (
                    "spec_lsl",
                    models.FloatField(
                        blank=True, help_text="Lower spec limit", null=True
                    ),
                ),
                (
                    "spec_target",
                    models.FloatField(blank=True, help_text="Target value", null=True),
                ),
                ("spec_unit", models.CharField(blank=True, max_length=50)),
                (
                    "reaction_plan",
                    models.TextField(
                        blank=True,
                        help_text="What to do when out of spec: contain, sort, notify, adjust",
                    ),
                ),
                ("sequence", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="agents_api.controlplan",
                    ),
                ),
                (
                    "linked_equipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Measurement equipment used for this characteristic",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_plan_items",
                        to="agents_api.measurementequipment",
                    ),
                ),
                (
                    "linked_process_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="ProcessNode this item monitors — enables graph-level control coverage tracking",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_plan_items",
                        to="graph.processnode",
                    ),
                ),
            ],
            options={
                "db_table": "iso_control_plan_items",
                "ordering": ["control_plan", "sequence"],
            },
        ),
    ]
