# Generated by Django 5.2.12 on 2026-03-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0077_tenant_isolation_fks"),
        ("graph", "0003_olr001_node_fields"),
        ("loop", "0013_olr001_signal_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlplanitem",
            name="competency_stage_required",
            field=models.IntegerField(
                default=1,
                help_text="1=See, 2=Do, 3=Teach — minimum stage to execute this control item",
            ),
        ),
        migrations.AddField(
            model_name="controlplanitem",
            name="detection_mechanism_level",
            field=models.IntegerField(
                blank=True,
                help_text="1-8 per OLR-001 §9 detection hierarchy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="controlplanitem",
            name="fmis_row",
            field=models.ForeignKey(
                blank=True,
                help_text="FMIS row this control item monitors — links control plan to knowledge structure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_plan_items",
                to="loop.fmisrow",
            ),
        ),
        migrations.AddField(
            model_name="measurementequipment",
            name="failure_count",
            field=models.IntegerField(default=0, help_text="Historical failure count"),
        ),
        migrations.AddField(
            model_name="measurementequipment",
            name="failure_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{date, hours_at_failure, description}]",
            ),
        ),
        migrations.AddField(
            model_name="measurementequipment",
            name="measurement_uncertainty_percent",
            field=models.FloatField(
                blank=True,
                help_text="% contribution to total variation from Gage R&R",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="measurementequipment",
            name="mtbf_hours",
            field=models.FloatField(
                blank=True, help_text="Mean time between failures (hours)", null=True
            ),
        ),
        migrations.AddField(
            model_name="measurementequipment",
            name="weibull_scale",
            field=models.FloatField(
                blank=True, help_text="Weibull scale parameter (eta)", null=True
            ),
        ),
        migrations.AddField(
            model_name="measurementequipment",
            name="weibull_shape",
            field=models.FloatField(
                blank=True, help_text="Weibull shape parameter (beta)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="controlplanitem",
            name="linked_process_node",
            field=models.ForeignKey(
                blank=True,
                help_text="ProcessNode this item monitors",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="control_plan_items",
                to="graph.processnode",
            ),
        ),
    ]
