# Generated by Django 5.2.12 on 2026-05-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0082_transfer_llm_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customercomplaint",
            name="capa",
        ),
        migrations.RemoveField(
            model_name="capastatuschange",
            name="capa",
        ),
        migrations.RemoveField(
            model_name="capastatuschange",
            name="changed_by",
        ),
        migrations.DeleteModel(
            name="CAPAReport",
        ),
        migrations.DeleteModel(
            name="CAPAStatusChange",
        ),
    ]
