# Generated by Django 5.2.12 on 2026-03-27 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents_api", "0073_a3_notebook_link"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0023_qms_phase_c_registers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Specific deliverable — not a vague task",
                        max_length=300,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "due_date",
                    models.DateField(
                        help_text="When the deliverable is due. Required — a commitment without a date is a wish."
                    ),
                ),
                (
                    "preconditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='What the org must provide: [{"description": "...", "status": "pending|met|unmet", "blocked_by_commitment_id": "uuid|null"}]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("fulfilled", "Fulfilled"),
                            ("broken", "Broken"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "transition_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("revise_document", "Revise Document"),
                            ("create_document", "Create Document"),
                            ("add_control", "Add Control (FMIS)"),
                            ("train", "Training"),
                            ("process_confirmation", "Schedule PC"),
                            ("forced_failure", "Schedule Forced Failure"),
                            ("monitor", "Set Up Monitoring"),
                            ("audit_zone", "Schedule Zone Audit"),
                            ("first_article", "First Article Inspection"),
                        ],
                        default="",
                        help_text="If set, fulfilling this commitment triggers a mode transition (LOOP-001 §3.2)",
                        max_length=30,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("investigation", "Investigation"),
                            ("management_review", "Management Review"),
                            ("kaizen_charter", "Kaizen Charter"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("target_object_id", models.UUIDField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_commitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Person who commits to the deliverable",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_investigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commitments",
                        to="core.investigation",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "loop_commitment",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModeTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transition_type",
                    models.CharField(
                        choices=[
                            ("revise_document", "Investigate → Standardize (revise)"),
                            ("create_document", "Investigate → Standardize (create)"),
                            ("add_control", "Investigate → Standardize (FMIS)"),
                            ("train", "Standardize → Verify (training)"),
                            ("process_confirmation", "Standardize → Verify (PC)"),
                            ("forced_failure", "Standardize → Verify (FFT)"),
                            ("monitor", "Standardize → Verify (SPC)"),
                            ("audit_zone", "Standardize → Verify (frontier)"),
                            ("first_article", "Standardize → Verify (FAI)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "from_mode",
                    models.CharField(
                        choices=[
                            ("investigate", "Investigate"),
                            ("standardize", "Standardize"),
                            ("verify", "Verify"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_mode",
                    models.CharField(
                        choices=[
                            ("investigate", "Investigate"),
                            ("standardize", "Standardize"),
                            ("verify", "Verify"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_object_id", models.UUIDField()),
                ("target_object_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions",
                        to="loop.commitment",
                    ),
                ),
            ],
            options={
                "db_table": "loop_mode_transition",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QMSPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("process_confirmation", "Process Confirmation"),
                            ("spc_monitoring", "SPC Monitoring"),
                            ("forced_failure", "Forced Failure"),
                            ("complaint", "Customer Complaint"),
                            ("training", "Training"),
                            ("review_frequency", "Review Frequency"),
                            ("training_coverage", "Training Coverage"),
                            ("recurrence", "Recurrence Detection"),
                            ("commitment_fulfillment", "Commitment Fulfillment"),
                            ("calibration", "Calibration"),
                            ("verification_schedule", "Verification Schedule"),
                            ("fmis", "FMIS Methodology"),
                            ("investigation", "Investigation"),
                            ("capa_report", "CAPA Report"),
                            ("severity_display", "Severity Display"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "rule_key",
                    models.CharField(
                        help_text="Machine-readable key: e.g., pc.retraining_threshold",
                        max_length=100,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Structured rule configuration — typed parameters",
                    ),
                ),
                (
                    "linked_standard",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which ISO/IATF/AS clause this policy satisfies",
                        max_length=100,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "controlled_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qms_policies",
                        to="agents_api.controlleddocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qms_policies",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "loop_qms_policy",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("spc_violation", "SPC Out-of-Control"),
                            ("pc_threshold", "PC Threshold Breach"),
                            ("customer_complaint", "Customer Complaint"),
                            ("audit_finding", "Audit Finding"),
                            ("forced_failure_miss", "Forced Failure Detection Miss"),
                            ("frontier_card", "Frontier Card Finding"),
                            ("operator_report", "Operator Report"),
                            ("management_review", "Management Review Action"),
                            ("training_reflection", "Training Reflection Pattern"),
                            ("supplier_issue", "Supplier Quality Issue"),
                            ("field_return", "Field Return / Warranty"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                (
                    "triage_state",
                    models.CharField(
                        choices=[
                            ("untriaged", "Untriaged"),
                            ("acknowledged", "Acknowledged"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="untriaged",
                        max_length=20,
                    ),
                ),
                ("source_object_id", models.UUIDField(blank=True, null=True)),
                ("dismissed_reason", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by_investigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_signals",
                        to="core.investigation",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "loop_signal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("retraining_needed", "Retraining Needed"),
                            ("standard_revision_needed", "Standard Revision Needed"),
                            ("review_overdue", "Review Overdue"),
                            ("recurrence_detected", "Recurrence Detected"),
                            ("detection_gap", "Detection Gap"),
                            ("threshold_breach", "Threshold Breach"),
                            ("schedule_miss", "Schedule Miss"),
                            ("calibration_overdue", "Calibration Overdue"),
                            ("commitment_overdue", "Commitment Overdue"),
                            ("qualification_gap", "Investigator Qualification Gap"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Structured data: affected entities, measurements, thresholds, evidence",
                    ),
                ),
                (
                    "source_event",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ToolEventBus event name, or empty for PolicySweepEvaluator",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("dismissed_reason", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_conditions",
                        to="core.tenant",
                    ),
                ),
                (
                    "policy_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="loop.qmspolicy",
                    ),
                ),
                (
                    "resolved_by_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_conditions",
                        to="loop.signal",
                    ),
                ),
            ],
            options={
                "db_table": "loop_policy_condition",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["status", "due_date"], name="loop_commit_status_39eae1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["owner", "status"], name="loop_commit_owner_i_cc9cb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=models.Index(
                fields=["tenant", "status"], name="loop_commit_tenant__ae7a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qmspolicy",
            index=models.Index(
                fields=["tenant", "scope", "is_active"],
                name="loop_qms_po_tenant__8ca6f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qmspolicy",
            index=models.Index(
                fields=["rule_key", "is_active"], name="loop_qms_po_rule_ke_5ea2fa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="qmspolicy",
            constraint=models.UniqueConstraint(
                fields=("tenant", "rule_key", "version"), name="unique_policy_version"
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["triage_state", "-created_at"],
                name="loop_signal_triage__51eb24_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["tenant", "triage_state"], name="loop_signal_tenant__4271df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policycondition",
            index=models.Index(
                fields=["status", "-created_at"], name="loop_policy_status_a74df3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policycondition",
            index=models.Index(
                fields=["tenant", "status"], name="loop_policy_tenant__1b36c5_idx"
            ),
        ),
    ]
