# Generated by Django 5.2.12 on 2026-03-27 19:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0073_a3_notebook_link"),
        ("core", "0023_qms_phase_c_registers"),
        ("files", "0002_alter_userfile_file"),
        ("loop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                ("document_version", models.CharField(max_length=20)),
                (
                    "process_area",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("shift", models.CharField(blank=True, default="", max_length=20)),
                (
                    "diagnosis",
                    models.CharField(
                        choices=[
                            ("system_works", "System Works"),
                            ("standard_unclear", "Standard Unclear / Training Gap"),
                            ("process_gap", "Process Design Broken"),
                            ("incomplete", "Observation Incomplete"),
                        ],
                        default="incomplete",
                        max_length=30,
                    ),
                ),
                ("observer_notes", models.TextField(blank=True, default="")),
                (
                    "improvements_observed",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What's going RIGHT — acknowledge good practice first",
                    ),
                ),
                (
                    "operator_interaction",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"what_going_well": "...", "challenges": "...", "what_would_change": "..."}',
                    ),
                ),
                (
                    "comfort_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("comfortable", "Comfortable"),
                            ("neutral", "Neutral"),
                            ("uncomfortable", "Uncomfortable"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "close_loop_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immediate", "Immediate (on the spot)"),
                            ("within_24h", "Within 24 Hours"),
                            ("pending", "Pending"),
                            ("not_done", "Not Done"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("close_loop_notes", models.TextField(blank=True, default="")),
                (
                    "controlled_document",
                    models.ForeignKey(
                        help_text="The standard being confirmed — REQUIRED",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_confirmations",
                        to="agents_api.controlleddocument",
                    ),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        help_text="The person conducting the PC",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_confirmations_as_observer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="The operator being observed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_confirmations_as_operator",
                        to="agents_api.employee",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_confirmations",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "loop_process_confirmation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PCObservationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "step_text",
                    models.CharField(
                        help_text="The step being observed", max_length=500
                    ),
                ),
                ("key_point", models.CharField(blank=True, default="", max_length=500)),
                (
                    "reason_why",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "followed",
                    models.BooleanField(
                        default=True, help_text="Was the standard followed?"
                    ),
                ),
                (
                    "followed_na",
                    models.BooleanField(default=False, help_text="Not applicable"),
                ),
                (
                    "outcome_pass",
                    models.BooleanField(
                        default=True, help_text="Was the outcome correct?"
                    ),
                ),
                (
                    "outcome_na",
                    models.BooleanField(default=False, help_text="Not applicable"),
                ),
                (
                    "deviation_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "linked_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agents_api.isosection",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Photo evidence linked to this step",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.userfile",
                    ),
                ),
                (
                    "process_confirmation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation_items",
                        to="loop.processconfirmation",
                    ),
                ),
            ],
            options={
                "db_table": "loop_pc_observation_item",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingReflection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "document_version",
                    models.CharField(
                        help_text="Snapshot of document version at training time",
                        max_length=20,
                    ),
                ),
                (
                    "reflection_text",
                    models.TextField(
                        help_text="Free-text reflection prompted by: What was clear? What was confusing? What would you change? What's different from how you actually do it?"
                    ),
                ),
                (
                    "self_assessed_level",
                    models.IntegerField(
                        default=0,
                        help_text="Operator's self-assessed TWI competency level (0-4) post-training",
                    ),
                ),
                (
                    "controlled_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_reflections",
                        to="agents_api.controlleddocument",
                    ),
                ),
                (
                    "flagged_sections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sections the operator found unclear",
                        related_name="flagged_in_reflections",
                        to="agents_api.isosection",
                    ),
                ),
                (
                    "training_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection",
                        to="agents_api.trainingrecord",
                    ),
                ),
            ],
            options={
                "db_table": "loop_training_reflection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForcedFailureTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "test_mode",
                    models.CharField(
                        choices=[
                            (
                                "hypothesis_driven",
                                "Hypothesis-Driven (linked to FMIS row)",
                            ),
                            ("exploratory", "Exploratory (boundary probing)"),
                        ],
                        default="hypothesis_driven",
                        max_length=20,
                    ),
                ),
                (
                    "test_plan",
                    models.TextField(
                        help_text="What conditions will be created, what's the expected detection response"
                    ),
                ),
                (
                    "control_being_tested",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the detection control under test",
                    ),
                ),
                (
                    "safety_reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="Confirmation that test can be conducted safely — REQUIRED before execution",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("detected", "Detected"),
                            ("not_detected", "Not Detected"),
                            ("partially_detected", "Partially Detected"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "detection_count",
                    models.IntegerField(
                        default=0, help_text="How many injected failures were detected"
                    ),
                ),
                (
                    "injection_count",
                    models.IntegerField(
                        default=0, help_text="How many failures were injected"
                    ),
                ),
                ("evidence_notes", models.TextField(blank=True, default="")),
                ("conducted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_forced_failure_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_photos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="forced_failure_evidence",
                        to="files.userfile",
                    ),
                ),
                (
                    "fmea_row",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked FMEA row for hypothesis-driven tests (nullable for exploratory)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forced_failure_tests",
                        to="agents_api.fmearow",
                    ),
                ),
                (
                    "safety_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_reviewed_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forced_failure_tests",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "loop_forced_failure_test",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["fmea_row", "-created_at"],
                        name="loop_forced_fmea_ro_132353_idx",
                    ),
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="loop_forced_tenant__098474_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="processconfirmation",
            index=models.Index(
                fields=["operator", "controlled_document"],
                name="loop_proces_operato_fe1577_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processconfirmation",
            index=models.Index(
                fields=["tenant", "-created_at"], name="loop_proces_tenant__9fe5e9_idx"
            ),
        ),
    ]
