# Generated by Django 5.2.12 on 2026-03-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0073_a3_notebook_link"),
        ("loop", "0002_processconfirmation_pcobservationitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processconfirmation",
            name="controlled_document",
            field=models.ForeignKey(
                blank=True,
                help_text="The standard being confirmed — required before observation can begin",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_confirmations",
                to="agents_api.controlleddocument",
            ),
        ),
        migrations.AlterField(
            model_name="processconfirmation",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                help_text="The operator being observed — assigned at gemba, not at scheduling time",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_confirmations_as_operator",
                to="agents_api.employee",
            ),
        ),
    ]
