# Generated by Django 5.2.12 on 2026-03-28 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_qms_phase_c_registers"),
        ("loop", "0004_fmis_fmisrow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigationEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("narrative", "Narrative"),
                            ("tool_output", "Tool Output"),
                            ("evidence", "Evidence"),
                            ("photo", "Photo"),
                            ("data", "Data"),
                        ],
                        default="narrative",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown content for narrative entries. JSON for tool/evidence/data.",
                    ),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Plotly chart JSON, table data, analysis parameters/results",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigation_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.investigation",
                    ),
                ),
                (
                    "tool_link",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to InvestigationToolLink for tool output entries",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entry",
                        to="core.investigationtoollink",
                    ),
                ),
            ],
            options={
                "db_table": "loop_investigation_entry",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
