# Generated by Django 5.2.12 on 2026-03-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loop", "0006_auditor_portal_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fmisrow",
            name="cause_entity",
        ),
        migrations.RemoveField(
            model_name="fmisrow",
            name="effect_entity",
        ),
        migrations.RemoveField(
            model_name="fmisrow",
            name="failure_mode_entity",
        ),
    ]
