# Generated by Django 5.2.12 on 2026-03-29 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0076_control_plan"),
        ("core", "0023_qms_phase_c_registers"),
        ("loop", "0009_commitment_resource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("quality_defect", "Quality Defect"),
                            ("delivery", "Delivery Issue"),
                            ("documentation", "Documentation"),
                            ("specification", "Specification Deviation"),
                            ("packaging", "Packaging / Handling"),
                            ("contamination", "Contamination"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "part_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "lot_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("quantity_affected", models.IntegerField(default=0)),
                ("quantity_rejected", models.IntegerField(default=0)),
                ("defect_description", models.TextField(blank=True, default="")),
                ("inspection_method", models.TextField(blank=True, default="")),
                ("evidence_photos", models.JSONField(blank=True, default=list)),
                (
                    "cost_of_quality",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Internal cost: scrap, rework, sort, downtime",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "credit_requested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "credit_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("returned", "Return to Supplier"),
                            ("scrapped", "Scrapped"),
                            ("reworked", "Reworked"),
                            ("use_as_is", "Use As-Is (concession)"),
                            ("sorted", "100% Sorted"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("filed", "Filed"),
                            ("acknowledged", "Acknowledged"),
                            ("responded", "Responded"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                ("response_due_date", models.DateField(blank=True, null=True)),
                (
                    "portal_token",
                    models.CharField(
                        blank=True, default="", max_length=64, unique=True
                    ),
                ),
                ("portal_expires_at", models.DateTimeField(blank=True, null=True)),
                ("linked_process_node_ids", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_supplier_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ncr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_claims",
                        to="agents_api.nonconformancerecord",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="agents_api.supplierrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_claims",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "loop_supplier_claim",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("next_shipment", "Next Shipment Inspection"),
                            ("audit", "Supplier Audit"),
                            ("test", "Test / Re-Qualification"),
                            ("document_review", "Document Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("conforming", "Conforming"),
                            ("nonconforming", "Nonconforming"),
                            ("partial", "Partially Conforming"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evidence_notes", models.TextField(blank=True, default="")),
                ("evidence_files", models.JSONField(blank=True, default=list)),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claim_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="loop.supplierclaim",
                    ),
                ),
            ],
            options={
                "db_table": "loop_claim_verification",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "root_cause_category",
                    models.CharField(
                        choices=[
                            ("method", "Method / Process"),
                            ("material", "Material"),
                            ("machine", "Machine / Equipment"),
                            ("man", "Personnel / Training"),
                            ("measurement", "Measurement System"),
                            ("environment", "Environment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("root_cause_description", models.TextField()),
                ("corrective_action", models.TextField()),
                ("preventive_action", models.TextField()),
                ("implementation_date", models.DateField()),
                (
                    "evidence_files",
                    models.JSONField(
                        blank=True, default=list, help_text="UserFile UUIDs"
                    ),
                ),
                ("is_repeat_root_cause", models.BooleanField(default=False)),
                (
                    "response_quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="0-1 score computed by response quality rules",
                        null=True,
                    ),
                ),
                (
                    "quality_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of string flags from quality analysis",
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        blank=True,
                        help_text="null=pending, true=accepted, false=rejected",
                        null=True,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="loop.supplierclaim",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_supplier_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "loop_supplier_response",
                "ordering": ["revision"],
            },
        ),
        migrations.AddIndex(
            model_name="supplierclaim",
            index=models.Index(
                fields=["supplier", "status"], name="loop_suppli_supplie_a3d3c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierclaim",
            index=models.Index(
                fields=["tenant", "status"], name="loop_suppli_tenant__b019ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierclaim",
            index=models.Index(
                fields=["portal_token"], name="loop_suppli_portal__953fce_idx"
            ),
        ),
    ]
