# Generated by Django 5.2.12 on 2026-03-29 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0076_control_plan"),
        ("core", "0023_qms_phase_c_registers"),
        ("files", "0002_alter_userfile_file"),
        ("loop", "0010_supplier_claims"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierCoA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "coa_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "lot_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "part_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("date_issued", models.DateField(blank=True, null=True)),
                (
                    "measurements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{parameter, value, unit, spec_min, spec_max, method, conforming}]",
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[("manual", "Manual Entry"), ("csv", "CSV Upload")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("all_conforming", models.BooleanField(default=True)),
                (
                    "nonconforming_parameters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Parameter names that failed spec check",
                    ),
                ),
                ("spc_data_ingested", models.BooleanField(default=False)),
                ("spc_ingestion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_process_node_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ProcessNode UUIDs for material property nodes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("reviewed", "Reviewed"),
                            ("accepted", "Accepted"),
                            ("ingested", "Ingested into SPC"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_coas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Uploaded PDF/file if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coas",
                        to="files.userfile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_coas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coas",
                        to="agents_api.supplierrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_coas",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "loop_supplier_coa",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "status"],
                        name="loop_suppli_supplie_e3acc0_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"],
                        name="loop_suppli_tenant__36d184_idx",
                    ),
                    models.Index(
                        fields=["part_number", "lot_number"],
                        name="loop_suppli_part_nu_0a74bc_idx",
                    ),
                ],
            },
        ),
    ]
