# Generated by Django 5.2.12 on 2026-03-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0077_tenant_isolation_fks"),
        ("core", "0024_tenant_isolation_fk"),
        ("loop", "0011_supplier_coa"),
    ]

    operations = [
        migrations.AddField(
            model_name="forcedfailuretest",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forced_failure_tests",
                to="agents_api.site",
            ),
        ),
        migrations.AddField(
            model_name="modetransition",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mode_transitions",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="processconfirmation",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_confirmations",
                to="agents_api.site",
            ),
        ),
    ]
