# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0024_tenant_isolation_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="CEMatrix",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("title", models.CharField(blank=True, max_length=255)),
                        (
                            "outputs",
                            models.JSONField(
                                default=list,
                                help_text='Process outputs (Y\'s): [{"name": "...", "weight": 1-10}]',
                            ),
                        ),
                        (
                            "inputs",
                            models.JSONField(
                                default=list,
                                help_text='Process inputs (X\'s): [{"name": "..."}]',
                            ),
                        ),
                        (
                            "scores",
                            models.JSONField(
                                default=dict,
                                help_text="Scoring grid: str(input_idx) → str(output_idx) → 0|1|3|9",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("draft", "Draft"),
                                    ("scoring", "Scoring"),
                                    ("complete", "Complete"),
                                ],
                                default="draft",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "owner",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="ce_mat_matrices",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="ce_mat_matrices",
                                to="core.project",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="ce_matrices",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "C&E Matrix",
                        "verbose_name_plural": "C&E Matrices",
                        "db_table": "ce_matrices",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
