# Generated by Django 5.2.12 on 2026-03-29 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0078_olr001_controlplan_equipment"),
        ("core", "0024_tenant_isolation_fk"),
        ("graph", "0003_olr001_node_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeHealthSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "calibration_rate",
                    models.FloatField(help_text="edges with evidence / total edges"),
                ),
                (
                    "staleness_rate",
                    models.FloatField(help_text="past threshold / calibrated"),
                ),
                (
                    "contradiction_rate",
                    models.FloatField(help_text="conflicting evidence / total"),
                ),
                (
                    "knowledge_gap_ratio",
                    models.FloatField(help_text="assertion-only / total"),
                ),
                (
                    "signal_resolution_velocity_days",
                    models.FloatField(
                        blank=True,
                        help_text="avg days signal → knowledge update",
                        null=True,
                    ),
                ),
                (
                    "proactive_reactive_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="internal detection / total customer-facing",
                        null=True,
                    ),
                ),
                (
                    "detection_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="critical nodes by detection level",
                    ),
                ),
                (
                    "maturity_level",
                    models.IntegerField(
                        default=1,
                        help_text="1=Structured, 2=Learning, 3=Sustaining, 4=Predictive",
                    ),
                ),
                ("total_nodes", models.IntegerField(default=0)),
                ("total_edges", models.IntegerField(default=0)),
                ("calibrated_edges", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="graph.processgraph",
                    ),
                ),
            ],
            options={
                "db_table": "graph_knowledge_health",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["graph", "-snapshot_date"],
                        name="graph_knowl_graph_i_cce1e3_idx",
                    )
                ],
                "unique_together": {("graph", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="TenantConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=30)),
                ("key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_overrides",
                        to="agents_api.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_entries",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "graph_tenant_config",
                "indexes": [
                    models.Index(
                        fields=["tenant", "domain"],
                        name="graph_tenan_tenant__598430_idx",
                    )
                ],
                "unique_together": {("tenant", "domain", "key", "site")},
            },
        ),
    ]
