# Generated by Django 5.2.12 on 2026-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_archetype_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="window64",
            name="goal_number",
            field=models.PositiveSmallIntegerField(
                help_text="0 = mandala center (purpose), 1-8 = the 8 goals"
            ),
        ),
    ]
