# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_tenant_isolation_fk"),
        ("dsw", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="notebook",
                    name="baseline_analysis",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dsw.dswresult",
                    ),
                ),
                migrations.AlterField(
                    model_name="notebook",
                    name="current_analysis",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dsw.dswresult",
                    ),
                ),
                migrations.AlterField(
                    model_name="trial",
                    name="after_analysis",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dsw.dswresult",
                    ),
                ),
                migrations.AlterField(
                    model_name="trial",
                    name="before_analysis",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dsw.dswresult",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
