# Generated by Django 5.2.12 on 2026-04-22 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "agents_api",
            "0081_alter_afe_fmea_remove_fmearow_fmea_alter_risk_fmea_and_more",
        ),
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_system", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                (
                    "schema",
                    models.JSONField(
                        help_text="Section definitions: [{key, type, label, required, config}, ...]"
                    ),
                ),
                (
                    "status_flow",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ordered status list, e.g. ["draft", "active", "review", "complete"]',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = system template",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_templates",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "qms_tool_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("status", models.CharField(default="draft", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qms_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qms_artifacts",
                        to="core.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qms_artifacts",
                        to="agents_api.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qms_artifacts",
                        to="core.tenant",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="qms.tooltemplate",
                    ),
                ),
            ],
            options={
                "db_table": "qms_artifacts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowPhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                ("sort_order", models.IntegerField()),
                ("color", models.CharField(blank=True, max_length=20)),
                (
                    "available_templates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="workflow_phases",
                        to="qms.tooltemplate",
                    ),
                ),
            ],
            options={
                "db_table": "qms_workflow_phases",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SignalTypeRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=200)),
                (
                    "default_severity",
                    models.CharField(default="warning", max_length=20),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = system type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_types",
                        to="core.tenant",
                    ),
                ),
                (
                    "auto_phase",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: auto-enter this phase on signal creation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_signal_types",
                        to="qms.workflowphase",
                    ),
                ),
            ],
            options={
                "db_table": "qms_signal_type_registry",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = system workflow",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_templates",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "qms_workflow_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="workflowphase",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="qms.workflowtemplate",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "gate_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Optional: {"requires_sections": ["root_cause"]}',
                    ),
                ),
                (
                    "from_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="qms.workflowphase",
                    ),
                ),
                (
                    "to_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="qms.workflowphase",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="qms.workflowtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "qms_workflow_transitions",
            },
        ),
        migrations.CreateModel(
            name="ArtifactSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_key", models.CharField(max_length=100)),
                (
                    "primitive_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("grid", "Grid"),
                            ("tree", "Tree"),
                            ("checklist", "Checklist"),
                            ("action_list", "Action List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="qms.artifact",
                    ),
                ),
            ],
            options={
                "db_table": "qms_artifact_sections",
                "ordering": ["sort_order"],
                "unique_together": {("artifact", "section_key")},
            },
        ),
        migrations.AddConstraint(
            model_name="tooltemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug", "version"),
                name="unique_tool_template_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="signaltyperegistry",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="unique_signal_type_per_tenant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowphase",
            unique_together={("workflow", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="workflowtransition",
            unique_together={("workflow", "from_phase", "to_phase")},
        ),
    ]
