# Generated by Django 5.2.12 on 2026-04-15 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        ("workbench", "0007_tenant_isolation_fks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epistemiclog",
            name="knowledge_graph",
        ),
        migrations.RemoveField(
            model_name="epistemiclog",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="epistemiclog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="epistemiclog",
            name="workbench",
        ),
        migrations.RemoveField(
            model_name="knowledgegraph",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="knowledgegraph",
            name="user",
        ),
        migrations.RemoveField(
            model_name="knowledgegraph",
            name="workbench",
        ),
        migrations.RemoveField(
            model_name="workbench",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="workbench",
            name="user",
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analysis_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("triage", "Triage (cleaned)"),
                            ("transform", "Transform"),
                            ("merge", "Merge"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("columns_meta", models.JSONField(default=list)),
                ("row_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_datasets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Datasets that were merged/transformed to create this one",
                        to="workbench.sessiondataset",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="workbench.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "session_datasets",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("analysis_type", models.CharField(max_length=50)),
                ("analysis_id", models.CharField(max_length=100)),
                ("columns_used", models.JSONField(default=list)),
                ("config", models.JSONField(default=dict)),
                ("statistics", models.JSONField(default=dict)),
                ("narrative", models.JSONField(default=dict)),
                ("summary", models.TextField(blank=True, default="")),
                ("charts", models.JSONField(default=list)),
                ("diagnostics", models.JSONField(default=list)),
                ("assumptions", models.JSONField(default=dict)),
                ("education", models.JSONField(blank=True, null=True)),
                ("bayesian_shadow", models.JSONField(blank=True, null=True)),
                (
                    "evidence_grade",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("guide_observation", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="workbench.analysissession",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="workbench.sessiondataset",
                    ),
                ),
            ],
            options={
                "db_table": "session_analyses",
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Artifact",
        ),
        migrations.DeleteModel(
            name="EpistemicLog",
        ),
        migrations.DeleteModel(
            name="KnowledgeGraph",
        ),
        migrations.DeleteModel(
            name="Workbench",
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(
                fields=["user", "-updated_at"], name="analysis_se_user_id_e4c6e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionanalysis",
            index=models.Index(
                fields=["session", "created_at"], name="session_ana_session_ba4db3_idx"
            ),
        ),
    ]
