# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="IshikawaDiagram",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("title", models.CharField(blank=True, max_length=255)),
                        (
                            "effect",
                            models.TextField(
                                blank=True,
                                help_text="The process-level effect being analyzed (the fish head)",
                            ),
                        ),
                        (
                            "branches",
                            models.JSONField(
                                default=list,
                                help_text="6M category branches with recursive causes",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("draft", "Draft"),
                                    ("analyzing", "Analyzing"),
                                    ("complete", "Complete"),
                                ],
                                default="draft",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "owner",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="ik_diagrams",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="ik_diagrams",
                                to="core.project",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="ishikawa_diagrams",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Ishikawa Diagram",
                        "verbose_name_plural": "Ishikawa Diagrams",
                        "db_table": "ishikawa_diagrams",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
