# Generated by Django 5.2.10 on 2026-02-12 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_scheduled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('industry', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('experience_level', models.CharField(blank=True, max_length=20)),
                ('organization_size', models.CharField(blank=True, max_length=20)),
                ('primary_goal', models.CharField(blank=True, max_length=40)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('confidence_stats', models.IntegerField(default=3)),
                ('urgency', models.IntegerField(default=3)),
                ('biggest_challenge', models.TextField(blank=True)),
                ('learning_path', models.CharField(blank=True, max_length=40)),
                ('helpful_emails', models.JSONField(blank=True, default=list)),
                ('skipped_emails', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_surveys',
            },
        ),
        migrations.CreateModel(
            name='OnboardingEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_key', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_emails',
                'ordering': ['scheduled_for'],
                'unique_together': {('user', 'email_key')},
            },
        ),
    ]
