# Generated by Django 5.2.10 on 2026-02-12 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_onboarding_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('referrer_domain', models.CharField(blank=True, db_index=True, max_length=200)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('is_bot', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='api.blogpost')),
            ],
            options={
                'db_table': 'blog_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', 'viewed_at'], name='blog_views_post_id_94cef1_idx'), models.Index(fields=['referrer_domain', 'viewed_at'], name='blog_views_referre_5efaba_idx')],
            },
        ),
    ]
