# Generated by Django 5.2.10 on 2026-02-12 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_email_campaign_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('query_limit_near', 'Query limit near'), ('inactive_days', 'Inactive for N days'), ('signup_no_query', 'Signup with no queries'), ('churn_signal', 'Churn signal'), ('milestone', 'Query milestone'), ('feature_unused', 'Feature unused')], max_length=20)),
                ('trigger_config', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('send_email', 'Send email'), ('internal_alert', 'Internal alert')], max_length=20)),
                ('action_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_hours', models.IntegerField(default=72)),
                ('times_fired', models.IntegerField(default=0)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'automation_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutopilotReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('alerts', models.JSONField(default=list)),
                ('status', models.CharField(default='pending_review', max_length=20)),
            ],
            options={
                'db_table': 'autopilot_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hypothesis', models.TextField(blank=True)),
                ('experiment_type', models.CharField(choices=[('email_subject', 'Email Subject'), ('email_body', 'Email Body'), ('onboarding_flow', 'Onboarding Flow'), ('feature_flag', 'Feature Flag')], max_length=20)),
                ('metric', models.CharField(choices=[('conversion', 'Conversion'), ('retention', 'Retention'), ('revenue', 'Revenue'), ('engagement', 'Engagement')], default='conversion', max_length=20)),
                ('variants', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('concluded', 'Concluded')], db_index=True, default='draft', max_length=10)),
                ('winner', models.CharField(blank=True, max_length=50)),
                ('target', models.CharField(default='all', max_length=100)),
                ('min_sample_size', models.IntegerField(default=100)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.automationrule')),
            ],
            options={
                'db_table': 'automation_logs',
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['rule', 'user', 'fired_at'], name='automation__rule_id_833a4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.FloatField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experiment_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('experiment', 'user')},
            },
        ),
    ]
