# Generated by Django 5.2.10 on 2026-02-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
