# Generated by Django 5.2.10 on 2026-02-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_feedback_internal_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="trigger_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("query_limit_near", "Query limit near"),
                    ("inactive_days", "Inactive for N days"),
                    ("signup_no_query", "Signup with no queries"),
                    ("churn_signal", "Churn signal"),
                    ("milestone", "Query milestone"),
                    ("feature_unused", "Feature unused"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="trigger_2_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automationrule",
            name="trigger_logic",
            field=models.CharField(
                choices=[("and", "AND"), ("or", "OR")], default="and", max_length=3
            ),
        ),
    ]
