# Generated by Django 5.2.10 on 2026-02-26 02:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_crm_lead_bounced_invalid_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('referrer_domain', models.CharField(blank=True, db_index=True, max_length=200)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('is_bot', models.BooleanField(default=False)),
                ('method', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'site_visits',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['path', 'viewed_at'], name='site_visits_path_cd181f_idx'), models.Index(fields=['referrer_domain', 'viewed_at'], name='site_visits_referre_5a0255_idx'), models.Index(fields=['is_bot', 'viewed_at'], name='site_visits_is_bot_3fd303_idx')],
            },
        ),
    ]
