# Generated by Django 5.2.10 on 2026-02-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_country_index_sitevisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitevisit",
            name="duration_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
