# Generated by Django 5.2.12 on 2026-03-04 02:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_partner_stage_to_crmlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlead',
            name='email_opted_out',
            field=models.BooleanField(db_column='email_opted_out', default=False),
        ),
        migrations.RenameField(
            model_name='crmlead',
            old_name='email_opted_out',
            new_name='is_email_opted_out',
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='failed',
            field=models.BooleanField(db_column='failed', default=False),
        ),
        migrations.RenameField(
            model_name='emailrecipient',
            old_name='failed',
            new_name='has_failed',
        ),
        migrations.AlterField(
            model_name='experimentassignment',
            name='converted',
            field=models.BooleanField(db_column='converted', default=False),
        ),
        migrations.RenameField(
            model_name='experimentassignment',
            old_name='converted',
            new_name='has_converted',
        ),
        migrations.AlterField(
            model_name='whitepaper',
            name='gated',
            field=models.BooleanField(db_column='gated', default=True, help_text='Require email to download'),
        ),
        migrations.RenameField(
            model_name='whitepaper',
            old_name='gated',
            new_name='is_gated',
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(choices=[('dsw', 'Decision Science Workbench'), ('qms', 'Quality Management'), ('platform', 'Platform'), ('workbench', 'Workbench'), ('forge', 'Forge'), ('learn', 'Learn'), ('billing', 'Billing'), ('infrastructure', 'Infrastructure')], db_index=True, max_length=20)),
                ('quarter', models.CharField(db_index=True, max_length=7)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=15)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('professional', 'Professional'), ('team', 'Team'), ('enterprise', 'Enterprise')], default='free', max_length=15)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('change_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roadmap_items',
                'ordering': ['quarter', 'sort_order', '-created_at'],
                'indexes': [models.Index(fields=['quarter', 'status'], name='roadmap_ite_quarter_b6dcb0_idx')],
            },
        ),
    ]
