# Generated by Django 5.2.10 on 2026-01-30 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbench',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The inquiry or question being investigated', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional context about the inquiry')),
                ('template', models.CharField(choices=[('blank', 'Blank'), ('dmaic', 'DMAIC'), ('kaizen', 'Kaizen Event'), ('8d', '8D Report'), ('a3', 'A3 Problem Solving')], default='blank', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('template_state', models.JSONField(blank=True, default=dict, help_text='Template-specific state (phases, days, disciplines)')),
                ('connections', models.JSONField(blank=True, default=list, help_text='Connections between artifacts')),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Canvas layout positions for artifacts')),
                ('datasets', models.JSONField(blank=True, default=list, help_text='Datasets loaded in this workbench')),
                ('guide_observations', models.JSONField(blank=True, default=list, help_text='AI Guide observations and suggestions')),
                ('conclusion', models.TextField(blank=True, help_text='The structured response / conclusion reached')),
                ('conclusion_confidence', models.CharField(blank=True, help_text='Confidence in the conclusion', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbenches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workbenches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('dataset', 'Dataset'), ('cleaned_dataset', 'Cleaned Dataset'), ('generated_dataset', 'Generated Dataset'), ('spc_chart', 'SPC Chart'), ('capability_study', 'Capability Study'), ('anova', 'ANOVA'), ('regression', 'Regression'), ('correlation', 'Correlation'), ('descriptive_stats', 'Descriptive Statistics'), ('hypothesis_test', 'Hypothesis Test'), ('forecast', 'Forecast'), ('doe_design', 'DOE Design'), ('doe_results', 'DOE Results'), ('ml_model', 'ML Model'), ('model_metrics', 'Model Metrics'), ('feature_importance', 'Feature Importance'), ('note', 'Note'), ('hypothesis', 'Hypothesis'), ('evidence', 'Evidence'), ('conclusion', 'Conclusion'), ('report', 'Report'), ('summary', 'Summary'), ('control_plan', 'Control Plan'), ('script', 'Script'), ('visualization', 'Visualization'), ('research_findings', 'Research Findings'), ('citation', 'Citation'), ('process_map', 'Process Map'), ('fishbone', 'Fishbone Diagram'), ('five_whys', '5 Whys Analysis'), ('action_item', 'Action Item')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField(default=dict, help_text='Type-specific content (data, results, text, etc.)')),
                ('source', models.CharField(blank=True, help_text='What created this: user, analyst, researcher, coder, etc.', max_length=50)),
                ('source_artifact_id', models.UUIDField(blank=True, help_text='If derived from another artifact, link to source', null=True)),
                ('probability', models.FloatField(blank=True, help_text='Probability estimate (for hypotheses)', null=True)),
                ('supports_hypotheses', models.JSONField(blank=True, default=list, help_text='Hypothesis IDs this evidence supports')),
                ('weakens_hypotheses', models.JSONField(blank=True, default=list, help_text='Hypothesis IDs this evidence weakens')),
                ('model_path', models.CharField(blank=True, help_text='Path to saved model file', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workbench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='workbench.workbench')),
            ],
            options={
                'db_table': 'artifacts',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workbench',
            index=models.Index(fields=['user', 'status'], name='workbenches_user_id_6a0d45_idx'),
        ),
        migrations.AddIndex(
            model_name='workbench',
            index=models.Index(fields=['user', '-updated_at'], name='workbenches_user_id_8afdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['workbench', 'artifact_type'], name='artifacts_workben_6df1af_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['workbench', 'created_at'], name='artifacts_workben_50de99_idx'),
        ),
    ]
