# Generated by Django 5.2.10 on 2026-01-31 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Knowledge Graph', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('nodes', models.JSONField(blank=True, default=list, help_text='Graph nodes (hypotheses, causes, effects)')),
                ('edges', models.JSONField(blank=True, default=list, help_text='Causal edges with weights')),
                ('expansion_signals', models.JSONField(blank=True, default=list, help_text='Signals indicating incomplete causal surface')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graphs', to=settings.AUTH_USER_MODEL)),
                ('workbench', models.OneToOneField(blank=True, help_text='Associated workbench (optional - graph can be standalone)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph', to='workbench.workbench')),
            ],
            options={
                'db_table': 'knowledge_graphs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EpistemicLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('hypothesis_created', 'Hypothesis Created'), ('hypothesis_updated', 'Hypothesis Updated'), ('hypothesis_rejected', 'Hypothesis Rejected'), ('hypothesis_confirmed', 'Hypothesis Confirmed'), ('evidence_added', 'Evidence Added'), ('evidence_linked', 'Evidence Linked to Hypothesis'), ('belief_update', 'Belief Updated'), ('belief_propagation', 'Belief Propagated'), ('expansion_signal', 'Expansion Signal Triggered'), ('expansion_resolved', 'Expansion Resolved'), ('node_added', 'Node Added to Graph'), ('edge_added', 'Edge Added to Graph'), ('edge_weight_updated', 'Edge Weight Updated'), ('causal_chain_traced', 'Causal Chain Traced'), ('dead_end_identified', 'Dead End Identified'), ('insight_recorded', 'Insight Recorded'), ('inquiry_started', 'Inquiry Started'), ('inquiry_resolved', 'Inquiry Resolved'), ('methodology_selected', 'Methodology Selected')], max_length=30)),
                ('event_data', models.JSONField(default=dict, help_text='Event-specific data (before/after states, deltas, etc.)')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Snapshot of relevant context when event occurred')),
                ('led_to_insight', models.BooleanField(blank=True, help_text='Did this event lead to insight? (marked retrospectively)', null=True)),
                ('led_to_dead_end', models.BooleanField(blank=True, help_text='Did this event lead to dead end? (marked retrospectively)', null=True)),
                ('source', models.CharField(default='system', help_text='What triggered this event: user, guide, analyst, system, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epistemic_logs', to=settings.AUTH_USER_MODEL)),
                ('workbench', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epistemic_logs', to='workbench.workbench')),
                ('knowledge_graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epistemic_logs', to='workbench.knowledgegraph')),
            ],
            options={
                'db_table': 'epistemic_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='epistemic_l_user_id_c67b14_idx'), models.Index(fields=['workbench', '-created_at'], name='epistemic_l_workben_ff3cbc_idx'), models.Index(fields=['knowledge_graph', '-created_at'], name='epistemic_l_knowled_e36eac_idx'), models.Index(fields=['event_type', '-created_at'], name='epistemic_l_event_t_6fe386_idx')],
            },
        ),
    ]
