# Generated by Django 5.2.10 on 2026-02-01 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0002_add_knowledge_graph_and_epistemic_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgegraph',
            name='workbench',
            field=models.ForeignKey(blank=True, help_text='Workbench that created/modified this (for tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_graphs', to='workbench.workbench'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short title for the project', max_length=255)),
                ('hypothesis', models.TextField(help_text='The hypothesis being investigated')),
                ('description', models.TextField(blank=True, help_text='Additional context, background, or scope')),
                ('domain', models.CharField(blank=True, help_text='Domain area (manufacturing, software, healthcare, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('conclusion', models.TextField(blank=True, help_text='Final conclusion about the hypothesis')),
                ('conclusion_status', models.CharField(blank=True, choices=[('supported', 'Hypothesis Supported'), ('refuted', 'Hypothesis Refuted'), ('inconclusive', 'Inconclusive'), ('modified', 'Hypothesis Modified')], help_text='Outcome of the investigation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='epistemiclog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epistemic_logs', to='workbench.project'),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='project',
            field=models.OneToOneField(blank=True, help_text='Project this graph belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph', to='workbench.project'),
        ),
        migrations.AddField(
            model_name='workbench',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this workbench belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workbenches', to='workbench.project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='projects_user_id_05c680_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-updated_at'], name='projects_user_id_2c9bf1_idx'),
        ),
    ]
