# Generated by Django 5.2.10 on 2026-02-02 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0003_add_project_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField(help_text="The hypothesis being tested (e.g., 'High temperature causes defects')")),
                ('mechanism', models.TextField(blank=True, help_text='How this cause produces the effect')),
                ('prior_probability', models.FloatField(default=0.5, help_text='Initial probability estimate (0-1)')),
                ('current_probability', models.FloatField(default=0.5, help_text='Current probability after evidence updates')),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('supported', 'Supported'), ('refuted', 'Refuted'), ('inconclusive', 'Inconclusive')], default='investigating', max_length=20)),
                ('conclusion_notes', models.TextField(blank=True, help_text='Notes on why this hypothesis was supported/refuted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='workbench.project')),
            ],
            options={
                'verbose_name_plural': 'hypotheses',
                'db_table': 'hypotheses',
                'ordering': ['-current_probability', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='Summary of the evidence')),
                ('evidence_type', models.CharField(choices=[('statistical', 'Statistical Analysis'), ('simulation', 'Simulation Result'), ('observation', 'Observation'), ('experiment', 'Experiment'), ('research', 'Research/Literature'), ('expert', 'Expert Opinion')], default='observation', max_length=20)),
                ('direction', models.CharField(choices=[('supports', 'Supports'), ('weakens', 'Weakens'), ('neutral', 'Neutral')], default='supports', max_length=10)),
                ('strength', models.FloatField(default=0.5, help_text='Strength of evidence (0-1)')),
                ('source', models.CharField(blank=True, help_text="Where this evidence came from (e.g., 'DSW regression', 'Simulator')", max_length=100)),
                ('source_artifact_id', models.UUIDField(blank=True, help_text='Link to source artifact if from a workbench', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed data (statistics, parameters, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='workbench.hypothesis')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'db_table': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', help_text='Title for this conversation thread', max_length=255)),
                ('messages', models.JSONField(default=list, help_text='Conversation messages')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Context snapshot (hypothesis state, evidence summary, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='workbench.hypothesis')),
            ],
            options={
                'db_table': 'hypothesis_conversations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
