# Generated by Django 5.2.12 on 2026-03-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workbench", "0004_add_hypothesis_evidence_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epistemiclog",
            name="led_to_dead_end",
            field=models.BooleanField(
                blank=True,
                db_column="led_to_dead_end",
                help_text="Did this event lead to dead end? (marked retrospectively)",
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="epistemiclog",
            old_name="led_to_dead_end",
            new_name="has_led_to_dead_end",
        ),
        migrations.AlterField(
            model_name="epistemiclog",
            name="led_to_insight",
            field=models.BooleanField(
                blank=True,
                db_column="led_to_insight",
                help_text="Did this event lead to insight? (marked retrospectively)",
                null=True,
            ),
        ),
        migrations.RenameField(
            model_name="epistemiclog",
            old_name="led_to_insight",
            new_name="has_led_to_insight",
        ),
    ]
