# Generated by Django 5.2.12 on 2026-03-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0005_alter_epistemiclog_led_to_dead_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='hypothesis',
        ),
        migrations.RemoveField(
            model_name='hypothesis',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='knowledgegraph',
            name='project',
        ),
        migrations.RemoveField(
            model_name='workbench',
            name='project',
        ),
        migrations.RemoveField(
            model_name='epistemiclog',
            name='project',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.DeleteModel(
            name='Hypothesis',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
