# Generated by Django 5.2.12 on 2026-03-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_qms_phase_c_registers"),
        (
            "workbench",
            "0006_remove_deprecated_project_hypothesis_evidence_conversation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="epistemiclog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epistemic_logs",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="knowledgegraph",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workbench_knowledge_graphs",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="workbench",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workbenches",
                to="core.tenant",
            ),
        ),
    ]
