# Generated by Django 5.2.10 on 2026-01-27 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('tabular', 'Tabular'), ('text', 'Text')], default='tabular', max_length=20)),
                ('schema_def', models.JSONField()),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=8)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forge_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('tabular', 'Tabular'), ('text', 'Text')], max_length=20)),
                ('domain', models.CharField(blank=True, default='', max_length=100)),
                ('record_count', models.PositiveIntegerField()),
                ('schema_def', models.JSONField(default=dict)),
                ('quality_level', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('output_format', models.CharField(default='jsonl', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('records_generated', models.PositiveIntegerField(blank=True, null=True)),
                ('result_path', models.CharField(blank=True, default='', max_length=500)),
                ('result_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('quality_report', models.JSONField(blank=True, null=True)),
                ('cost_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='forge.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('tabular', 'Tabular'), ('text', 'Text')], max_length=20)),
                ('quality_level', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('record_count', models.PositiveIntegerField()),
                ('cost_cents', models.PositiveIntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='forge.apikey')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='forge.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='forge_job_status_a83afc_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['api_key', 'created_at'], name='forge_job_api_key_98a098_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['api_key', 'period_start', 'period_end'], name='forge_usage_api_key_c2d34b_idx'),
        ),
    ]
