# Generated by Django 5.2.10 on 2026-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_whitepaper_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitepaperdownload",
            name="path",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="whitepaperdownload",
            name="referrer",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
