# Generated by Django 5.2.10 on 2026-02-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_whitepaper_download_referrer_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whitepaperdownload",
            name="path",
        ),
        migrations.RemoveField(
            model_name="whitepaperdownload",
            name="referrer",
        ),
    ]
