# Generated by Django 5.2.12 on 2026-03-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_plandocument"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plandocument",
            old_name="roadmap_items",
            new_name="change_request_ids",
        ),
    ]
