# Generated by Django 5.2.12 on 2026-05-06 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GovernanceJudgement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique judgement record identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Tenant UUID for multi-tenant isolation",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Correlation ID for event tracing (SBL-001)",
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Parent correlation ID for event lineage",
                        null=True,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True,
                        help_text="Event that was evaluated",
                        max_length=100,
                    ),
                ),
                (
                    "event_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of event payload at evaluation time",
                    ),
                ),
                (
                    "judgment",
                    models.CharField(
                        choices=[
                            ("ALLOW", "ALLOW"),
                            ("BLOCK", "BLOCK"),
                            ("ESCALATE", "ESCALATE"),
                            ("MONITOR", "MONITOR"),
                        ],
                        db_index=True,
                        help_text="Judgment result: ALLOW, BLOCK, ESCALATE, MONITOR",
                        max_length=20,
                    ),
                ),
                (
                    "judgment_reason",
                    models.TextField(help_text="Reason for the judgment"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Confidence score (0.0-1.0) for the judgment",
                        null=True,
                    ),
                ),
                (
                    "obligations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Required actions from policy decision (POL-001 §3.1)",
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        db_index=True,
                        help_text="User or system that triggered the event",
                        max_length=255,
                    ),
                ),
                (
                    "judged_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the judgment was made",
                    ),
                ),
                (
                    "integrity_hash",
                    models.CharField(
                        help_text="SHA-256 hash for integrity verification",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "governance_judgement",
                "ordering": ["-judged_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique approval request identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Tenant UUID for multi-tenant isolation",
                    ),
                ),
                (
                    "org_domain_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ORG-001 domain for domain-scoped approvals",
                        null=True,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True, help_text="Correlation ID for tracing"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        help_text="Type of approval request", max_length=100
                    ),
                ),
                (
                    "request_title",
                    models.CharField(
                        help_text="Human-readable request title", max_length=200
                    ),
                ),
                (
                    "request_description",
                    models.TextField(
                        blank=True, default="", help_text="Detailed request description"
                    ),
                ),
                (
                    "request_payload",
                    models.JSONField(default=dict, help_text="Original request data"),
                ),
                (
                    "approval_chain",
                    models.JSONField(
                        default=list,
                        help_text="Approval chain pattern (sequential/parallel/hybrid)",
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=0, help_text="Current position in approval chain"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("EXPIRED", "EXPIRED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current approval status",
                        max_length=20,
                    ),
                ),
                (
                    "timeout_class",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("critical", "critical"),
                        ],
                        default="medium",
                        help_text="Timeout class for this request",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="When this request expires"
                    ),
                ),
                (
                    "requester_id",
                    models.CharField(
                        help_text="User who requested approval", max_length=255
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(
                        help_text="Display name of requester", max_length=255
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When request was resolved", null=True
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User who resolved the request",
                        max_length=255,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, default="", help_text="Notes on resolution"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "judgement",
                    models.ForeignKey(
                        help_text="Judgement that triggered this approval",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="governance.governancejudgement",
                    ),
                ),
            ],
            options={
                "db_table": "governance_approval_request",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GovernanceRule",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique rule instance identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Tenant UUID for multi-tenant isolation (SEC-001 §5.2)",
                    ),
                ),
                (
                    "org_domain_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ORG-001 domain for domain-scoped rules",
                        null=True,
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(
                        db_index=True,
                        help_text="Rule identifier scoped to tenant (e.g., gov-change-001)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable rule name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Detailed rule description"
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        db_index=True,
                        help_text="Event name that triggers this rule (EVT-001)",
                        max_length=100,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Condition expression (JSON) for rule evaluation",
                    ),
                ),
                (
                    "judgment_type",
                    models.CharField(
                        choices=[
                            ("ALLOW", "ALLOW"),
                            ("BLOCK", "BLOCK"),
                            ("ESCALATE", "ESCALATE"),
                            ("MONITOR", "MONITOR"),
                        ],
                        help_text="Judgment when rule matches: ALLOW, BLOCK, ESCALATE",
                        max_length=20,
                    ),
                ),
                (
                    "judgment_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Message explaining the judgment",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("governance.change", "governance.change"),
                            ("governance.approval", "governance.approval"),
                            ("governance.compliance", "governance.compliance"),
                            ("governance.quality", "governance.quality"),
                            ("governance.risk", "governance.risk"),
                            ("governance.operational", "governance.operational"),
                            ("governance.migration", "governance.migration"),
                            ("governance.infrastructure", "governance.infrastructure"),
                            ("governance.schema", "governance.schema"),
                        ],
                        db_index=True,
                        default="governance.change",
                        help_text="Rule classification (GOV-001 §4.2)",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Rule priority (lower = higher priority)",
                    ),
                ),
                (
                    "escalation_path",
                    models.JSONField(
                        default=list,
                        help_text="Approval chain for ESCALATE judgments (GOV-001 §6.2)",
                    ),
                ),
                (
                    "timeout_class",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("critical", "critical"),
                        ],
                        default="medium",
                        help_text="Timeout class for approvals (GOV-001 §12)",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.8,
                        help_text="Confidence threshold for ESCALATE (0.0-1.0)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("ACTIVE", "ACTIVE"),
                            ("DEPRECATED", "DEPRECATED"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Rule lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True, help_text="When rule becomes effective", null=True
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True, help_text="When rule expires", null=True
                    ),
                ),
                (
                    "inheritance_mode",
                    models.CharField(
                        choices=[
                            ("inherit", "inherit"),
                            ("extend", "extend"),
                            ("override", "override"),
                        ],
                        default="inherit",
                        help_text="How child domains inherit this rule",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="User who created the rule", max_length=255
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Rule version for change tracking"
                    ),
                ),
            ],
            options={
                "db_table": "governance_rule",
                "ordering": ["priority", "-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "trigger_event", "status"],
                        name="gov_rule_tenant_event_status",
                    ),
                    models.Index(
                        fields=["tenant_id", "classification", "status"],
                        name="gov_rule_tenant_class_status",
                    ),
                ],
                "unique_together": {("tenant_id", "rule_id", "org_domain_id")},
            },
        ),
        migrations.AddField(
            model_name="governancejudgement",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Rule that produced this judgment (nullable for default-permit per SBL-001 §3.5.6)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="judgements",
                to="governance.governancerule",
            ),
        ),
        migrations.CreateModel(
            name="TimeoutConfiguration",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True, help_text="Tenant UUID")),
                (
                    "timeout_class",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("critical", "critical"),
                        ],
                        help_text="Timeout class being configured",
                        max_length=20,
                    ),
                ),
                (
                    "default_hours",
                    models.IntegerField(help_text="Default timeout in hours"),
                ),
                (
                    "min_hours",
                    models.IntegerField(help_text="Minimum timeout in hours"),
                ),
                (
                    "max_hours",
                    models.IntegerField(help_text="Maximum timeout in hours"),
                ),
                (
                    "on_timeout",
                    models.CharField(
                        choices=[
                            ("ALLOW", "ALLOW"),
                            ("BLOCK", "BLOCK"),
                            ("ESCALATE", "ESCALATE"),
                            ("MONITOR", "MONITOR"),
                        ],
                        default="ESCALATE",
                        help_text="Judgment when timeout occurs",
                        max_length=20,
                    ),
                ),
                (
                    "escalation_path",
                    models.JSONField(
                        default=list, help_text="Escalation path on timeout"
                    ),
                ),
                (
                    "notification_channels",
                    models.JSONField(
                        default=list, help_text="Channels for timeout notifications"
                    ),
                ),
            ],
            options={
                "db_table": "governance_timeout_config",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("tenant_id", "timeout_class")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalSignature",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique signature identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signer_id",
                    models.CharField(
                        help_text="Unique identifier of signer", max_length=255
                    ),
                ),
                (
                    "signer_name",
                    models.CharField(
                        help_text="Printed name of signer", max_length=255
                    ),
                ),
                (
                    "signer_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Role of signer (manager, tech_lead, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("APPROVE", "APPROVE"), ("REJECT", "REJECT")],
                        help_text="Signature action",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Signature notes or rejection reason",
                    ),
                ),
                (
                    "signature_hash",
                    models.CharField(
                        help_text="SHA-256 hash of signature data", max_length=64
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When signature was applied",
                    ),
                ),
                (
                    "approval_request",
                    models.ForeignKey(
                        help_text="Approval request being signed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="governance.approvalrequest",
                    ),
                ),
            ],
            options={
                "db_table": "governance_approval_signature",
                "ordering": ["signed_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["approval_request", "signer_id"],
                        name="gov_sig_request_signer",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["tenant_id", "status", "expires_at"],
                name="gov_approval_tenant_status",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["correlation_id"], name="gov_approval_correlation"
            ),
        ),
        migrations.AddIndex(
            model_name="governancejudgement",
            index=models.Index(
                fields=["tenant_id", "event_name", "judged_at"],
                name="gov_judgement_tenant_event",
            ),
        ),
        migrations.AddIndex(
            model_name="governancejudgement",
            index=models.Index(
                fields=["correlation_id", "judged_at"], name="gov_judgement_correlation"
            ),
        ),
    ]
