# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents_api", "0079_rack_session"),
        ("core", "0024_tenant_isolation_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="A3Report",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("draft", "Draft"),
                                    ("in_progress", "In Progress"),
                                    ("review", "Under Review"),
                                    ("complete", "Complete"),
                                    ("archived", "Archived"),
                                ],
                                default="draft",
                                max_length=20,
                            ),
                        ),
                        ("background", models.TextField(blank=True)),
                        ("current_condition", models.TextField(blank=True)),
                        ("goal", models.TextField(blank=True)),
                        ("root_cause", models.TextField(blank=True)),
                        ("countermeasures", models.TextField(blank=True)),
                        ("implementation_plan", models.TextField(blank=True)),
                        ("follow_up", models.TextField(blank=True)),
                        ("imported_from", models.JSONField(blank=True, default=dict)),
                        ("embedded_diagrams", models.JSONField(blank=True, default=dict)),
                        ("last_critique", models.JSONField(blank=True, default=dict)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="a3_reports_created_ext",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "notebook",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="a3_reports_ext",
                                to="core.notebook",
                            ),
                        ),
                        (
                            "owner",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="a3_reports_ext",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="a3_reports_ext",
                                to="core.project",
                            ),
                        ),
                        (
                            "site",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="a3_records_ext",
                                to="agents_api.site",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="a3_reports",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "A3 Report",
                        "verbose_name_plural": "A3 Reports",
                        "db_table": "a3_reports",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
