# Generated by Django 5.2.12 on 2026-03-21 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents_api", "0070_project_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField(help_text="Monday of the audit week")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_audit_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_schedules",
                        to="agents_api.site",
                    ),
                ),
            ],
            options={
                "db_table": "safety_audit_schedules",
                "ordering": ["-week_start"],
                "unique_together": {("site", "week_start")},
            },
        ),
        migrations.CreateModel(
            name="FrontierZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Press mezzanine', 'Loading dock transition'",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("transition", "Transition Zone"),
                            ("overhead", "Overhead / Elevated"),
                            ("below", "Below Floor / Pit"),
                            ("infrastructure", "Hidden Infrastructure"),
                            ("temporal", "Temporal (Shift Change)"),
                            ("contractor", "Contractor Work Zone"),
                            ("storage", "Storage / Warehouse"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frontier_zones",
                        to="agents_api.site",
                    ),
                ),
            ],
            options={
                "db_table": "safety_frontier_zones",
                "ordering": ["site", "name"],
            },
        ),
        migrations.CreateModel(
            name="AuditAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_assignments",
                        to="agents_api.employee",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="safety.auditschedule",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="safety.frontierzone",
                    ),
                ),
            ],
            options={
                "db_table": "safety_audit_assignments",
                "ordering": ["target_date"],
            },
        ),
        migrations.CreateModel(
            name="FrontierCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audit_date", models.DateField()),
                ("shift", models.CharField(blank=True, default="", max_length=20)),
                (
                    "safety_observations",
                    models.JSONField(
                        default=list,
                        help_text="[{category, item, at_risk, severity, notes}]",
                    ),
                ),
                (
                    "five_s_tallies",
                    models.JSONField(
                        default=dict,
                        help_text="{sort, set_in_order, shine, standardize, sustain} — deficiency counts",
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "operator_concern",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What is your biggest safety concern in this area?",
                    ),
                ),
                (
                    "operator_improvement",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="If you could change one thing to make this area safer, what would it be?",
                    ),
                ),
                (
                    "operator_near_miss",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Have you experienced or witnessed any near-misses here recently?",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="True after card findings have been entered into FMEA",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "has_safety_crossfeed",
                    models.BooleanField(
                        default=False,
                        help_text="True if any 5S deficiency also carries safety consequence",
                    ),
                ),
                ("crossfeed_notes", models.TextField(blank=True, default="")),
                (
                    "fmea_rows_created",
                    models.JSONField(
                        default=list,
                        help_text="UUIDs of FMEARow records created from this card",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to scheduled assignment (null if ad-hoc)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to="safety.auditassignment",
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frontier_cards",
                        to="agents_api.employee",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frontier_cards",
                        to="agents_api.site",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="safety.frontierzone",
                    ),
                ),
            ],
            options={
                "db_table": "safety_frontier_cards",
                "ordering": ["-audit_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "-audit_date"],
                        name="safety_fron_site_id_239d26_idx",
                    ),
                    models.Index(
                        fields=["auditor", "-audit_date"],
                        name="safety_fron_auditor_65aca4_idx",
                    ),
                    models.Index(
                        fields=["is_processed"], name="safety_fron_is_proc_e43ed0_idx"
                    ),
                ],
            },
        ),
    ]
