# Generated by Django 5.2.12 on 2026-03-29 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0023_qms_phase_c_registers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessGraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "process_area",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_graphs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_graph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subgraphs",
                        to="graph.processgraph",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_graphs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "graph_process_graph",
            },
        ),
        migrations.CreateModel(
            name="ProcessNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("process_parameter", "Process Parameter"),
                            ("quality_characteristic", "Quality Characteristic"),
                            ("failure_mode", "Failure Mode"),
                            ("environmental_factor", "Environmental Factor"),
                            ("material_property", "Material Property"),
                            ("measurement", "Measurement"),
                            ("specification", "Specification"),
                            ("equipment", "Equipment"),
                            ("human_factor", "Human Factor"),
                            ("custom", "Custom"),
                        ],
                        default="process_parameter",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "custom_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "distribution",
                    models.JSONField(
                        blank=True,
                        help_text="Current distribution: {mean, std, shape, n, source, as_of}",
                        null=True,
                    ),
                ),
                (
                    "spec_limits",
                    models.JSONField(
                        blank=True,
                        help_text="Specification limits: {usl, lsl, target}",
                        null=True,
                    ),
                ),
                (
                    "control_limits",
                    models.JSONField(
                        blank=True,
                        help_text="Control limits: {ucl, lcl, cl}",
                        null=True,
                    ),
                ),
                (
                    "controllability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("direct", "Directly Controllable"),
                            ("indirect", "Indirectly Controllable"),
                            ("noise", "Noise (uncontrollable)"),
                            ("fixed", "Fixed"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "control_method",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "shared",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this node can be referenced by edges in sibling graphs",
                    ),
                ),
                (
                    "linked_fmis_rows",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="UUIDs of FMISRow records where this node appears",
                    ),
                ),
                (
                    "linked_equipment",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="UUIDs of MeasurementEquipment records",
                    ),
                ),
                (
                    "linked_spc_chart",
                    models.UUIDField(
                        blank=True,
                        help_text="Active SPC chart monitoring this node",
                        null=True,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        blank=True,
                        default="manual",
                        help_text="How this node was created: fmea_seed, investigation, manual, spc",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_process_nodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="graph.processgraph",
                    ),
                ),
            ],
            options={
                "db_table": "graph_process_node",
            },
        ),
        migrations.CreateModel(
            name="ProcessEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("causal", "Causal"),
                            ("correlational", "Correlational"),
                            ("confounded", "Confounded"),
                            ("specification", "Specification"),
                            ("measurement", "Measurement"),
                        ],
                        default="causal",
                        max_length=20,
                    ),
                ),
                ("effect_size", models.FloatField(blank=True, null=True)),
                ("effect_ci_lower", models.FloatField(blank=True, null=True)),
                ("effect_ci_upper", models.FloatField(blank=True, null=True)),
                (
                    "posterior_strength",
                    models.FloatField(
                        default=0.5,
                        help_text="Synara posterior — belief this relationship exists (0.0-1.0)",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("nonlinear", "Nonlinear"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "linearity",
                    models.CharField(
                        choices=[
                            ("linear", "Linear"),
                            ("nonlinear", "Nonlinear"),
                            ("threshold", "Threshold"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "operating_region",
                    models.JSONField(
                        blank=True,
                        help_text='Conditions under which this edge manifests: {"humidity": {">": 60}}',
                        null=True,
                    ),
                ),
                ("evidence_count", models.IntegerField(default=0)),
                (
                    "provenance",
                    models.CharField(
                        blank=True,
                        default="manual",
                        help_text="How created: fmea_assertion, doe, investigation, operator, spc, literature",
                        max_length=30,
                    ),
                ),
                (
                    "source_investigation",
                    models.UUIDField(
                        blank=True,
                        help_text="Investigation that created/last calibrated this edge",
                        null=True,
                    ),
                ),
                (
                    "calibration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this edge was last calibrated with empirical data",
                        null=True,
                    ),
                ),
                (
                    "interaction_terms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Interaction terms: [{modulating_node, modulation_type, fit_result, calibrated}]",
                    ),
                ),
                ("is_stale", models.BooleanField(default=False)),
                (
                    "staleness_reason",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_contradicted", models.BooleanField(default=False)),
                (
                    "contradiction_signal_id",
                    models.UUIDField(
                        blank=True,
                        help_text="LOOP-001 Signal raised for this contradiction",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_process_edges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="graph.processgraph",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="graph.processnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="graph.processnode",
                    ),
                ),
            ],
            options={
                "db_table": "graph_process_edge",
            },
        ),
        migrations.CreateModel(
            name="EdgeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effect_size", models.FloatField(blank=True, null=True)),
                (
                    "confidence_interval",
                    models.JSONField(
                        blank=True, help_text="CI: {lower, upper}", null=True
                    ),
                ),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                ("p_value", models.FloatField(blank=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("doe", "Design of Experiments"),
                            ("investigation", "Investigation"),
                            ("spc", "Statistical Process Control"),
                            ("process_confirmation", "Process Confirmation"),
                            ("forced_failure_test", "Forced Failure Test"),
                            ("gage_rr", "Gage R&R"),
                            ("operator", "Operator Observation"),
                            ("literature", "Literature / Reference"),
                            ("safety", "Safety Observation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        blank=True,
                        help_text="FK to source object (Investigation, DOE, etc.)",
                        null=True,
                    ),
                ),
                (
                    "source_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of what was observed",
                    ),
                ),
                (
                    "strength",
                    models.FloatField(
                        default=1.0,
                        help_text="Measurement reliability / study quality (0.0-1.0)",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(help_text="When the evidence was generated"),
                ),
                ("retracted", models.BooleanField(default=False)),
                ("retracted_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_edge_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_stack",
                        to="graph.processedge",
                    ),
                ),
            ],
            options={
                "db_table": "graph_edge_evidence",
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["edge", "-observed_at"],
                        name="graph_edge__edge_id_79f6a4_idx",
                    ),
                    models.Index(
                        fields=["edge", "source_type"],
                        name="graph_edge__edge_id_f3f58b_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="processgraph",
            index=models.Index(
                fields=["tenant"], name="graph_proce_tenant__2d53e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processgraph",
            index=models.Index(
                fields=["tenant", "process_area"], name="graph_proce_tenant__abff1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processnode",
            index=models.Index(
                fields=["graph", "node_type"], name="graph_proce_graph_i_eef293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processnode",
            index=models.Index(
                fields=["graph", "name"], name="graph_proce_graph_i_f3d4a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processedge",
            index=models.Index(
                fields=["graph", "relation_type"], name="graph_proce_graph_i_3e7f7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processedge",
            index=models.Index(
                fields=["source", "relation_type"],
                name="graph_proce_source__ed5da0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processedge",
            index=models.Index(
                fields=["target", "relation_type"],
                name="graph_proce_target__96d944_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processedge",
            index=models.Index(
                fields=["graph", "is_stale"], name="graph_proce_graph_i_5441b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processedge",
            index=models.Index(
                fields=["graph", "is_contradicted"],
                name="graph_proce_graph_i_1b58ec_idx",
            ),
        ),
    ]
