# Generated by Django 5.2.12 on 2026-03-29 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="edgeevidence",
            name="edge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_stack",
                to="graph.processedge",
            ),
        ),
        migrations.AddConstraint(
            model_name="processedge",
            constraint=models.UniqueConstraint(
                fields=("graph", "source", "target", "relation_type"),
                name="unique_edge_per_graph",
            ),
        ),
    ]
