# Generated by Django 5.2.12 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("graph", "0002_edge_unique_constraint_and_evidence_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="processnode",
            name="classification_tier",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("major", "Major"),
                    ("minor", "Minor"),
                ],
                default="minor",
                help_text="OLR-001 §4.7: determines evidence minimum + staleness threshold",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="processnode",
            name="customer_facing",
            field=models.BooleanField(
                default=False,
                help_text="True if this characteristic directly affects what the customer receives (from QFD)",
            ),
        ),
        migrations.AddField(
            model_name="processnode",
            name="detection_mechanism_level",
            field=models.IntegerField(
                blank=True,
                help_text="1=source prevention, 2=auto arrest, 3=auto detect, 4=auto alert, 5=structured check, 6=observation, 7=downstream, 8=undetectable",
                null=True,
            ),
        ),
    ]
