# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
import hoshin.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "agents_api",
            "0080_remove_a3report_created_by_remove_a3report_notebook_and_more",
        ),
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Employee",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("email", models.EmailField(max_length=254)),
                        ("role", models.CharField(blank=True, max_length=255)),
                        ("department", models.CharField(blank=True, max_length=255)),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "db_table": "hoshin_employees",
                        "managed": False,
                    },
                ),
                migrations.CreateModel(
                    name="Site",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("code", models.CharField(blank=True, max_length=20)),
                        ("business_unit", models.CharField(blank=True, max_length=255)),
                        ("plant_manager", models.CharField(blank=True, max_length=255)),
                        ("ci_leader", models.CharField(blank=True, max_length=255)),
                        ("controller", models.CharField(blank=True, max_length=255)),
                        ("address", models.TextField(blank=True)),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "db_table": "hoshin_sites",
                        "ordering": ["name"],
                        "managed": False,
                    },
                ),
                migrations.CreateModel(
                    name="SiteAccess",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "role",
                            models.CharField(
                                choices=[
                                    ("viewer", "Viewer"),
                                    ("member", "Member"),
                                    ("admin", "Admin"),
                                ],
                                default="member",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "db_table": "hoshin_site_access",
                        "managed": False,
                    },
                ),
                migrations.CreateModel(
                    name="ActionItem",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        ("description", models.TextField(blank=True)),
                        ("owner_name", models.CharField(blank=True, max_length=255)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("not_started", "Not Started"),
                                    ("in_progress", "In Progress"),
                                    ("completed", "Completed"),
                                    ("blocked", "Blocked"),
                                    ("cancelled", "Cancelled"),
                                ],
                                default="not_started",
                                max_length=20,
                            ),
                        ),
                        ("start_date", models.DateField(blank=True, null=True)),
                        ("end_date", models.DateField(blank=True, null=True)),
                        ("due_date", models.DateField(blank=True, null=True)),
                        ("progress", models.IntegerField(default=0)),
                        ("sort_order", models.IntegerField(default=0)),
                        (
                            "source_type",
                            models.CharField(blank=True, default="", max_length=20),
                        ),
                        ("source_id", models.UUIDField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "depends_on",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hoshin_dependents",
                                to="hoshin.actionitem",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_action_items",
                                to="core.project",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "action_items",
                        "ordering": ["sort_order", "start_date"],
                    },
                ),
                migrations.CreateModel(
                    name="ActionToken",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "action_type",
                            models.CharField(
                                choices=[
                                    ("confirm_availability", "Confirm Availability"),
                                    ("decline", "Decline"),
                                    ("update_progress", "Update Progress"),
                                    ("view_dashboard", "View Dashboard"),
                                ],
                                max_length=30,
                            ),
                        ),
                        ("scoped_to", models.JSONField(default=dict)),
                        ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                        ("expires_at", models.DateTimeField()),
                        ("used_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "employee",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_action_tokens",
                                to="hoshin.employee",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "hoshin_action_tokens",
                    },
                ),
                migrations.CreateModel(
                    name="HoshinProject",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "project_class",
                            models.CharField(
                                choices=[
                                    ("kaizen", "Kaizen Event"),
                                    ("project", "Extended Project"),
                                ],
                                default="project",
                                max_length=20,
                            ),
                        ),
                        (
                            "project_type",
                            models.CharField(
                                choices=[
                                    ("material", "Material Savings"),
                                    ("labor", "Labor Savings"),
                                    ("quality", "Quality Improvement"),
                                    ("throughput", "Throughput Improvement"),
                                    ("energy", "Energy Reduction"),
                                    ("safety", "Safety Improvement"),
                                    ("other", "Other"),
                                ],
                                default="material",
                                max_length=20,
                            ),
                        ),
                        (
                            "opportunity",
                            models.CharField(
                                choices=[
                                    ("carryover", "Carryover from Prior Year"),
                                    ("budgeted_new", "Budgeted New"),
                                    ("contingency", "Contingency"),
                                    ("unplanned", "Unplanned/Reactive"),
                                ],
                                default="budgeted_new",
                                max_length=20,
                            ),
                        ),
                        (
                            "hoshin_status",
                            models.CharField(
                                choices=[
                                    ("proposed", "Proposed"),
                                    ("budgeted", "Budgeted"),
                                    ("active", "Active"),
                                    ("delayed", "Delayed"),
                                    ("completed", "Completed"),
                                    ("aborted", "Aborted"),
                                ],
                                default="proposed",
                                max_length=20,
                            ),
                        ),
                        (
                            "fiscal_year",
                            models.IntegerField(default=hoshin.models._current_year),
                        ),
                        (
                            "annual_savings_target",
                            models.DecimalField(decimal_places=2, default=0, max_digits=12),
                        ),
                        ("calculation_method", models.CharField(blank=True, max_length=30)),
                        (
                            "custom_formula",
                            models.CharField(blank=True, default="", max_length=500),
                        ),
                        (
                            "custom_formula_desc",
                            models.CharField(blank=True, default="", max_length=200),
                        ),
                        ("kaizen_charter", models.JSONField(blank=True, default=dict)),
                        ("monthly_actuals", models.JSONField(blank=True, default=list)),
                        ("baseline_data", models.JSONField(blank=True, default=list)),
                        ("source_burst_id", models.CharField(blank=True, max_length=50)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "project",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_ext",
                                to="core.project",
                            ),
                        ),
                        (
                            "site",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hoshin_projects_ext",
                                to="hoshin.site",
                            ),
                        ),
                        (
                            "source_vsm",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hoshin_projects_ext",
                                to="agents_api.valuestreammap",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "hoshin_projects",
                        "ordering": ["-updated_at"],
                    },
                ),
                migrations.CreateModel(
                    name="HoshinKPI",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "fiscal_year",
                            models.IntegerField(default=hoshin.models._current_year),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("description", models.TextField(blank=True)),
                        (
                            "target_value",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        (
                            "actual_value",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        ("unit", models.CharField(blank=True, max_length=50)),
                        (
                            "frequency",
                            models.CharField(
                                choices=[
                                    ("monthly", "Monthly"),
                                    ("quarterly", "Quarterly"),
                                    ("annual", "Annual"),
                                ],
                                default="monthly",
                                max_length=20,
                            ),
                        ),
                        ("direction", models.CharField(default="up", max_length=10)),
                        (
                            "aggregation",
                            models.CharField(
                                choices=[
                                    ("sum", "Sum (dollars)"),
                                    ("weighted_avg", "Volume-weighted average"),
                                    ("latest", "Latest calculator result"),
                                    ("manual", "Manual entry"),
                                ],
                                default="sum",
                                max_length=20,
                            ),
                        ),
                        (
                            "derived_field",
                            models.CharField(blank=True, default="ytd_savings", max_length=30),
                        ),
                        (
                            "calculator_result_type",
                            models.CharField(blank=True, default="", max_length=60),
                        ),
                        (
                            "calculator_field",
                            models.CharField(blank=True, default="", max_length=60),
                        ),
                        ("sort_order", models.IntegerField(default=0)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "tenant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_kpis_ext",
                                to="core.tenant",
                            ),
                        ),
                        (
                            "derived_from",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hoshin_derived_kpis",
                                to="hoshin.hoshinproject",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "hoshin_kpis",
                        "ordering": ["sort_order", "name"],
                    },
                ),
                migrations.CreateModel(
                    name="ProjectTemplate",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("name", models.CharField(max_length=300)),
                        ("description", models.TextField(blank=True)),
                        (
                            "project_class",
                            models.CharField(
                                choices=[
                                    ("kaizen", "Kaizen Event"),
                                    ("project", "Extended Project"),
                                ],
                                default="project",
                                max_length=20,
                            ),
                        ),
                        (
                            "project_type",
                            models.CharField(
                                choices=[
                                    ("material", "Material Savings"),
                                    ("labor", "Labor Savings"),
                                    ("quality", "Quality Improvement"),
                                    ("throughput", "Throughput Improvement"),
                                    ("energy", "Energy Reduction"),
                                    ("safety", "Safety Improvement"),
                                    ("other", "Other"),
                                ],
                                default="material",
                                max_length=20,
                            ),
                        ),
                        (
                            "opportunity",
                            models.CharField(
                                choices=[
                                    ("carryover", "Carryover from Prior Year"),
                                    ("budgeted_new", "Budgeted New"),
                                    ("contingency", "Contingency"),
                                    ("unplanned", "Unplanned/Reactive"),
                                ],
                                default="budgeted_new",
                                max_length=20,
                            ),
                        ),
                        ("calculation_method", models.CharField(blank=True, max_length=30)),
                        ("checklist_ids", models.JSONField(blank=True, default=list)),
                        ("default_actions", models.JSONField(blank=True, default=list)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "owner",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_project_templates",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "site",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hoshin_project_templates",
                                to="agents_api.site",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_project_templates",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "project_templates",
                        "ordering": ["name"],
                    },
                ),
                migrations.CreateModel(
                    name="ResourceCommitment",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "role",
                            models.CharField(
                                choices=[
                                    ("facilitator", "Facilitator"),
                                    ("team_member", "Team Member"),
                                    ("sponsor", "Sponsor"),
                                    ("process_owner", "Process Owner"),
                                    ("subject_expert", "Subject Expert"),
                                ],
                                max_length=30,
                            ),
                        ),
                        ("start_date", models.DateField()),
                        ("end_date", models.DateField()),
                        (
                            "hours_per_day",
                            models.DecimalField(decimal_places=1, default=8, max_digits=4),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("requested", "Requested"),
                                    ("confirmed", "Confirmed"),
                                    ("active", "Active"),
                                    ("completed", "Completed"),
                                    ("declined", "Declined"),
                                ],
                                default="requested",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "employee",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_commitments",
                                to="hoshin.employee",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_commitments",
                                to="hoshin.hoshinproject",
                            ),
                        ),
                        (
                            "requested_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hoshin_requested_commitments",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "hoshin_resource_commitments",
                    },
                ),
                migrations.CreateModel(
                    name="StrategicObjective",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("title", models.CharField(max_length=500)),
                        ("description", models.TextField(blank=True)),
                        ("owner_name", models.CharField(blank=True, max_length=255)),
                        ("start_year", models.IntegerField()),
                        ("end_year", models.IntegerField()),
                        ("target_metric", models.CharField(blank=True, max_length=255)),
                        (
                            "target_value",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        ("target_unit", models.CharField(blank=True, max_length=50)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("draft", "Draft"),
                                    ("active", "Active"),
                                    ("achieved", "Achieved"),
                                    ("deferred", "Deferred"),
                                ],
                                default="draft",
                                max_length=20,
                            ),
                        ),
                        ("sort_order", models.IntegerField(default=0)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "tenant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_strategic_objectives",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "hoshin_strategic_objectives",
                        "ordering": ["sort_order", "start_year"],
                    },
                ),
                migrations.CreateModel(
                    name="AnnualObjective",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "fiscal_year",
                            models.IntegerField(default=hoshin.models._current_year),
                        ),
                        ("title", models.CharField(max_length=500)),
                        ("description", models.TextField(blank=True)),
                        ("owner_name", models.CharField(blank=True, max_length=255)),
                        (
                            "target_value",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        (
                            "actual_value",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=12, null=True
                            ),
                        ),
                        ("target_unit", models.CharField(blank=True, max_length=50)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("on_track", "On Track"),
                                    ("at_risk", "At Risk"),
                                    ("behind", "Behind"),
                                    ("achieved", "Achieved"),
                                ],
                                default="on_track",
                                max_length=20,
                            ),
                        ),
                        ("sort_order", models.IntegerField(default=0)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "site",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hoshin_annual_objectives",
                                to="hoshin.site",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_annual_objectives",
                                to="core.tenant",
                            ),
                        ),
                        (
                            "strategic_objective",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hoshin_annual_objectives",
                                to="hoshin.strategicobjective",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "hoshin_annual_objectives",
                        "ordering": ["sort_order", "title"],
                    },
                ),
                migrations.CreateModel(
                    name="XMatrixCorrelation",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "fiscal_year",
                            models.IntegerField(default=hoshin.models._current_year),
                        ),
                        (
                            "pair_type",
                            models.CharField(
                                choices=[
                                    ("strategic_annual", "Strategic <-> Annual"),
                                    ("annual_project", "Annual <-> Project"),
                                    ("project_kpi", "Project <-> KPI"),
                                    ("kpi_strategic", "KPI <-> Strategic"),
                                ],
                                max_length=30,
                            ),
                        ),
                        ("row_id", models.UUIDField()),
                        ("col_id", models.UUIDField()),
                        (
                            "strength",
                            models.CharField(
                                choices=[
                                    ("strong", "Strong"),
                                    ("moderate", "Moderate"),
                                    ("weak", "Weak"),
                                ],
                                max_length=10,
                            ),
                        ),
                        (
                            "source",
                            models.CharField(
                                choices=[("auto", "Auto-suggested"), ("manual", "Manual")],
                                default="manual",
                                max_length=10,
                            ),
                        ),
                        (
                            "is_confirmed",
                            models.BooleanField(db_column="confirmed", default=False),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "tenant",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="hoshin_xmatrix_correlations",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "hoshin_xmatrix_correlations",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
