# Generated by Django 5.2.14 on 2026-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoshin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoshinkpi",
            name="pcl_slug",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PCL measure slug. When set, actual_value reads from PCL instead of local storage.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="strategicobjective",
            name="pcl_slug",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PCL measure slug for live tracking of this objective's target metric.",
                max_length=200,
            ),
        ),
    ]
