# Generated by Django 5.2.12 on 2026-04-14 18:41

import core.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="AgentLog",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("agent", models.CharField(max_length=50)),
                        ("action", models.CharField(max_length=50)),
                        ("latency_ms", models.IntegerField(null=True)),
                        ("is_success", models.BooleanField(db_column="success", default=True)),
                        ("error_message", models.TextField(blank=True)),
                        ("metadata", models.TextField(blank=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="triage_agent_logs",
                                to="core.tenant",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="triage_agent_logs",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "agents_api_agentlog",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="TriageResult",
                    fields=[
                        (
                            "id",
                            models.CharField(max_length=50, primary_key=True, serialize=False),
                        ),
                        ("original_filename", models.CharField(max_length=255)),
                        ("cleaned_csv", core.encryption.EncryptedTextField()),
                        ("report_markdown", core.encryption.EncryptedTextField()),
                        ("summary_json", core.encryption.EncryptedTextField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="triage_results",
                                to="core.tenant",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="triage_triage_results",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "agents_api_triageresult",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
