# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a3", "0001_initial"),
        (
            "agents_api",
            "0080_remove_a3report_created_by_remove_a3report_notebook_and_more",
        ),
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RCASession",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("title", models.CharField(blank=True, max_length=255)),
                        ("event", models.TextField(help_text="Description of the incident")),
                        (
                            "chain",
                            models.JSONField(
                                default=list, help_text="Causal chain steps with critiques"
                            ),
                        ),
                        ("root_cause", models.TextField(blank=True)),
                        ("countermeasure", models.TextField(blank=True)),
                        ("evaluation", models.TextField(blank=True)),
                        ("reopen_reason", models.TextField(blank=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("draft", "Draft"),
                                    ("investigating", "Investigating"),
                                    ("root_cause_identified", "Root Cause Identified"),
                                    ("verified", "Verified"),
                                    ("closed", "Closed"),
                                ],
                                default="draft",
                                max_length=25,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("embedding", models.BinaryField(blank=True, null=True)),
                        (
                            "a3_report",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="rca_sessions_ext",
                                to="a3.a3report",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="rca_sessions_created_ext",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "owner",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="rca_sessions_ext",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="rca_sessions_ext",
                                to="core.project",
                            ),
                        ),
                        (
                            "site",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="rca_records_ext",
                                to="agents_api.site",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="rca_sessions",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "RCA Session",
                        "verbose_name_plural": "RCA Sessions",
                        "db_table": "rca_sessions",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
