# Generated by Django 5.2.12 on 2026-03-28 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_qms_phase_c_registers"),
        ("notifications", "0003_add_calibration_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("capa_status", "CAPA Status Change"),
                    ("ncr_overdue", "NCR Overdue"),
                    ("ncr_assigned", "NCR Assigned"),
                    ("approval_request", "Approval Request"),
                    ("esig_request", "E-Signature Request"),
                    ("spc_alarm", "SPC Alarm"),
                    ("review_due", "Management Review Due"),
                    ("doc_review", "Document Review Reminder"),
                    ("training_due", "Training Due"),
                    ("training_expired", "Training Expired"),
                    ("audit_scheduled", "Audit Scheduled"),
                    ("action_due", "Action Item Due"),
                    ("assignment", "Assignment Change"),
                    ("system", "System Notification"),
                    ("incident_created", "Incident Created"),
                    ("incident_escalated", "Incident Escalated"),
                    ("incident_resolved", "Incident Resolved"),
                    ("commitment_requested", "Commitment Requested"),
                    ("commitment_confirmed", "Commitment Confirmed"),
                    ("commitment_declined", "Commitment Declined"),
                    ("routine_reminder", "Routine Reminder"),
                    ("routine_streak", "Routine Streak"),
                    ("routine_missed", "Routine Missed"),
                    ("diary_reminder", "Daily Diary Reminder"),
                    ("goal_due", "Goal Approaching Deadline"),
                    ("hansei_due", "Hansei Kai Reflection Due"),
                    ("afe_approval", "AFE Approval"),
                    ("complaint_assigned", "Complaint Assigned"),
                    ("complaint_status", "Complaint Status Change"),
                    ("audit_finding", "Audit Finding"),
                    ("checklist_complete", "Checklist Completed"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("secret", models.CharField(max_length=64)),
                ("event_patterns", models.JSONField(default=list)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "webhook_endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("exhausted", "Exhausted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, default="")),
                ("attempt_count", models.IntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["user", "is_active"], name="webhook_user_active"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["tenant", "is_active"], name="webhook_tenant_active"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["endpoint", "-created_at"], name="whd_endpoint_created"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "next_retry_at"], name="whd_status_retry"
            ),
        ),
    ]
