# Generated by Django 5.2.12 on 2026-03-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sched", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="schedule",
            name="syn_idx_sched_tnt_enabled",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="enabled",
            field=models.BooleanField(
                db_column="enabled",
                db_index=True,
                default=True,
                help_text="Whether schedule is active",
            ),
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="enabled",
            new_name="is_enabled",
        ),
        migrations.AlterField(
            model_name="taskexecution",
            name="success",
            field=models.BooleanField(
                db_column="success",
                default=False,
                help_text="Whether execution succeeded",
            ),
        ),
        migrations.RenameField(
            model_name="taskexecution",
            old_name="success",
            new_name="is_success",
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["tenant_id", "is_enabled", "next_run_at"],
                name="syn_idx_sched_tnt_enabled",
            ),
        ),
    ]
