# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "agents_api",
            "0080_remove_a3report_created_by_remove_a3report_notebook_and_more",
        ),
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="FMEA",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        ("description", models.TextField(blank=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("draft", "Draft"),
                                    ("active", "Active"),
                                    ("review", "Under Review"),
                                    ("complete", "Complete"),
                                ],
                                default="draft",
                                max_length=20,
                            ),
                        ),
                        (
                            "fmea_type",
                            models.CharField(
                                choices=[
                                    ("process", "Process FMEA"),
                                    ("design", "Design FMEA"),
                                    ("system", "System FMEA"),
                                ],
                                default="process",
                                max_length=20,
                            ),
                        ),
                        (
                            "scoring_method",
                            models.CharField(
                                choices=[
                                    ("rpn", "Risk Priority Number"),
                                    ("ap", "Action Priority (AIAG/VDA)"),
                                ],
                                default="rpn",
                                max_length=10,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="fmea_fmeas_created",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "owner",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="fmea_fmeas",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="fmea_fmeas",
                                to="core.project",
                            ),
                        ),
                        (
                            "site",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="fmea_records_ext",
                                to="agents_api.site",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="fmea_fmeas",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "FMEA",
                        "verbose_name_plural": "FMEAs",
                        "db_table": "fmeas",
                        "ordering": ["-updated_at"],
                    },
                ),
                migrations.CreateModel(
                    name="FMEARow",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("sort_order", models.IntegerField(default=0)),
                        ("process_step", models.CharField(blank=True, max_length=255)),
                        ("failure_mode", models.CharField(max_length=255)),
                        ("effect", models.TextField(blank=True)),
                        (
                            "severity",
                            models.IntegerField(
                                default=1,
                                validators=[
                                    django.core.validators.MinValueValidator(1),
                                    django.core.validators.MaxValueValidator(10),
                                ],
                            ),
                        ),
                        ("cause", models.TextField(blank=True)),
                        (
                            "occurrence",
                            models.IntegerField(
                                default=1,
                                validators=[
                                    django.core.validators.MinValueValidator(1),
                                    django.core.validators.MaxValueValidator(10),
                                ],
                            ),
                        ),
                        ("current_controls", models.TextField(blank=True)),
                        ("prevention_controls", models.TextField(blank=True)),
                        ("detection_controls", models.TextField(blank=True)),
                        (
                            "failure_mode_class",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("form", "Form"),
                                    ("fit", "Fit"),
                                    ("function", "Function"),
                                    ("safety", "Safety"),
                                    ("regulatory", "Regulatory"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "control_type",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("prevent", "Prevention"),
                                    ("detect", "Detection"),
                                    ("both", "Prevention & Detection"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "detection",
                            models.IntegerField(
                                default=1,
                                validators=[
                                    django.core.validators.MinValueValidator(1),
                                    django.core.validators.MaxValueValidator(10),
                                ],
                            ),
                        ),
                        ("rpn", models.IntegerField(default=1)),
                        ("recommended_action", models.TextField(blank=True)),
                        ("action_owner", models.CharField(blank=True, max_length=255)),
                        (
                            "action_status",
                            models.CharField(
                                choices=[
                                    ("not_started", "Not Started"),
                                    ("in_progress", "In Progress"),
                                    ("complete", "Complete"),
                                ],
                                default="not_started",
                                max_length=20,
                            ),
                        ),
                        ("revised_severity", models.IntegerField(blank=True, null=True)),
                        ("revised_occurrence", models.IntegerField(blank=True, null=True)),
                        ("revised_detection", models.IntegerField(blank=True, null=True)),
                        ("revised_rpn", models.IntegerField(blank=True, null=True)),
                        (
                            "spc_measurement",
                            models.CharField(blank=True, default="", max_length=255),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "fmea",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="rows",
                                to="fmea.fmea",
                            ),
                        ),
                        (
                            "hypothesis_link",
                            models.ForeignKey(
                                blank=True,
                                help_text="Hypothesis this failure mode relates to",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="fmea_rows_ext",
                                to="core.hypothesis",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "fmea_rows",
                        "ordering": ["sort_order"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
