# Generated by Django 5.2.12 on 2026-03-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_api_key_model"),
        ("core", "0024_tenant_isolation_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="core.tenant",
            ),
        ),
    ]
