# Generated by Django 5.2.12 on 2026-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_apikey_tenant_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitecode",
            name="trial_days",
            field=models.PositiveIntegerField(
                default=14, help_text="Number of days the trial lasts."
            ),
        ),
        migrations.AddField(
            model_name="invitecode",
            name="trial_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Free"),
                    ("founder", "Founder ($19/month)"),
                    ("pro", "Professional ($49/month)"),
                    ("team", "Team ($99/month)"),
                    ("enterprise", "Enterprise ($299/month)"),
                ],
                default="",
                help_text="Tier to grant on registration (blank = no trial grant).",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When trial tier access expires. Null = no active trial.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_original_tier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tier to revert to when trial expires (usually 'free').",
                max_length=12,
            ),
        ),
    ]
