# Generated by Django 5.2.12 on 2026-05-12 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlowchartTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("definition", models.JSONField(default=dict)),
                (
                    "devices_used",
                    models.JSONField(
                        default=list, help_text="List of plugin names for query index."
                    ),
                ),
                ("is_shared", models.BooleanField(default=False)),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="flowchart.flowcharttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "flowchart_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowchartInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("definition", models.JSONField(default=dict)),
                ("is_scratch", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="flowchart.flowcharttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "flowchart_instance",
                "ordering": ["-created_at"],
            },
        ),
    ]
