# Generated by Django 5.2.12 on 2026-05-06 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomEventDefinition",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True,
                        help_text="Event name following domain.entity.action pattern (EVT-001 §4.1)",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Semantic version (MAJOR.MINOR.PATCH)",
                        max_length=20,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable display name (e.g., 'Document Created')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the event"
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional help text explaining when/how the event is triggered",
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to detailed documentation for this event",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("workflow", "Workflow"),
                            ("integration", "Integration"),
                            ("notification", "Notification"),
                            ("analytics", "Analytics"),
                            ("compliance", "Compliance"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        help_text="Event category for organization",
                        max_length=50,
                    ),
                ),
                (
                    "audit",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this event should be included in audit logs",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=3, help_text="Event priority (1=critical, 5=low)"
                    ),
                ),
                (
                    "payload_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON Schema for event payload validation",
                    ),
                ),
                (
                    "workflow_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this event can be used as a workflow trigger (editable via marketplace)",
                    ),
                ),
                (
                    "developer_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Developer who created this event (UUID reference)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id_owner",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant that owns this event (null for global events)",
                        null=True,
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="If True, event is available to all tenants (marketplace)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_validation", "Pending Validation"),
                            ("validation_failed", "Validation Failed"),
                            ("validated", "Validated"),
                            ("published", "Published"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validation errors if validation failed",
                    ),
                ),
                (
                    "validation_warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validation warnings",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the event was validated", null=True
                    ),
                ),
                (
                    "validated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who/what validated the event (system or reviewer)",
                        max_length=100,
                    ),
                ),
                (
                    "marketplace_listing_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Associated marketplace listing UUID if published",
                        null=True,
                    ),
                ),
                (
                    "compliance_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Compliance references (e.g., ['ISO 27001 A.12.1', 'SOC 2 CC7.2'])",
                    ),
                ),
                (
                    "install_count",
                    models.IntegerField(
                        default=0, help_text="Number of tenant installations"
                    ),
                ),
                (
                    "emit_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total number of times this event has been emitted",
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("experimental", "Experimental"),
                            ("stable", "Stable"),
                            ("deprecated", "Deprecated"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Version lifecycle status per EVT-001 §6",
                        max_length=20,
                    ),
                ),
                (
                    "version_checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 checksum of payload_schema for integrity",
                        max_length=64,
                    ),
                ),
                (
                    "sunset_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this version reaches end of life (min 180 days from deprecation)",
                        null=True,
                    ),
                ),
                (
                    "successor_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Recommended successor version to migrate to",
                        max_length=20,
                    ),
                ),
                (
                    "migration_path",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Migration instructions from this version to successor",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the event was published to marketplace",
                        null=True,
                    ),
                ),
                (
                    "deprecated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the event was deprecated", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Event Definition",
                "verbose_name_plural": "Custom Event Definitions",
                "db_table": "events_custom_definition",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["event_name", "version"],
                        name="events_custom_name_version",
                    ),
                    models.Index(
                        fields=["developer_id", "status"],
                        name="events_custom_dev_status",
                    ),
                    models.Index(
                        fields=["tenant_id_owner", "status"],
                        name="events_custom_tenant_status",
                    ),
                    models.Index(
                        fields=["status", "is_global"],
                        name="events_custom_status_global",
                    ),
                    models.Index(fields=["category"], name="events_custom_category"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_name", "version", "tenant_id_owner"),
                        name="events_custom_unique_name_version_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventFamily",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable family name (e.g., 'Task Lifecycle')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g., 'task-lifecycle')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what semantic change this family represents",
                    ),
                ),
                (
                    "family_key",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical family key (e.g., 'task.lifecycle', 'risk.assessment')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Semantic version (MAJOR.MINOR.PATCH)",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lifecycle", "Lifecycle Events"),
                            ("state_change", "State Change Events"),
                            ("threshold", "Threshold Events"),
                            ("creation", "Creation Events"),
                            ("workflow", "Workflow Events"),
                            ("audit", "Audit Events"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        help_text="Family category for organization",
                        max_length=30,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domain this family belongs to (e.g., 'task', 'risk', 'form')",
                        max_length=50,
                    ),
                ),
                (
                    "max_events_per_emission",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum events that can be emitted per family invocation (cascade limit)",
                    ),
                ),
                (
                    "require_schema_compatibility",
                    models.BooleanField(
                        default=True,
                        help_text="All member events must have compatible payload schemas",
                    ),
                ),
                (
                    "allow_partial_emission",
                    models.BooleanField(
                        default=False,
                        help_text="If True, emit available events even if some fail validation",
                    ),
                ),
                (
                    "emission_order",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential (ordered)"),
                            ("parallel", "Parallel (unordered)"),
                        ],
                        default="sequential",
                        help_text="How member events are emitted",
                        max_length=20,
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Max family emissions per tenant per minute",
                    ),
                ),
                (
                    "rate_limit_per_hour",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Max family emissions per tenant per hour",
                    ),
                ),
                (
                    "tenant_id_owner",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant that owns this family (null for system families)",
                        null=True,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True for built-in system families",
                    ),
                ),
                (
                    "developer_id_owner",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Developer who created this family (UUID reference)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Enable/disable family"
                    ),
                ),
                (
                    "workflow_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this family can be used as a workflow trigger",
                    ),
                ),
                (
                    "emit_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="Total number of times this family was emitted",
                    ),
                ),
                (
                    "last_emitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this family was emitted",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event Family",
                "verbose_name_plural": "Event Families",
                "db_table": "events_family",
                "ordering": ["domain", "name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["family_key", "is_active"],
                        name="events_family_key_active",
                    ),
                    models.Index(
                        fields=["tenant_id_owner", "is_active"],
                        name="events_family_tenant_active",
                    ),
                    models.Index(
                        fields=["domain", "category"], name="events_family_domain_cat"
                    ),
                    models.Index(
                        fields=["workflow_enabled", "is_active"],
                        name="events_family_wfl_active",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "tenant_id_owner"),
                        name="events_family_unique_slug_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventSchemaRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical event name following EVT-001 §4.1 (domain.entity.action)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version (MAJOR.MINOR.PATCH)", max_length=10
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        help_text="JSON Schema definition for event payload validation"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable/disable schema validation enforcement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event Schema Registry",
                "verbose_name_plural": "Event Schema Registries",
                "db_table": "events_schema_registry",
                "ordering": ["event_name", "-version"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["event_name", "is_active"],
                        name="events_schema_name_active",
                    ),
                    models.Index(
                        fields=["tenant_id", "is_active"],
                        name="events_schema_tenant_active",
                    ),
                    models.Index(fields=["version"], name="events_schema_version"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemEventType",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical event name (domain.entity.action pattern)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable display name (e.g., 'Document Created')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what triggers this event",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional help text for users configuring this event",
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to detailed documentation",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("record", "Record"),
                            ("form", "Form"),
                            ("task", "Task"),
                            ("workflow", "Workflow"),
                            ("approval", "Approval"),
                            ("schedule", "Schedule"),
                            ("integration", "Integration"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="system",
                        help_text="Event category for organization",
                        max_length=50,
                    ),
                ),
                (
                    "workflow_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this event can be used as a workflow trigger",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable/disable this event type",
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Module that emits this event (e.g., 'document', 'form', 'workflow')",
                        max_length=50,
                    ),
                ),
                (
                    "payload_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema describing the event payload",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID (null for global system events per EVT-001 §4)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Event Type",
                "verbose_name_plural": "System Event Types",
                "db_table": "events_system_type",
                "ordering": ["category", "event_name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["workflow_enabled", "is_active"],
                        name="events_sys_wfl_active",
                    ),
                    models.Index(
                        fields=["category", "is_active"],
                        name="events_sys_category_active",
                    ),
                    models.Index(fields=["source_module"], name="events_sys_module"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomEventInstallation",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id_owner",
                    models.UUIDField(
                        db_index=True, help_text="Tenant that installed this event"
                    ),
                ),
                (
                    "installed_version",
                    models.CharField(
                        help_text="Version that was installed", max_length=20
                    ),
                ),
                (
                    "auto_update",
                    models.BooleanField(
                        default=True, help_text="Automatically update to latest version"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emit_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="Number of times this event was emitted by this tenant",
                    ),
                ),
                (
                    "last_emitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this event was emitted",
                        null=True,
                    ),
                ),
                (
                    "event_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="events.customeventdefinition",
                    ),
                ),
                (
                    "installed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Event Installation",
                "verbose_name_plural": "Custom Event Installations",
                "db_table": "events_custom_installation",
                "ordering": ["-installed_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id_owner", "is_active"],
                        name="events_install_tenant_active",
                    ),
                    models.Index(
                        fields=["event_definition", "is_active"],
                        name="events_install_event_active",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_definition", "tenant_id_owner"),
                        name="events_install_unique_event_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventFamilyMember",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID (nullable - isolation via family FK per EVT-001 §13.3)",
                        null=True,
                    ),
                ),
                (
                    "event_name_override",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Direct event name (if event is from catalog, not DB)",
                        max_length=255,
                    ),
                ),
                (
                    "emission_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order in which this event emits (lower = first)",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="If True, family emission fails if this event fails",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable/disable this member",
                    ),
                ),
                (
                    "payload_template",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Template for transforming family payload to this event's schema",
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSONLogic condition - only emit if condition is true",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_definition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Custom event reference (if custom event)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memberships",
                        to="events.customeventdefinition",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        help_text="Parent family this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="events.eventfamily",
                    ),
                ),
                (
                    "system_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="System event reference (if system event)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memberships",
                        to="events.systemeventtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Family Member",
                "verbose_name_plural": "Event Family Members",
                "db_table": "events_family_member",
                "ordering": ["family", "emission_order"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["family", "is_active"],
                        name="events_member_family_active",
                    ),
                    models.Index(
                        fields=["system_event"], name="events_member_sys_event"
                    ),
                    models.Index(
                        fields=["event_definition"], name="events_member_custom_event"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("system_event__isnull", False)),
                        fields=("family", "system_event"),
                        name="events_member_unique_sys",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("event_definition__isnull", False)),
                        fields=("family", "event_definition"),
                        name="events_member_unique_custom",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("event_name_override__gt", "")),
                        fields=("family", "event_name_override"),
                        name="events_member_unique_override",
                    ),
                ],
            },
        ),
    ]
