# Generated by Django 5.2.12 on 2026-05-06 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventSchema",
            fields=[
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this schema",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Event name (e.g., 'user.login', 'task.created')",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Schema version (e.g., '1.0.0', '2.1.0')",
                        max_length=50,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 checksum of schema_json", max_length=64
                    ),
                ),
                (
                    "schema_json",
                    models.JSONField(
                        help_text="JSON Schema definition (draft-07 compatible)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the active version for validation",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant identifier (null for global schemas) (SEC-001 §5.2)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this schema version was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of this schema version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Schema",
                "verbose_name_plural": "Event Schemas",
                "db_table": "schema_event_schema",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["name", "is_active"], name="schema_name_active"
                    ),
                    models.Index(
                        fields=["tenant_id", "name"], name="schema_tenant_name"
                    ),
                    models.Index(fields=["checksum"], name="schema_checksum"),
                ],
                "unique_together": {("name", "version", "tenant_id")},
            },
        ),
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique schema identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Correlation ID for causal trace graph (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant identifier (null for global schemas, SEC-001 §5.2)",
                        null=True,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domain namespace (e.g., 'qms', 'healthcare', 'manufacturing')",
                        max_length=100,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        db_index=True,
                        help_text="Entity type (e.g., 'ncr', 'patient', 'workorder')",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version (MAJOR.MINOR.PATCH)", max_length=50
                    ),
                ),
                (
                    "definition",
                    models.JSONField(
                        help_text="Full schema definition in JSON/YAML format"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Review"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("DEPRECATED", "Deprecated"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Schema lifecycle status",
                        max_length=15,
                    ),
                ),
                (
                    "governance_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Governance tags (PII, PHI, SAFETY, FINANCIAL, PROPRIETARY)",
                    ),
                ),
                (
                    "governance_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="CGS-1001 approval workflow metadata",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 checksum of definition", max_length=64
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this schema was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this schema was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="User ID of schema author",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema",
                "verbose_name_plural": "Schemas",
                "db_table": "syn_schema",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["domain", "entity"], name="idx_schema_domain_entity"
                    ),
                    models.Index(
                        fields=["tenant_id", "status"], name="idx_schema_tenant_status"
                    ),
                    models.Index(
                        fields=["status", "domain"], name="idx_schema_status_domain"
                    ),
                ],
                "unique_together": {("domain", "entity", "version", "tenant_id")},
            },
        ),
        migrations.CreateModel(
            name="SchemaVersion",
            fields=[
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique schema version identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Correlation ID for causal trace graph (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="Tenant identifier (SEC-001 §5.2)"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domain namespace (e.g., 'marketplace', 'qms', 'risk')",
                        max_length=100,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        db_index=True,
                        help_text="Entity type (e.g., 'MarketplaceListing', 'NCR')",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version (MAJOR.MINOR.PATCH)", max_length=20
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this version was applied",
                    ),
                ),
                (
                    "migration_hash",
                    models.CharField(
                        help_text="SHA-256 hash of migration definition for integrity verification",
                        max_length=64,
                    ),
                ),
                (
                    "migration_definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Migration operations and metadata",
                    ),
                ),
                (
                    "applied_by",
                    models.CharField(
                        help_text="User or system that applied this migration",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applying", "Applying"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        db_index=True,
                        default="applied",
                        help_text="Migration status",
                        max_length=20,
                    ),
                ),
                (
                    "rollback_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this migration can be rolled back",
                    ),
                ),
                (
                    "rollback_definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Rollback operations if available",
                    ),
                ),
                (
                    "previous_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Previous version before this migration",
                        max_length=20,
                    ),
                ),
                (
                    "migration_duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Migration execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if migration failed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Version",
                "verbose_name_plural": "Schema Versions",
                "db_table": "syn_schema_version",
                "ordering": ["-applied_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "domain", "entity"],
                        name="idx_schemaversion_tde",
                    ),
                    models.Index(
                        fields=["domain", "entity", "version"],
                        name="idx_schemaversion_dev",
                    ),
                    models.Index(
                        fields=["status", "applied_at"], name="idx_schemaversion_status"
                    ),
                ],
                "unique_together": {("tenant_id", "domain", "entity", "version")},
            },
        ),
        migrations.CreateModel(
            name="SchemaBehavior",
            fields=[
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique behavior identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Correlation ID for causal trace graph (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Behavior name", max_length=100)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("on_create", "On Create"),
                            ("on_update", "On Update"),
                            ("on_delete", "On Delete"),
                            ("on_validate", "On Validate"),
                        ],
                        help_text="When this behavior triggers",
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("emit_event", "Emit Event"),
                            ("generate_task", "Generate Task"),
                            ("invoke_policy", "Invoke Policy"),
                            ("invoke_reasoning", "Invoke Reasoning"),
                        ],
                        help_text="Type of action to perform",
                        max_length=20,
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration for action (event_name, task_reflex, policy_namespace)",
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True,
                        help_text="Optional JSONLogic condition for conditional execution",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Execution priority (lower = higher priority)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this behavior is active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this behavior was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this behavior was last updated"
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        help_text="Parent schema",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviors",
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Behavior",
                "verbose_name_plural": "Schema Behaviors",
                "db_table": "syn_schema_behavior",
                "ordering": ["schema", "priority", "name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["schema", "trigger_event"],
                        name="idx_schemabehavior_trigger",
                    ),
                    models.Index(
                        fields=["action_type", "is_active"],
                        name="idx_schemabehavior_action",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SchemaNode",
            fields=[
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique node identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Correlation ID for causal trace graph (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Field/node name", max_length=100)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("datetime", "DateTime"),
                            ("object", "Object"),
                            ("array", "Array"),
                            ("reference", "Reference"),
                        ],
                        help_text="Data type for this node",
                        max_length=20,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False, help_text="Whether this field is required"
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True, help_text="Default value for this field", null=True
                    ),
                ),
                (
                    "constraints",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation constraints (min, max, regex, enum, format)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Display metadata (display_name, description, units)",
                    ),
                ),
                (
                    "cognitive_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cognitive metadata (confidence_threshold, reasoning_workflow)",
                    ),
                ),
                (
                    "governance_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Governance tags for this field (PII, PHI, etc.)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within schema"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this node was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this node was last updated"
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        help_text="Parent schema",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="schema.schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Node",
                "verbose_name_plural": "Schema Nodes",
                "db_table": "syn_schema_node",
                "ordering": ["schema", "order", "name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["schema", "name"], name="idx_schemanode_schema_name"
                    ),
                    models.Index(fields=["node_type"], name="idx_schemanode_type"),
                ],
                "unique_together": {("schema", "name")},
            },
        ),
        migrations.CreateModel(
            name="SchemaValidationLog",
            fields=[
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID",
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        default="system",
                        help_text="User or system that performed the action",
                        max_length=255,
                    ),
                ),
                (
                    "actor_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of actor", null=True
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="State before change"
                    ),
                ),
                (
                    "after_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="State after change"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, help_text="Delta of changes"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for change"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context"
                    ),
                ),
                (
                    "entry_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="SHA-256 hash of entry content",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of previous entry (chain link)",
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Immutable creation timestamp",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When validation occurred",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True,
                        help_text="Event name being validated",
                        max_length=255,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant identifier (SEC-001 §5.2)",
                        null=True,
                    ),
                ),
                ("valid", models.BooleanField(help_text="Whether validation passed")),
                (
                    "errors",
                    models.JSONField(
                        default=list, help_text="Validation errors if any"
                    ),
                ),
                (
                    "payload_sample",
                    models.JSONField(
                        blank=True,
                        help_text="Sample of the payload (for debugging)",
                        null=True,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Correlation ID from event",
                        null=True,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        blank=True,
                        help_text="Schema used for validation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schema.eventschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Validation Log",
                "verbose_name_plural": "Schema Validation Logs",
                "db_table": "schema_validation_log",
                "ordering": ["-timestamp"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["event_name", "timestamp"], name="schemalog_event_time"
                    ),
                    models.Index(
                        fields=["tenant_id", "valid"], name="schemalog_tenant_valid"
                    ),
                    models.Index(fields=["valid"], name="schemalog_valid"),
                ],
            },
        ),
    ]
