# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Report",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("report_type", models.CharField(max_length=30)),
                        ("title", models.CharField(max_length=255)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("draft", "Draft"),
                                    ("in_progress", "In Progress"),
                                    ("review", "Under Review"),
                                    ("complete", "Complete"),
                                    ("archived", "Archived"),
                                ],
                                default="draft",
                                max_length=20,
                            ),
                        ),
                        ("sections", models.JSONField(blank=True, default=dict)),
                        ("imported_from", models.JSONField(blank=True, default=dict)),
                        ("embedded_diagrams", models.JSONField(blank=True, default=dict)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "owner",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="reports_ext",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="reports_ext",
                                to="core.project",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="reports_reports",
                                to="core.tenant",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Report",
                        "verbose_name_plural": "Reports",
                        "db_table": "reports",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
