# Generated by Django 5.2.10 on 2026-01-18 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('times_used', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('used_by', models.ManyToManyField(blank=True, related_name='invite_codes_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invite_codes',
            },
        ),
    ]
