# Generated by Django 5.2.10 on 2026-02-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('technology', 'Technology'), ('finance', 'Finance'), ('education', 'Education'), ('government', 'Government'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (1-50)'), ('medium', 'Medium (51-500)'), ('large', 'Large (501-5000)'), ('enterprise', 'Enterprise (5000+)')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('engineer', 'Engineer'), ('manager', 'Manager'), ('analyst', 'Analyst'), ('executive', 'Executive'), ('student', 'Student'), ('consultant', 'Consultant'), ('researcher', 'Researcher'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='incomplete', max_length=20),
        ),
    ]
