# Generated by Django 5.2.12 on 2026-03-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_dataexportrequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loginattempt",
            old_name="was_successful",
            new_name="is_successful",
        ),
    ]
