# Generated by Django 5.2.10 on 2026-02-02 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('team', 'Team'), ('enterprise', 'Enterprise')], default='team', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('max_members', models.IntegerField(default=10)),
                ('max_projects', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_tenant',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('concept', 'Concept'), ('variable', 'Variable'), ('actor', 'Actor'), ('event', 'Event'), ('data_source', 'Data Source'), ('finding', 'Finding'), ('custom', 'Custom')], default='concept', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('custom_type', models.CharField(blank=True, max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('typical_min', models.FloatField(blank=True, null=True)),
                ('typical_max', models.FloatField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'db_table': 'core_entity',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='Brief description of what this evidence shows')),
                ('details', models.TextField(blank=True, help_text='Detailed description or methodology')),
                ('source_type', models.CharField(choices=[('observation', 'Observation'), ('simulation', 'Simulation'), ('analysis', 'Data Analysis'), ('experiment', 'Experiment'), ('research', 'Research'), ('expert', 'Expert Opinion'), ('calculation', 'Calculation')], default='observation', max_length=20)),
                ('source_description', models.CharField(blank=True, help_text="Where this evidence came from (e.g., 'Coder simulation', 'DSW analysis')", max_length=255)),
                ('result_type', models.CharField(choices=[('statistical', 'Statistical'), ('categorical', 'Categorical'), ('quantitative', 'Quantitative'), ('qualitative', 'Qualitative')], default='qualitative', max_length=20)),
                ('confidence', models.FloatField(default=0.8, help_text='How reliable is this evidence? (0.0 to 1.0)')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('confidence_interval_low', models.FloatField(blank=True, null=True)),
                ('confidence_interval_high', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('statistical_test', models.CharField(blank=True, max_length=100)),
                ('measured_value', models.FloatField(blank=True, null=True)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('raw_output', models.JSONField(blank=True, default=dict, help_text='Raw structured output from analysis/simulation')),
                ('is_reproducible', models.BooleanField(default=False)),
                ('code_reference', models.TextField(blank=True, help_text='Code that generated this evidence (for reproduction)')),
                ('data_reference', models.CharField(blank=True, help_text='Reference to data used (file path, dataset ID)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence', to=settings.AUTH_USER_MODEL)),
                ('related_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.entity')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'db_table': 'core_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Knowledge Graph', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph', to='core.tenant')),
            ],
            options={
                'db_table': 'core_knowledge_graph',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.knowledgegraph'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('problem_statement', models.TextField(blank=True, help_text='What are you trying to understand or solve?')),
                ('effect_description', models.TextField(blank=True, help_text='What effect or outcome are you observing?')),
                ('effect_magnitude', models.CharField(blank=True, help_text="How big is the effect? (e.g., '40% increase', '$50k loss')", max_length=255)),
                ('domain', models.CharField(blank=True, help_text="Domain area (e.g., 'manufacturing', 'SaaS', 'healthcare')", max_length=100)),
                ('stakeholders', models.JSONField(blank=True, default=list, help_text='Who is affected or involved?')),
                ('constraints', models.JSONField(blank=True, default=list, help_text='Constraints on the investigation or solution')),
                ('available_data', models.TextField(blank=True, help_text='What data do you have access to?')),
                ('can_experiment', models.BooleanField(default=True, help_text='Can you run controlled experiments?')),
                ('methodology', models.CharField(choices=[('none', 'General Investigation'), ('dmaic', 'Six Sigma DMAIC'), ('doe', 'Design of Experiments'), ('pdca', 'Plan-Do-Check-Act'), ('a3', 'A3 Problem Solving'), ('scientific', 'Scientific Method')], default='scientific', max_length=20)),
                ('current_phase', models.CharField(choices=[('define', 'Define Problem'), ('hypothesize', 'Generate Hypotheses'), ('gather', 'Gather Evidence'), ('analyze', 'Analyze'), ('conclude', 'Conclude'), ('measure', 'Measure'), ('improve', 'Improve'), ('control', 'Control')], default='define', max_length=20)),
                ('phase_history', models.JSONField(blank=True, default=list, help_text='History of phase transitions [{phase, entered_at, notes}]')),
                ('interview_state', models.JSONField(blank=True, help_text='Saved interview progress', null=True)),
                ('interview_completed', models.BooleanField(default=False)),
                ('resolution_summary', models.TextField(blank=True, help_text='What did we learn? What was the answer?')),
                ('resolution_confidence', models.FloatField(blank=True, help_text='Confidence in resolution (0.0 to 1.0)', null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('graph', models.ForeignKey(blank=True, help_text='Knowledge graph this project references', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.knowledgegraph')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_projects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_projects', to='core.tenant')),
            ],
            options={
                'db_table': 'core_project',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField(help_text="The hypothesis statement (e.g., 'The UI change caused the sales drop')")),
                ('mechanism', models.TextField(blank=True, help_text='How would this cause the effect? The proposed mechanism.')),
                ('prior_probability', models.FloatField(default=0.5, help_text='Initial probability before evidence (0.0 to 1.0)')),
                ('current_probability', models.FloatField(default=0.5, help_text='Current probability after all evidence (0.0 to 1.0)')),
                ('probability_history', models.JSONField(blank=True, default=list, help_text='History of probability updates [{probability, evidence_id, timestamp}]')),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('uncertain', 'Uncertain'), ('merged', 'Merged')], default='active', max_length=20)),
                ('confirmation_threshold', models.FloatField(default=0.9, help_text='Probability above which hypothesis is confirmed')),
                ('rejection_threshold', models.FloatField(default=0.1, help_text='Probability below which hypothesis is rejected')),
                ('is_testable', models.BooleanField(default=True, help_text='Can this hypothesis be tested with evidence?')),
                ('test_suggestions', models.JSONField(blank=True, default=list, help_text='Suggested ways to test this hypothesis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hypotheses', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='core.hypothesis')),
                ('related_entities', models.ManyToManyField(blank=True, help_text='Entities from knowledge graph related to this hypothesis', related_name='hypotheses', to='core.entity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='core.project')),
            ],
            options={
                'verbose_name_plural': 'hypotheses',
                'db_table': 'core_hypothesis',
                'ordering': ['-current_probability', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('causes', 'causes'), ('prevents', 'prevents'), ('enables', 'enables'), ('influences', 'influences'), ('correlates_with', 'correlates with'), ('inversely_correlates', 'inversely correlates with'), ('is_part_of', 'is part of'), ('contains', 'contains'), ('is_type_of', 'is a type of'), ('has_type', 'has type'), ('happens_before', 'happens before'), ('happens_after', 'happens after'), ('happens_during', 'happens during'), ('triggers', 'triggers'), ('related_to', 'related to'), ('depends_on', 'depends on'), ('contradicts', 'contradicts'), ('supports', 'supports'), ('custom', 'custom')], default='related_to', max_length=30)),
                ('custom_type', models.CharField(blank=True, max_length=100)),
                ('strength', models.FloatField(default=1.0, help_text='Strength of relationship (0.0 to 1.0)')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence in this relationship existing (0.0 to 1.0)')),
                ('effect_size', models.FloatField(blank=True, help_text='Estimated causal effect size', null=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('evidence_count', models.IntegerField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.knowledgegraph')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.entity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.entity')),
            ],
            options={
                'db_table': 'core_relationship',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
            ],
            options={
                'db_table': 'core_membership',
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likelihood_ratio', models.FloatField(default=1.0, help_text='P(evidence|H true) / P(evidence|H false). >1 supports, <1 opposes')),
                ('direction', models.CharField(choices=[('supports', 'Supports'), ('opposes', 'Opposes'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('reasoning', models.TextField(blank=True, help_text='Why does this evidence support/oppose this hypothesis with this strength?')),
                ('is_manual', models.BooleanField(default=True, help_text='Was this link created by user (True) or inferred by system (False)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When this evidence was applied to update hypothesis probability', null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypothesis_links', to='core.evidence')),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='core.hypothesis')),
            ],
            options={
                'db_table': 'core_evidence_link',
                'ordering': ['-created_at'],
                'unique_together': {('hypothesis', 'evidence')},
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['graph', 'entity_type'], name='core_entity_graph_i_ea599a_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['graph', 'name'], name='core_entity_graph_i_845fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='hypothesis',
            index=models.Index(fields=['project', 'status'], name='core_hypoth_project_78670d_idx'),
        ),
        migrations.AddIndex(
            model_name='hypothesis',
            index=models.Index(fields=['project', '-current_probability'], name='core_hypoth_project_58aae9_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['graph', 'relation_type'], name='core_relati_graph_i_0bed28_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['source', 'relation_type'], name='core_relati_source__40d75f_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['target', 'relation_type'], name='core_relati_target__418c46_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='core_projec_user_id_9ca548_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'status'], name='core_projec_tenant__994f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-updated_at'], name='core_projec_updated_fe33f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tenant__isnull', True), ('user__isnull', False)), models.Q(('tenant__isnull', False), ('user__isnull', True)), _connector='OR'), name='project_has_single_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('tenant', 'user')},
        ),
        migrations.AddConstraint(
            model_name='knowledgegraph',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tenant__isnull', True), ('user__isnull', False)), models.Q(('tenant__isnull', False), ('user__isnull', True)), _connector='OR'), name='graph_has_single_owner'),
        ),
    ]
