# Generated by Django 5.2.10 on 2026-02-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_dataset_and_experiment_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='synara_state',
            field=models.JSONField(blank=True, help_text='Persisted Synara belief engine state (graph, expansion signals, update history)', null=True),
        ),
    ]
