# Generated by Django 5.2.10 on 2026-02-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_synara_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypothesis',
            name='mechanism',
        ),
        migrations.RemoveField(
            model_name='project',
            name='available_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='effect_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='effect_magnitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stakeholders',
        ),
        migrations.AddField(
            model_name='evidence',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.project'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='because_clause',
            field=models.TextField(blank=True, help_text='BECAUSE [mechanism]... Why do we think this will happen?'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='data_requirements',
            field=models.JSONField(blank=True, default=list, help_text='Data needed to test [{variable, source, available}]'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='dependent_var_unit',
            field=models.CharField(blank=True, help_text='Unit of measure for Y', max_length=50),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='dependent_variable',
            field=models.CharField(blank=True, help_text='Y variable - what we measure as effect', max_length=255),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='if_clause',
            field=models.TextField(blank=True, help_text='IF [condition/change]... What is being changed or tested?'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='independent_var_values',
            field=models.JSONField(blank=True, default=list, help_text='Possible values or levels of X [list]'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='independent_variable',
            field=models.CharField(blank=True, help_text='X variable - what we change or observe as cause', max_length=255),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='predicted_direction',
            field=models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('change', 'Change'), ('no_change', 'No Change')], default='change', help_text='Expected direction of change in Y', max_length=20),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='predicted_magnitude',
            field=models.CharField(blank=True, help_text="Expected size of effect (e.g., '>10%', '~5 units')", max_length=100),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='rationale',
            field=models.TextField(blank=True, help_text='Why do we think this hypothesis might be true? Prior knowledge, observations.'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='success_criteria',
            field=models.TextField(blank=True, help_text='What evidence would confirm this? What would refute it?'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='test_method',
            field=models.TextField(blank=True, help_text='How will we test this? Experiment design, analysis approach.'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='then_clause',
            field=models.TextField(blank=True, help_text='THEN [expected outcome]... What do we expect to happen?'),
        ),
        migrations.AddField(
            model_name='project',
            name='assumptions',
            field=models.JSONField(blank=True, default=list, help_text='Assumptions being made [list]'),
        ),
        migrations.AddField(
            model_name='project',
            name='champion_name',
            field=models.CharField(blank=True, help_text='Executive sponsor name', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='champion_title',
            field=models.CharField(blank=True, help_text='Executive sponsor title', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='goal_baseline',
            field=models.CharField(blank=True, help_text="Current baseline value (e.g., '87%')", max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='goal_deadline',
            field=models.DateField(blank=True, help_text='Target completion date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='goal_metric',
            field=models.CharField(blank=True, help_text="What metric are we improving? (e.g., 'First Pass Yield')", max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='goal_statement',
            field=models.TextField(blank=True, help_text='Full goal statement (can be generated from fields below)'),
        ),
        migrations.AddField(
            model_name='project',
            name='goal_target',
            field=models.CharField(blank=True, help_text="Target value (e.g., '95%')", max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='goal_unit',
            field=models.CharField(blank=True, help_text="Unit of measure (e.g., '%', 'ppm', 'hours')", max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_customer',
            field=models.TextField(blank=True, help_text='Customer impact: complaints, returns, satisfaction, churn'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_delivery',
            field=models.TextField(blank=True, help_text='Delivery impact: on-time delivery, lead time, backlog'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_financial',
            field=models.TextField(blank=True, help_text='Financial impact: cost, revenue loss, scrap, rework'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_other',
            field=models.JSONField(blank=True, default=list, help_text='Other impacts [list of {category, description}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_quality',
            field=models.TextField(blank=True, help_text='Quality impact: defect rates, yield, specs out of tolerance'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_regulatory',
            field=models.TextField(blank=True, help_text='Regulatory/compliance impact: violations, audit findings'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_safety',
            field=models.TextField(blank=True, help_text='Safety impact: injuries, near-misses, risk level'),
        ),
        migrations.AddField(
            model_name='project',
            name='leader_name',
            field=models.CharField(blank=True, help_text='Project leader name', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='leader_title',
            field=models.CharField(blank=True, help_text='Project leader title', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='milestones',
            field=models.JSONField(blank=True, default=list, help_text='Key milestones [{name, target_date, actual_date, status}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_magnitude',
            field=models.TextField(blank=True, help_text='How much? How often? Quantify the problem.'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_since',
            field=models.CharField(blank=True, help_text='When did this problem start? First observed date/event.', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_trend',
            field=models.CharField(choices=[('increasing', 'Getting Worse'), ('stable', 'Stable'), ('decreasing', 'Improving'), ('unknown', 'Unknown')], default='unknown', help_text='Is the problem getting worse, stable, or improving?', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_whats',
            field=models.JSONField(blank=True, default=list, help_text='What is happening? What is the defect/issue? [list of statements]'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_whens',
            field=models.JSONField(blank=True, default=list, help_text='When does it happen? Time patterns, shifts, seasons [list]'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_wheres',
            field=models.JSONField(blank=True, default=list, help_text='Where is it occurring? Location, process step, product line [list]'),
        ),
        migrations.AddField(
            model_name='project',
            name='resolution_actions',
            field=models.JSONField(blank=True, default=list, help_text='Actions taken [{action, owner, due_date, status}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='resolution_verification',
            field=models.TextField(blank=True, help_text='How was the fix verified? Evidence of effectiveness.'),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_in',
            field=models.JSONField(blank=True, default=list, help_text='What is IN scope [list of items]'),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_out',
            field=models.JSONField(blank=True, default=list, help_text='What is OUT of scope [list of items]'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_completion',
            field=models.DateField(blank=True, help_text='Target project completion date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.JSONField(blank=True, default=list, help_text='Team members [list of {name, role, department}]'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='code_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='data_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='raw_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='source_description',
            field=models.CharField(blank=True, help_text='Where this evidence came from', max_length=255),
        ),
        migrations.AlterField(
            model_name='evidencelink',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencelink',
            name='is_manual',
            field=models.BooleanField(default=True, help_text='Created by user (True) or inferred by system (False)?'),
        ),
        migrations.AlterField(
            model_name='evidencelink',
            name='reasoning',
            field=models.TextField(blank=True, help_text='Why does this evidence support/oppose with this strength?'),
        ),
        migrations.AlterField(
            model_name='experimentdesign',
            name='design_spec',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='experimentdesign',
            name='design_type',
            field=models.CharField(choices=[('full_factorial', 'Full Factorial'), ('fractional_factorial', 'Fractional Factorial'), ('ccd', 'Central Composite'), ('box_behnken', 'Box-Behnken'), ('plackett_burman', 'Plackett-Burman'), ('definitive_screening', 'Definitive Screening'), ('taguchi', 'Taguchi'), ('custom', 'Custom')], default='full_factorial', max_length=30),
        ),
        migrations.AlterField(
            model_name='experimentdesign',
            name='execution_review',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentdesign',
            name='execution_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentdesign',
            name='factors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='experimentdesign',
            name='responses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='is_testable',
            field=models.BooleanField(default=True, help_text='Can this hypothesis be tested with available data/experiments?'),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='related_entities',
            field=models.ManyToManyField(blank=True, related_name='hypotheses', to='core.entity'),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='statement',
            field=models.TextField(help_text='Full hypothesis statement (can be generated from structured fields)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='can_experiment',
            field=models.BooleanField(default=True, help_text='Can controlled experiments be run?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='constraints',
            field=models.JSONField(blank=True, default=list, help_text='Constraints and limitations [list]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.CharField(choices=[('define', 'Define'), ('measure', 'Measure'), ('analyze', 'Analyze'), ('improve', 'Improve'), ('control', 'Control')], default='define', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, help_text='Domain area (manufacturing, SaaS, healthcare, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.knowledgegraph'),
        ),
        migrations.AlterField(
            model_name='project',
            name='interview_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase_history',
            field=models.JSONField(blank=True, default=list, help_text='Phase transitions [{phase, entered_at, notes}]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='Consolidated problem statement (can be generated from 5W2H fields)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resolution_summary',
            field=models.TextField(blank=True, help_text='What was the root cause? What did we learn?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='synara_state',
            field=models.JSONField(blank=True, help_text='Persisted Synara belief engine state', null=True),
        ),
    ]
