# Generated by Django 5.2.10 on 2026-02-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_org_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_seat_item_id',
            field=models.CharField(blank=True, help_text='Stripe subscription item ID for the seat line item (si_xxx)', max_length=255),
        ),
    ]
