# Generated by Django 5.2.10 on 2026-02-20 20:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenant_stripe_seat_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypothesis',
            name='current_probability',
            field=models.FloatField(default=0.5, help_text='Current probability after all evidence (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='prior_probability',
            field=models.FloatField(default=0.5, help_text='Initial probability before evidence (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['project', '-created_at'], name='core_eviden_project_a52d58_idx'),
        ),
    ]
