# Generated by Django 5.2.10 on 2026-02-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_study_action_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='changelog',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
