# Generated by Django 5.2.12 on 2026-03-08 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0013_add_measurement_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary key (UUID v4)', primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique correlation ID for CTG tracing (CTG-001 §5)', unique=True)),
                ('parent_correlation_id', models.UUIDField(blank=True, db_index=True, help_text='Parent entity correlation ID for causal chain (CTG-001 §5)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (AUD-001)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (AUD-001)')),
                ('created_by', models.CharField(blank=True, default='', help_text='User ID who created this record', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', help_text='User ID who last modified this record', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag (DAT-001 §9)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (DAT-001 §9)', null=True)),
                ('deleted_by', models.CharField(blank=True, default='', help_text='User ID who deleted this record', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensible metadata (MOD-001 §10)')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('concluded', 'Concluded'), ('exported', 'Exported')], db_index=True, default='open', max_length=20)),
                ('synara_state', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('export_package', models.JSONField(blank=True, help_text='Conclusion package JSON (§9) frozen at export time', null=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('exported_to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_investigations', to='core.project')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_investigations', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, help_text='Previous version this was reopened from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='core.investigation')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='core.tenant')),
            ],
            options={
                'db_table': 'core_investigation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='contributor', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investigation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_investigation_membership',
                'unique_together': {('investigation', 'user')},
            },
        ),
        migrations.AddField(
            model_name='investigation',
            name='members',
            field=models.ManyToManyField(related_name='investigations', through='core.InvestigationMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvestigationToolLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('tool_type', models.CharField(max_length=30)),
                ('tool_function', models.CharField(choices=[('information', 'Information'), ('inference', 'Inference'), ('intent', 'Intent'), ('report', 'Report')], max_length=20)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_links', to='core.investigation')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_investigation_tool_link',
                'unique_together': {('investigation', 'content_type', 'object_id')},
            },
        ),
    ]
