# Generated by Django 5.2.12 on 2026-03-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_investigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='Evidence this record replaces (same source/tool, newer run)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='core.evidence'),
        ),
    ]
