# Generated by Django 5.2.12 on 2026-03-14 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0064_add_ncr_supplier_fk"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0015_add_evidence_supersedes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("active", "Active"),
                            ("concluded", "Concluded"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("baseline_summary", models.TextField(blank=True, default="")),
                (
                    "baseline_metric",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("baseline_value", models.FloatField(blank=True, null=True)),
                (
                    "baseline_unit",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("baseline_date", models.DateField(blank=True, null=True)),
                ("current_value", models.FloatField(blank=True, null=True)),
                ("current_date", models.DateField(blank=True, null=True)),
                ("synara_state", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concluded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "baseline_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agents_api.dswresult",
                    ),
                ),
                (
                    "current_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agents_api.dswresult",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The charter this notebook executes against",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebooks",
                        to="core.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebooks",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_notebook",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HanseiKai",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("what_went_well", models.TextField()),
                ("what_didnt", models.TextField()),
                ("what_next", models.TextField()),
                (
                    "key_learning",
                    models.TextField(
                        help_text="One sentence distillation — the yokoten seed"
                    ),
                ),
                ("carry_forward", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hansei_kai",
                        to="core.notebook",
                    ),
                ),
            ],
            options={
                "db_table": "core_hansei_kai",
            },
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Auto-increment within notebook (Trial 1, 2, 3...)"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("before_value", models.FloatField(blank=True, null=True)),
                ("before_date", models.DateField(blank=True, null=True)),
                ("after_value", models.FloatField(blank=True, null=True)),
                ("after_date", models.DateField(blank=True, null=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("improved", "Improved"),
                            ("no_effect", "No Effect"),
                            ("degraded", "Degraded"),
                            ("inconclusive", "Inconclusive"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verdict_narrative",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="System-generated narrative with statistical significance",
                    ),
                ),
                ("delta", models.FloatField(blank=True, null=True)),
                ("delta_pct", models.FloatField(blank=True, null=True)),
                ("adopted", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "after_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agents_api.dswresult",
                    ),
                ),
                (
                    "before_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agents_api.dswresult",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_trials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_links",
                    models.ManyToManyField(
                        blank=True, related_name="trials", to="core.evidence"
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trials",
                        to="core.notebook",
                    ),
                ),
            ],
            options={
                "db_table": "core_trial",
                "ordering": ["sequence"],
                "unique_together": {("notebook", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="NotebookPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("calculator", "Calculator"),
                            ("simulator", "Simulator"),
                            ("analysis", "Analysis"),
                            ("note", "Note"),
                            ("attachment", "Attachment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "source_tool",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tool identifier: oee, kanban, takt, cpk, plantsim, dsw, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "inputs",
                    models.JSONField(
                        blank=True, default=dict, help_text="Frozen inputs"
                    ),
                ),
                (
                    "outputs",
                    models.JSONField(
                        blank=True, default=dict, help_text="Frozen outputs"
                    ),
                ),
                (
                    "rendered_html",
                    models.TextField(blank=True, default="", help_text="Frozen visual"),
                ),
                ("narrative", models.TextField(blank=True, default="")),
                ("sequence", models.PositiveIntegerField(default=0)),
                (
                    "trial_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("before", "Before"),
                            ("after", "After"),
                            ("supporting", "Supporting"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.notebook",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="core.trial",
                    ),
                ),
            ],
            options={
                "db_table": "core_notebook_page",
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="notebook",
            name="active_trial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.trial",
            ),
        ),
        migrations.CreateModel(
            name="TrialAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("raise_capa", "Raise CAPA"),
                            ("schedule_audit", "Schedule Verification Audit"),
                            ("request_doc_update", "Request Document Update"),
                            ("flag_training_gap", "Flag Training Gap"),
                            ("flag_fmea_update", "Flag FMEA Update"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_type", models.CharField(max_length=30)),
                ("target_id", models.UUIDField()),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="core.trial",
                    ),
                ),
            ],
            options={
                "db_table": "core_trial_action",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrialToolLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("tool_type", models.CharField(max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("before", "Before"),
                            ("after", "After"),
                            ("supporting", "Supporting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_links",
                        to="core.trial",
                    ),
                ),
            ],
            options={
                "db_table": "core_trial_tool_link",
            },
        ),
        migrations.CreateModel(
            name="Yokoten",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learning", models.TextField()),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Conditions that made this work",
                    ),
                ),
                (
                    "applicable_to",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for matching: process types, defect categories, industries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yokoten",
                        to="core.notebook",
                    ),
                ),
                (
                    "source_trial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yokoten",
                        to="core.trial",
                    ),
                ),
            ],
            options={
                "db_table": "core_yokoten",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YokotenAdoption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adopted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helped", "Helped"),
                            ("not_applicable", "Not Applicable"),
                            ("adapted", "Adapted"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "adopted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adopted_yokoten",
                        to="core.notebook",
                    ),
                ),
                (
                    "yokoten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoptions",
                        to="core.yokoten",
                    ),
                ),
            ],
            options={
                "db_table": "core_yokoten_adoption",
            },
        ),
        migrations.AddIndex(
            model_name="notebook",
            index=models.Index(
                fields=["owner", "status"], name="core_notebo_owner_i_5654bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notebook",
            index=models.Index(
                fields=["project", "status"], name="core_notebo_project_4a0b90_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trialtoollink",
            unique_together={("trial", "content_type", "object_id")},
        ),
        migrations.AlterUniqueTogether(
            name="yokotenadoption",
            unique_together={("yokoten", "target_notebook")},
        ),
    ]
