# Generated by Django 5.2.12 on 2026-03-18 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_front_page_digest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HaradaGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horizon', models.CharField(choices=[('long_term', '3-5 Year'), ('fiscal_year', 'Current FY'), ('monthly', 'Current Month'), ('immediate', 'Immediate')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('revised', 'Revised'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('service_at_home', models.TextField(blank=True, default='', help_text='How this goal serves others at home')),
                ('service_at_work', models.TextField(blank=True, default='', help_text='How this goal serves others at work')),
                ('perspectives', models.JSONField(blank=True, default=dict, help_text='{"tangible_self": [], "tangible_others": [], "intangible_self": [], "intangible_others": []}')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Links FY → long-term, month → FY, immediate → month', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.haradagoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harada_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_harada_goal',
                'ordering': ['horizon', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(choices=[('harada_36', 'Harada 36'), ('ci_readiness', 'CI Readiness')], max_length=20)),
                ('dimension_number', models.PositiveSmallIntegerField(help_text='1-36 for Harada, 1-12 for CI Readiness')),
                ('name', models.CharField(help_text="e.g., 'Preparation', 'Process vs. Person Attribution'", max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('thinking', 'Thinking Faculty'), ('action', 'Action Taking'), ('human', 'Human Talent'), ('leadership', 'Leadership'), ('ci', 'CI Readiness')], max_length=20)),
                ('response_type', models.CharField(choices=[('likert', 'Likert 1-5'), ('forced_choice', 'Forced Choice Scenario')], max_length=20)),
                ('question_text', models.TextField(blank=True, default='', help_text='Likert: the question. Forced-choice: general description (scenarios in ScenarioBank).')),
            ],
            options={
                'db_table': 'core_question_dimension',
                'ordering': ['instrument', 'dimension_number'],
                'unique_together': {('instrument', 'dimension_number')},
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_key', models.CharField(help_text="Short ID for tracking (e.g., 'd1_s1', 'd1_s2')", max_length=20)),
                ('situation', models.TextField(help_text='The scenario description presented to the user')),
                ('option_a', models.TextField(help_text='Archetype A response')),
                ('option_a_label', models.CharField(help_text="Short label for clustering (e.g., 'system_thinker')", max_length=50)),
                ('option_b', models.TextField()),
                ('option_b_label', models.CharField(max_length=50)),
                ('option_c', models.TextField()),
                ('option_c_label', models.CharField(max_length=50)),
                ('option_d', models.TextField()),
                ('option_d_label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.questiondimension')),
            ],
            options={
                'db_table': 'core_scenario',
                'ordering': ['dimension', 'scenario_key'],
                'unique_together': {('dimension', 'scenario_key')},
            },
        ),
        migrations.CreateModel(
            name='Window64',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_number', models.PositiveSmallIntegerField(help_text='Which of the 8 goals this belongs to (1-8)')),
                ('position', models.PositiveSmallIntegerField(help_text='0 = center (goal), 1-8 = surrounding cells')),
                ('cell_type', models.CharField(choices=[('goal', 'Goal (center)'), ('task', 'Task (one-time)'), ('routine', 'Routine (recurring)')], max_length=10)),
                ('text', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harada_goal', models.ForeignKey(blank=True, help_text='Optional link to the long-term goal this supports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='window_cells', to='core.haradagoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window64_cells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_window64',
                'ordering': ['goal_number', 'position'],
                'unique_together': {('user', 'goal_number', 'position')},
            },
        ),
        migrations.CreateModel(
            name='DailyDiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('daily_phrase', models.CharField(blank=True, default='', help_text='Motivational phrase for the day', max_length=200)),
                ('time_blocks', models.JSONField(blank=True, default=list)),
                ('top_tasks', models.JSONField(blank=True, default=list, help_text='[{"task": "...", "completed": bool}, ...]')),
                ('score_overall', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_mental', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_body', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_work', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_relations', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_life', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_learning', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_routines', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, default='', help_text='Challenges and positive takeaways')),
                ('what_differently', models.TextField(blank=True, default='', help_text='What would you have done differently?')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes / future actions')),
                ('score_comments', models.JSONField(blank=True, default=dict, help_text='{"mental": "Anxiety", "body": "Tired", ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_diaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_daily_diary',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_version', models.PositiveSmallIntegerField(default=1, help_text='Version of the instrument (for retake comparison)')),
                ('session_id', models.UUIDField(default=uuid.uuid4, help_text='Groups responses from the same sitting')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='1-5 for Likert dimensions', null=True)),
                ('option_chosen', models.CharField(blank=True, default='', help_text="Archetype label chosen (e.g., 'system_thinker')", max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.questiondimension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(blank=True, help_text='Which scenario was presented (for retake analysis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='core.scenario')),
            ],
            options={
                'db_table': 'core_questionnaire_response',
                'indexes': [models.Index(fields=['user', 'dimension', '-timestamp'], name='core_questi_user_id_ccd0e0_idx'), models.Index(fields=['user', 'session_id'], name='core_questi_user_id_e3721f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoutineCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_checks', to=settings.AUTH_USER_MODEL)),
                ('window_cell', models.ForeignKey(help_text='The routine being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.window64')),
            ],
            options={
                'db_table': 'core_routine_check',
                'indexes': [models.Index(fields=['user', 'date'], name='core_routin_user_id_a68bc5_idx')],
                'unique_together': {('user', 'window_cell', 'date')},
            },
        ),
    ]
