# Generated by Django 5.2.12 on 2026-03-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_qms_phase_c_registers"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontpagedigest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="front_page_digests",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="trainingcenter",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_centers",
                to="core.tenant",
            ),
        ),
    ]
