# Generated by Django 5.2.12 on 2026-03-27 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0073_a3_notebook_link"),
        ("core", "0023_qms_phase_c_registers"),
        ("loop", "0003_alter_processconfirmation_controlled_document_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FMIS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "methodology",
                    models.CharField(
                        choices=[
                            ("aiag_4th", "AIAG 4th Edition (manual 1-10)"),
                            (
                                "svend_bayesian",
                                "Svend Bayesian (posteriors + integer mapping)",
                            ),
                            (
                                "svend_full",
                                "Svend Full (posteriors + operational definitions required)",
                            ),
                        ],
                        default="svend_bayesian",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fmis_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmis_documents",
                        to="core.investigation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fmis_documents",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "FMIS",
                "verbose_name_plural": "FMIS Documents",
                "db_table": "loop_fmis",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FMISRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                ("failure_mode_text", models.CharField(max_length=500)),
                (
                    "effect_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "cause_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("prevention_control", models.TextField(blank=True, default="")),
                ("detection_control", models.TextField(blank=True, default="")),
                (
                    "severity_alpha",
                    models.JSONField(
                        default=list,
                        help_text="Dirichlet alpha vector [α₁, α₂, α₃, α₄, α₅]. Default: [1,1,1,1,1]",
                    ),
                ),
                (
                    "severity_manual",
                    models.IntegerField(
                        blank=True,
                        help_text="Manual override / initial committee estimate (1-10)",
                        null=True,
                    ),
                ),
                (
                    "severity_method",
                    models.CharField(
                        default="manual",
                        help_text="manual or bayesian — determines which value is displayed",
                        max_length=10,
                    ),
                ),
                (
                    "occurrence_alpha",
                    models.FloatField(default=1.0, help_text="Beta prior α"),
                ),
                (
                    "occurrence_beta",
                    models.FloatField(default=1.0, help_text="Beta prior β"),
                ),
                (
                    "occurrence_failures",
                    models.IntegerField(
                        default=0, help_text="Cumulative failure count"
                    ),
                ),
                (
                    "occurrence_units",
                    models.IntegerField(
                        default=0, help_text="Cumulative units observed"
                    ),
                ),
                (
                    "occurrence_manual",
                    models.IntegerField(
                        blank=True, help_text="Manual override (1-10)", null=True
                    ),
                ),
                (
                    "occurrence_method",
                    models.CharField(default="manual", max_length=10),
                ),
                (
                    "detection_alpha",
                    models.FloatField(default=1.0, help_text="Beta prior α"),
                ),
                (
                    "detection_beta",
                    models.FloatField(default=1.0, help_text="Beta prior β"),
                ),
                (
                    "detection_detected",
                    models.IntegerField(
                        default=0, help_text="Cumulative detections from FFTs"
                    ),
                ),
                (
                    "detection_injected",
                    models.IntegerField(
                        default=0, help_text="Cumulative injections from FFTs"
                    ),
                ),
                (
                    "detection_manual",
                    models.IntegerField(
                        blank=True, help_text="Manual override (1-10)", null=True
                    ),
                ),
                ("detection_method", models.CharField(default="manual", max_length=10)),
                (
                    "rpn",
                    models.IntegerField(
                        default=0, help_text="S × O × D (computed on save)"
                    ),
                ),
                ("last_evidence_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cause_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmis_causes",
                        to="core.entity",
                    ),
                ),
                (
                    "effect_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmis_effects",
                        to="core.entity",
                    ),
                ),
                (
                    "failure_mode_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmis_failure_modes",
                        to="core.entity",
                    ),
                ),
                (
                    "fmis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="loop.fmis",
                    ),
                ),
                (
                    "investigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmis_rows",
                        to="core.investigation",
                    ),
                ),
                (
                    "legacy_fmea_row",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to legacy AIAG FMEARow for migration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmis_row",
                        to="agents_api.fmearow",
                    ),
                ),
            ],
            options={
                "db_table": "loop_fmis_row",
                "ordering": ["-rpn", "created_at"],
            },
        ),
    ]
