# Generated by Django 5.2.12 on 2026-03-29 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loop", "0007_remove_fmisrow_entity_fks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commitment",
            name="linked_artifacts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {type, id, title, created_at} for artifacts linked to this commitment",
            ),
        ),
        migrations.AddField(
            model_name="commitment",
            name="resource_needs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {description, status: needed|available|blocked} resource requirements",
            ),
        ),
        migrations.CreateModel(
            name="CommitmentNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitment_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="loop.commitment",
                    ),
                ),
            ],
            options={
                "db_table": "loop_commitment_note",
                "ordering": ["created_at"],
            },
        ),
    ]
