# Generated by Django 5.2.12 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loop", "0012_tenant_site_isolation_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="signal",
            name="linked_process_node_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="UUIDs of ProcessNode records this signal relates to",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="triaged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this signal was first triaged — feeds resolution velocity metric (OLR-001 §13.4)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="signal",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("spc_violation", "SPC Out-of-Control"),
                    ("pc_threshold", "PC Threshold Breach"),
                    ("customer_complaint", "Customer Complaint"),
                    ("audit_finding", "Audit Finding"),
                    ("forced_failure_miss", "Forced Failure Detection Miss"),
                    ("frontier_card", "Frontier Card Finding"),
                    ("operator_report", "Operator Report"),
                    ("management_review", "Management Review Action"),
                    ("training_reflection", "Training Reflection Pattern"),
                    ("supplier_issue", "Supplier Quality Issue"),
                    ("field_return", "Field Return / Warranty"),
                    ("graph_staleness", "Graph Edge Staleness"),
                    ("graph_contradiction", "Graph Edge Contradiction"),
                    ("graph_expansion", "Graph Expansion Signal"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
