# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fmea", "0001_initial"),
        ("loop", "0013_olr001_signal_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="fmisrow",
                    name="legacy_fmea_row",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Link to legacy AIAG FMEARow for migration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fmis_row",
                        to="fmea.fmearow",
                    ),
                ),
                migrations.AlterField(
                    model_name="forcedfailuretest",
                    name="fmea_row",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Linked FMEA row for hypothesis-driven tests (nullable for exploratory)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forced_failure_tests",
                        to="fmea.fmearow",
                    ),
                ),
                migrations.AlterField(
                    model_name="investigationentry",
                    name="structured_data",
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Chart spec JSON, table data, analysis parameters/results",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
