# Generated by Django 5.2.10 on 2026-02-13 16:55

from django.db import migrations, models

import core.encrypted_storage
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(storage=core.encrypted_storage.EncryptedFileSystemStorage(), upload_to=files.models.user_file_path),
        ),
    ]
