# Generated by Django 5.2.12 on 2026-03-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_tenant_isolation_fk"),
        ("files", "0002_alter_userfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="userquota",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_quotas",
                to="core.tenant",
            ),
        ),
    ]
