# Generated by Django 5.2.12 on 2026-03-29 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forge", "0006_alter_apikey_tier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("api_key__isnull", False), ("user__isnull", False), _connector="OR"
                ),
                name="forge_job_has_owner",
            ),
        ),
    ]
