# Generated by Django 5.2.12 on 2026-04-15 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_app", models.CharField(db_index=True, max_length=50)),
                ("source_type", models.CharField(max_length=100)),
                ("source_id", models.UUIDField()),
                (
                    "artifact_key",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("consumer_app", models.CharField(db_index=True, max_length=50)),
                ("consumer_type", models.CharField(max_length=100)),
                ("consumer_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_references",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_references",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "artifact_references",
                "indexes": [
                    models.Index(
                        fields=["source_app", "source_type", "source_id"],
                        name="artifact_re_source__f3956b_idx",
                    ),
                    models.Index(
                        fields=["consumer_app", "consumer_type", "consumer_id"],
                        name="artifact_re_consume_c8e8e1_idx",
                    ),
                    models.Index(
                        fields=["tenant", "source_app"],
                        name="artifact_re_tenant__a70187_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_app",
                            "source_id",
                            "artifact_key",
                            "consumer_app",
                            "consumer_type",
                            "consumer_id",
                        ),
                        name="unique_artifact_reference",
                    )
                ],
            },
        ),
    ]
