# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="AssessmentAttempt",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("questions", models.JSONField(default=list)),
                        ("answers", models.JSONField(default=dict)),
                        ("score", models.FloatField(blank=True, null=True)),
                        ("is_passed", models.BooleanField(db_column="passed", default=False)),
                        ("started_at", models.DateTimeField(auto_now_add=True)),
                        ("completed_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="learn_assessment_attempts",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learn_assessment_attempt",
                        "ordering": ["-started_at"],
                    },
                ),
                migrations.CreateModel(
                    name="LearnSession",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("module_id", models.CharField(max_length=64)),
                        ("section_id", models.CharField(max_length=64)),
                        ("state", models.JSONField(default=dict)),
                        ("steps_completed", models.JSONField(default=list)),
                        ("started_at", models.DateTimeField(auto_now_add=True)),
                        ("completed_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                help_text="Sandbox project for this learning session",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="learn_sessions_ext",
                                to="core.project",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="learn_sessions_ext",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learn_session",
                        "ordering": ["-started_at"],
                    },
                ),
                migrations.CreateModel(
                    name="SectionProgress",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("module_id", models.CharField(max_length=64)),
                        ("section_id", models.CharField(max_length=64)),
                        (
                            "is_completed",
                            models.BooleanField(db_column="completed", default=False),
                        ),
                        ("completed_at", models.DateTimeField(blank=True, null=True)),
                        ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="learn_section_progress",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learn_section_progress",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
