# Generated by Django 5.2.10 on 2026-01-18 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.TextField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('safety_passed', models.BooleanField(default=True)),
                ('safety_confidence', models.FloatField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('conditioning_norm', models.FloatField(blank=True, null=True)),
                ('reasoning_trace', models.JSONField(blank=True, null=True)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('reasoner_raw_output', models.TextField(blank=True)),
                ('verified', models.BooleanField(null=True)),
                ('verification_confidence', models.FloatField(blank=True, null=True)),
                ('lm_prompt', models.TextField(blank=True)),
                ('lm_raw_output', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('gate_passed', models.BooleanField(default=True)),
                ('gate_reason', models.CharField(blank=True, max_length=255)),
                ('fallback_used', models.BooleanField(default=False)),
                ('safety_time_ms', models.IntegerField(blank=True, null=True)),
                ('intuition_time_ms', models.IntegerField(blank=True, null=True)),
                ('reasoner_time_ms', models.IntegerField(blank=True, null=True)),
                ('verifier_time_ms', models.IntegerField(blank=True, null=True)),
                ('lm_time_ms', models.IntegerField(blank=True, null=True)),
                ('total_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_stage', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_log', to='chat.message')),
            ],
            options={
                'db_table': 'trace_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_type', models.CharField(choices=[('low_confidence', 'Low Confidence'), ('verification_failed', 'Verification Failed'), ('error', 'Pipeline Error'), ('user_flagged', 'User Flagged'), ('random_sample', 'Random Sample')], default='low_confidence', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved for Training'), ('rejected', 'Rejected'), ('exported', 'Exported')], default='pending', max_length=20)),
                ('input_text', models.TextField()),
                ('domain', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('reasoning_trace', models.JSONField(blank=True, null=True)),
                ('model_response', models.TextField(blank=True)),
                ('corrected_response', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('verification_confidence', models.FloatField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('trace_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_candidates', to='chat.tracelog')),
            ],
            options={
                'db_table': 'training_candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
