# Generated by Django 5.2.10 on 2026-02-12 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_modelversion_usagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('feature_use', 'Feature Use'), ('milestone', 'Milestone'), ('error', 'Error'), ('session_start', 'Session Start')], db_index=True, max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('page', models.CharField(blank=True, max_length=200)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='event_logs_event_t_f0df7d_idx'), models.Index(fields=['user', 'created_at'], name='event_logs_user_id_dde186_idx'), models.Index(fields=['session_id', 'created_at'], name='event_logs_session_a1c846_idx')],
            },
        ),
    ]
