# Generated by Django 5.2.12 on 2026-03-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_message_messages_convers_3ebb41_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="blocked",
            field=models.BooleanField(db_column="blocked", default=False),
        ),
        migrations.RenameField(
            model_name="message",
            old_name="blocked",
            new_name="is_blocked",
        ),
        migrations.AlterField(
            model_name="message",
            name="verified",
            field=models.BooleanField(db_column="verified", null=True),
        ),
        migrations.RenameField(
            model_name="message",
            old_name="verified",
            new_name="is_verified",
        ),
        migrations.AlterField(
            model_name="tracelog",
            name="fallback_used",
            field=models.BooleanField(db_column="fallback_used", default=False),
        ),
        migrations.RenameField(
            model_name="tracelog",
            old_name="fallback_used",
            new_name="has_fallback_used",
        ),
        migrations.AlterField(
            model_name="tracelog",
            name="gate_passed",
            field=models.BooleanField(db_column="gate_passed", default=True),
        ),
        migrations.RenameField(
            model_name="tracelog",
            old_name="gate_passed",
            new_name="has_gate_passed",
        ),
        migrations.AlterField(
            model_name="tracelog",
            name="safety_passed",
            field=models.BooleanField(db_column="safety_passed", default=True),
        ),
        migrations.RenameField(
            model_name="tracelog",
            old_name="safety_passed",
            new_name="has_safety_passed",
        ),
        migrations.AlterField(
            model_name="tracelog",
            name="verified",
            field=models.BooleanField(db_column="verified", null=True),
        ),
        migrations.RenameField(
            model_name="tracelog",
            old_name="verified",
            new_name="is_verified",
        ),
    ]
