# Generated by Django 5.2.12 on 2026-05-01 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                ("definition", models.TextField(blank=True, default="")),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "measure_type",
                    models.CharField(
                        choices=[
                            ("process", "Process"),
                            ("material", "Material"),
                            ("product", "Product"),
                            ("resource", "Resource"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("continuous", "Continuous"),
                            ("discrete", "Discrete"),
                            ("proportion", "Proportion"),
                            ("integer", "Integer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("range_min", models.FloatField(blank=True, null=True)),
                ("range_max", models.FloatField(blank=True, null=True)),
                ("formula", models.TextField(blank=True, null=True)),
                (
                    "parent_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("parent_id", models.UUIDField(blank=True, null=True)),
                ("cached_value", models.FloatField(blank=True, null=True)),
                ("cached_variance", models.FloatField(blank=True, null=True)),
                ("cached_confidence", models.FloatField(blank=True, null=True)),
                ("cached_n", models.IntegerField(default=0)),
                ("cached_effective_n", models.FloatField(default=0.0)),
                ("cached_at", models.DateTimeField(blank=True, null=True)),
                ("decay_enabled", models.BooleanField(default=False)),
                ("decay_halflife_days", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "pcl_measure",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("tenant_id", "slug"),
                        name="unique_active_measure_slug_per_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MeasureTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                ("target_value", models.FloatField()),
                ("target_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(default="manual", max_length=50)),
                (
                    "source_ref_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("source_ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="pcl.measure",
                    ),
                ),
            ],
            options={
                "db_table": "pcl_measure_target",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Datapoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Correlation ID for tracing",
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID (SEC-001 §5.2). Null for system-wide logs.",
                        null=True,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True,
                        help_text="Event name (EVT-001 format)",
                        max_length=255,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        default="system",
                        help_text="User or system that performed the action",
                        max_length=255,
                    ),
                ),
                (
                    "actor_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of actor", null=True
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="State before change"
                    ),
                ),
                (
                    "after_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="State after change"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, help_text="Delta of changes"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for change"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context"
                    ),
                ),
                (
                    "entry_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="SHA-256 hash of entry content",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of previous entry (chain link)",
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Immutable creation timestamp",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="When the observation was made (may differ from created_at)"
                    ),
                ),
                ("source_type", models.CharField(db_index=True, max_length=30)),
                (
                    "source_ref_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("source_ref_id", models.UUIDField(blank=True, null=True)),
                ("observation_count", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True, default="")),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datapoints",
                        to="pcl.measure",
                    ),
                ),
            ],
            options={
                "db_table": "pcl_datapoint",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["measure", "-created_at"],
                        name="pcl_datapoi_measure_51ea61_idx",
                    ),
                    models.Index(
                        fields=["measure", "source_type"],
                        name="pcl_datapoi_measure_018e9e_idx",
                    ),
                ],
            },
        ),
    ]
