# Generated by Django 5.2.12 on 2026-05-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pcl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="provenance",
            field=models.CharField(
                choices=[
                    ("observed", "Observed"),
                    ("calculated", "Calculated"),
                    ("simulated", "Simulated"),
                    ("projected", "Projected"),
                ],
                db_index=True,
                default="observed",
                max_length=20,
            ),
        ),
    ]
