# Generated by Django 5.2.12 on 2026-05-06 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
        ("pcl", "0002_add_provenance_to_datapoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="source_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datapoints",
                to="job.job",
            ),
        ),
    ]
