# Generated by Django 5.2.10 on 2026-01-28 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('cleaned_csv', models.TextField()),
                ('report_markdown', models.TextField()),
                ('summary_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('latency_ms', models.IntegerField(null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='agents_api__agent_7241ff_idx'), models.Index(fields=['user', 'created_at'], name='agents_api__user_id_e25449_idx')],
            },
        ),
    ]
