# Generated by Django 5.2.10 on 2026-01-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0005_add_dmaic_phases'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='problem',
            new_name='agents_api__user_id_aab7c6_idx',
            old_name='agents_api__user_id_c8e7a5_idx',
        ),
        migrations.RenameIndex(
            model_name='problem',
            new_name='agents_api__user_id_c94cb6_idx',
            old_name='agents_api__user_id_f3a2d1_idx',
        ),
        migrations.AddField(
            model_name='problem',
            name='interview_state',
            field=models.JSONField(blank=True, help_text='Saved interview progress {current_section, current_question, answers, bias_warnings}', null=True),
        ),
    ]
