# Generated by Django 5.2.10 on 2026-02-02 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0006_add_interview_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.BinaryField()),
                ('value_type', models.CharField(default='pickle', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('namespace', models.CharField(blank=True, db_index=True, max_length=50)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_cache',
                'indexes': [models.Index(fields=['namespace', 'key'], name='session_cac_namespa_eedea3_idx'), models.Index(fields=['expires_at'], name='session_cac_expires_b72a43_idx'), models.Index(fields=['user_id', 'namespace'], name='session_cac_user_id_b6334f_idx')],
            },
        ),
    ]
