# Generated by Django 5.2.10 on 2026-02-07 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0009_whiteboard_models'),
        ('core', '0003_add_synara_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='core.project'),
        ),
    ]
