# Generated by Django 5.2.10 on 2026-02-07 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0011_llm_usage_tracking'),
        ('core', '0003_add_synara_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='A3Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Problem/theme title', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('complete', 'Complete'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('background', models.TextField(blank=True, help_text='Why does this matter? Business context, impact.')),
                ('current_condition', models.TextField(blank=True, help_text="What's happening now? Data, metrics, observations.")),
                ('goal', models.TextField(blank=True, help_text='What are we trying to achieve? Target condition, metrics.')),
                ('root_cause', models.TextField(blank=True, help_text='Why is this happening? 5-why, fishbone findings.')),
                ('countermeasures', models.TextField(blank=True, help_text='What will we do about it? Actions to address root causes.')),
                ('implementation_plan', models.TextField(blank=True, help_text='Who, what, when? Action items with owners and dates.')),
                ('follow_up', models.TextField(blank=True, help_text='How will we verify? Check dates, success metrics.')),
                ('imported_from', models.JSONField(blank=True, default=dict, help_text='References to imported content: {section: [{source, id, summary}]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a3_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a3_reports', to='core.project')),
            ],
            options={
                'verbose_name': 'A3 Report',
                'verbose_name_plural': 'A3 Reports',
                'db_table': 'a3_reports',
                'ordering': ['-updated_at'],
            },
        ),
    ]
