# Generated by Django 5.2.10 on 2026-02-07 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0012_a3_report'),
        ('core', '0003_add_synara_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueStreamMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled VSM', max_length=255)),
                ('status', models.CharField(choices=[('current', 'Current State'), ('future', 'Future State'), ('archived', 'Archived')], default='current', max_length=20)),
                ('product_family', models.CharField(blank=True, help_text='Product or service being mapped', max_length=255)),
                ('customer_name', models.CharField(blank=True, default='Customer', max_length=255)),
                ('customer_demand', models.CharField(blank=True, help_text='e.g., 460 units/day', max_length=100)),
                ('takt_time', models.FloatField(blank=True, help_text='Takt time in seconds', null=True)),
                ('supplier_name', models.CharField(blank=True, default='Supplier', max_length=255)),
                ('supply_frequency', models.CharField(blank=True, help_text='e.g., Weekly', max_length=100)),
                ('process_steps', models.JSONField(default=list, help_text='Process boxes with metrics')),
                ('inventory', models.JSONField(default=list, help_text='Inventory triangles')),
                ('information_flow', models.JSONField(default=list, help_text='Information arrows')),
                ('material_flow', models.JSONField(default=list, help_text='Material flow arrows')),
                ('total_lead_time', models.FloatField(blank=True, help_text='Total lead time in days', null=True)),
                ('total_process_time', models.FloatField(blank=True, help_text='Total value-add time in seconds', null=True)),
                ('pce', models.FloatField(blank=True, help_text='Process Cycle Efficiency (%)', null=True)),
                ('kaizen_bursts', models.JSONField(default=list, help_text='Improvement opportunities')),
                ('zoom', models.FloatField(default=1.0)),
                ('pan_x', models.FloatField(default=0.0)),
                ('pan_y', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_stream_maps', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value_stream_maps', to='core.project')),
            ],
            options={
                'verbose_name': 'Value Stream Map',
                'verbose_name_plural': 'Value Stream Maps',
                'db_table': 'value_stream_maps',
                'ordering': ['-updated_at'],
            },
        ),
    ]
