# Generated by Django 5.2.10 on 2026-02-07 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0014_dsw_result_project_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learn_assessment_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('level', models.CharField(default='analyst', max_length=32)),
                ('modules_completed', models.JSONField(default=list)),
                ('assessment_score', models.FloatField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('holder_name', models.CharField(max_length=255)),
                ('assessment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='agents_api.assessmentattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learn_certificate',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_id', models.CharField(max_length=64)),
                ('section_id', models.CharField(max_length=64)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learn_section_progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', '-started_at'], name='learn_asses_user_id_6abdc1_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'passed'], name='learn_asses_user_id_ee908f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user'], name='learn_certi_user_id_adbabf_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionprogress',
            index=models.Index(fields=['user', 'module_id'], name='learn_secti_user_id_61661d_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionprogress',
            index=models.Index(fields=['user', 'completed'], name='learn_secti_user_id_a99a38_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectionprogress',
            constraint=models.UniqueConstraint(fields=('user', 'module_id', 'section_id'), name='unique_user_section'),
        ),
    ]
