# Generated by Django 5.2.10 on 2026-02-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0015_learning_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
