# Generated by Django 5.2.10 on 2026-02-10 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0017_add_a3_embedded_diagrams'),
        ('core', '0004_charter_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCASession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('event', models.TextField(help_text='Description of the incident')),
                ('chain', models.JSONField(default=list, help_text='Causal chain steps with critiques')),
                ('root_cause', models.TextField(blank=True, help_text='Stated root cause')),
                ('countermeasure', models.TextField(blank=True, help_text='Proposed countermeasure')),
                ('evaluation', models.TextField(blank=True, help_text='Final AI evaluation of the analysis')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('complete', 'Complete')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('a3_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rca_sessions', to='agents_api.a3report')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rca_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rca_sessions', to='core.project')),
            ],
            options={
                'verbose_name': 'RCA Session',
                'verbose_name_plural': 'RCA Sessions',
                'db_table': 'rca_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
