# Generated by Django 5.2.10 on 2026-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0019_add_rca_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuestreammap',
            name='customers',
            field=models.JSONField(default=list, help_text='Customer entities on the map'),
        ),
        migrations.AddField(
            model_name='valuestreammap',
            name='suppliers',
            field=models.JSONField(default=list, help_text='Supplier entities on the map'),
        ),
    ]
