# Generated by Django 5.2.10 on 2026-02-12 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0021_add_vsm_work_centers'),
        ('core', '0004_charter_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, help_text='0-100%')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='agents_api.actionitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='core.project')),
            ],
            options={
                'db_table': 'action_items',
                'ordering': ['sort_order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Short site code, e.g. PLT-01', max_length=20)),
                ('business_unit', models.CharField(blank=True, max_length=255)),
                ('plant_manager', models.CharField(blank=True, max_length=255)),
                ('ci_leader', models.CharField(blank=True, max_length=255)),
                ('controller', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.tenant')),
            ],
            options={
                'db_table': 'hoshin_sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HoshinProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_class', models.CharField(choices=[('kaizen', 'Kaizen Event'), ('project', 'Extended Project')], default='project', max_length=20)),
                ('project_type', models.CharField(choices=[('material', 'Material Savings'), ('labor', 'Labor Savings'), ('quality', 'Quality Improvement'), ('throughput', 'Throughput Improvement'), ('energy', 'Energy Reduction'), ('safety', 'Safety Improvement'), ('other', 'Other')], default='material', max_length=20)),
                ('opportunity', models.CharField(choices=[('carryover', 'Carryover from Prior Year'), ('budgeted_new', 'Budgeted New'), ('contingency', 'Contingency'), ('unplanned', 'Unplanned/Reactive')], default='budgeted_new', max_length=20)),
                ('hoshin_status', models.CharField(choices=[('proposed', 'Proposed'), ('budgeted', 'Budgeted'), ('active', 'Active'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='proposed', max_length=20)),
                ('fiscal_year', models.IntegerField(default=2026, help_text='e.g. 2026')),
                ('annual_savings_target', models.DecimalField(decimal_places=2, default=0, help_text='Target annual savings in dollars', max_digits=12)),
                ('calculation_method', models.CharField(blank=True, help_text='waste_pct, time_reduction, headcount, claims, freight, energy, direct, layout', max_length=30)),
                ('kaizen_charter', models.JSONField(blank=True, default=dict, help_text='Kaizen event logistics: {event_date, end_date, location, schedule, event_type, primary_metric, primary_baseline, primary_target, secondary_metric, secondary_baseline, secondary_target, process_start, process_end}')),
                ('monthly_actuals', models.JSONField(blank=True, default=list, help_text='Monthly savings: [{month, baseline, actual, volume, cost_per_unit, savings}]')),
                ('baseline_data', models.JSONField(blank=True, default=list, help_text='Prior year baselines: [{month, metric_value, volume, cost_per_unit}]')),
                ('source_burst_id', models.CharField(blank=True, help_text='ID of originating kaizen burst in source_vsm.kaizen_bursts', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoshin', to='core.project')),
                ('source_vsm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoshin_projects', to='agents_api.valuestreammap')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoshin_projects', to='agents_api.site')),
            ],
            options={
                'db_table': 'hoshin_projects',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['site', 'hoshin_status'], name='hoshin_proj_site_id_7b6264_idx'), models.Index(fields=['fiscal_year', 'hoshin_status'], name='hoshin_proj_fiscal__a8cbd1_idx')],
            },
        ),
    ]
