# Generated by Django 5.2.10 on 2026-02-12 18:54

import agents_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0023_hoshin_custom_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoshinproject',
            name='fiscal_year',
            field=models.IntegerField(default=agents_api.models._current_year, help_text='Fiscal year'),
        ),
    ]
