# Generated by Django 5.2.10 on 2026-02-12 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0024_alter_hoshinproject_fiscal_year'),
        ('core', '0006_tenant_stripe_seat_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FMEA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('review', 'Under Review'), ('complete', 'Complete')], default='draft', max_length=20)),
                ('fmea_type', models.CharField(choices=[('process', 'Process FMEA'), ('design', 'Design FMEA'), ('system', 'System FMEA')], default='process', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fmeas', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmeas', to='core.project')),
            ],
            options={
                'verbose_name': 'FMEA',
                'verbose_name_plural': 'FMEAs',
                'db_table': 'fmeas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FMEARow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('process_step', models.CharField(blank=True, max_length=255)),
                ('failure_mode', models.CharField(max_length=255)),
                ('effect', models.TextField(blank=True)),
                ('severity', models.IntegerField(default=1)),
                ('cause', models.TextField(blank=True)),
                ('occurrence', models.IntegerField(default=1)),
                ('current_controls', models.TextField(blank=True)),
                ('detection', models.IntegerField(default=1)),
                ('rpn', models.IntegerField(default=1)),
                ('recommended_action', models.TextField(blank=True)),
                ('action_owner', models.CharField(blank=True, max_length=255)),
                ('action_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('revised_severity', models.IntegerField(blank=True, null=True)),
                ('revised_occurrence', models.IntegerField(blank=True, null=True)),
                ('revised_detection', models.IntegerField(blank=True, null=True)),
                ('revised_rpn', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fmea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='agents_api.fmea')),
                ('hypothesis_link', models.ForeignKey(blank=True, help_text='Hypothesis this failure mode relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmea_rows', to='core.hypothesis')),
            ],
            options={
                'db_table': 'fmea_rows',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(help_text="Key into REPORT_TYPES registry (e.g. 'capa', '8d')", max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('complete', 'Complete'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('sections', models.JSONField(blank=True, default=dict, help_text='Section content: {"problem_description": "...", "root_cause_analysis": "..."}')),
                ('imported_from', models.JSONField(blank=True, default=dict, help_text='References to imported content: {section: [{source, id, summary}]}')),
                ('embedded_diagrams', models.JSONField(blank=True, default=dict, help_text='Embedded SVG diagrams: {section: [{id, svg, board_name, room_code}]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.project')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-updated_at'],
            },
        ),
    ]
