# Generated by Django 5.2.10 on 2026-02-15 14:12

import django.db.models.deletion
from django.db import migrations, models


def backfill_parent_vsm(apps, schema_editor):
    """Link existing future-state VSMs to their current-state parents."""
    VSM = apps.get_model("agents_api", "ValueStreamMap")
    futures = VSM.objects.filter(status="future", parent_vsm__isnull=True)
    for future in futures:
        if not future.project_id:
            continue
        current = (
            VSM.objects.filter(
                project_id=future.project_id,
                owner_id=future.owner_id,
                status="current",
            )
            .order_by("created_at")
            .first()
        )
        if current:
            future.parent_vsm = current
            future.save(update_fields=["parent_vsm"])


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0031_savedmodel_project_training_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuestreammap',
            name='parent_vsm',
            field=models.ForeignKey(blank=True, help_text='Current-state VSM this future state was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_states', to='agents_api.valuestreammap'),
        ),
        migrations.RunPython(backfill_parent_vsm, migrations.RunPython.noop),
    ]
