# Generated by Django 5.2.10 on 2026-02-26 03:25

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0037_kpi_aggregation_fields'),
        ('core', '0008_alter_evidence_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicobjective',
            name='target_metric',
            field=models.CharField(blank=True, help_text="Metric catalog key, e.g. 'waste_pct', 'dollar_savings', 'spc_capability'. Links to HoshinKPI.METRIC_CATALOG for unit, direction, and aggregation.", max_length=255),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='target_unit',
            field=models.CharField(blank=True, help_text='Auto-filled from metric catalog', max_length=50),
        ),
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('category', models.CharField(blank=True, help_text='e.g. SOP, Work Instruction, Policy', max_length=100)),
                ('iso_clause', models.CharField(blank=True, max_length=20)),
                ('current_version', models.CharField(default='1.0', max_length=20)),
                ('review_due_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iso_controlled_documents',
                'ordering': ['document_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('lead_auditor', models.CharField(blank=True, max_length=200)),
                ('iso_clauses', models.JSONField(blank=True, default=list, help_text='List of clause refs')),
                ('departments', models.JSONField(blank=True, default=list)),
                ('scope', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iso_audits',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='scheduled', max_length=20)),
                ('meeting_date', models.DateField()),
                ('attendees', models.TextField(blank=True)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Prior actions, audit results, customer feedback, process performance, NCRs, risks, opportunities')),
                ('outputs', models.JSONField(blank=True, default=dict, help_text='Improvement opportunities, resource needs, changes to QMS')),
                ('minutes', models.TextField(blank=True)),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Auto-captured QMS metrics at review time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iso_management_reviews',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='NonconformanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigation', 'Investigation'), ('capa', 'CAPA'), ('verification', 'Verification'), ('closed', 'Closed')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('internal_audit', 'Internal Audit'), ('customer_complaint', 'Customer Complaint'), ('supplier', 'Supplier'), ('process', 'Process'), ('external_audit', 'External Audit'), ('management_review', 'Management Review'), ('other', 'Other')], default='other', max_length=30)),
                ('iso_clause', models.CharField(blank=True, help_text='e.g. 8.7, 10.2', max_length=20)),
                ('containment_action', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('verification_result', models.TextField(blank=True)),
                ('capa_due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncrs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs', to='core.project')),
            ],
            options={
                'db_table': 'iso_ncrs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(choices=[('nonconformity', 'Nonconformity'), ('observation', 'Observation'), ('opportunity', 'Opportunity for Improvement')], max_length=20)),
                ('description', models.TextField()),
                ('iso_clause', models.CharField(blank=True, max_length=20)),
                ('corrective_action', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='agents_api.internalaudit')),
                ('ncr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='agents_api.nonconformancerecord')),
            ],
            options={
                'db_table': 'iso_audit_findings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('conditional', 'Conditional'), ('disqualified', 'Disqualified')], default='pending', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('products_services', models.TextField(blank=True, help_text='What they supply')),
                ('iso_clause', models.CharField(blank=True, max_length=20)),
                ('last_evaluation_date', models.DateField(blank=True, null=True)),
                ('next_evaluation_date', models.DateField(blank=True, null=True)),
                ('quality_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iso_suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('iso_clause', models.CharField(blank=True, help_text='e.g. 7.2, 8.5.1', max_length=20)),
                ('frequency_months', models.IntegerField(default=0, help_text='0 = one-time')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iso_training_requirements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='agents_api.trainingrequirement')),
            ],
            options={
                'db_table': 'iso_training_records',
                'ordering': ['employee_name'],
            },
        ),
    ]
