# Generated by Django 5.2.10 on 2026-02-28 02:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0042_add_learn_session'),
        ('core', '0010_project_changelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Plant', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stations', models.JSONField(default=list)),
                ('connections', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('sinks', models.JSONField(default=list)),
                ('work_centers', models.JSONField(default=list)),
                ('simulation_config', models.JSONField(default=dict)),
                ('simulation_results', models.JSONField(default=list)),
                ('metric_snapshots', models.JSONField(default=list)),
                ('zoom', models.FloatField(default=1.0)),
                ('pan_x', models.FloatField(default=0.0)),
                ('pan_y', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_simulations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_simulations', to='core.project')),
                ('source_vsm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_simulations', to='agents_api.valuestreammap')),
            ],
            options={
                'db_table': 'plant_simulation',
                'ordering': ['-updated_at'],
            },
        ),
    ]
