# Generated by Django 5.2.10 on 2026-03-01 20:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0044_trainingrecordchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QMSFieldChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(db_index=True, max_length=20)),
                ('record_id', models.UUIDField(db_index=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iso_qms_field_changes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_type', 'record_id'], name='iso_qms_fie_record__e9ec12_idx')],
            },
        ),
    ]
