# Generated by Django 5.2.10 on 2026-03-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0046_iso_document_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="fmearow",
            name="spc_measurement",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
