# Generated by Django 5.2.12 on 2026-03-04 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0048_qms_phase2_fmea_rca"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assessmentattempt",
            name="learn_asses_user_id_ee908f_idx",
        ),
        migrations.RemoveIndex(
            model_name="sectionprogress",
            name="learn_secti_user_id_a99a38_idx",
        ),
        migrations.RemoveField(
            model_name="agentlog",
            name="success",
        ),
        migrations.RemoveField(
            model_name="assessmentattempt",
            name="passed",
        ),
        migrations.RemoveField(
            model_name="auditfinding",
            name="resolved",
        ),
        migrations.RemoveField(
            model_name="board",
            name="voting_active",
        ),
        migrations.RemoveField(
            model_name="sectionprogress",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="xmatrixcorrelation",
            name="confirmed",
        ),
        migrations.AddField(
            model_name="agentlog",
            name="is_success",
            field=models.BooleanField(db_column="success", default=True),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="is_passed",
            field=models.BooleanField(db_column="passed", default=False),
        ),
        migrations.AddField(
            model_name="auditfinding",
            name="is_resolved",
            field=models.BooleanField(db_column="resolved", default=False),
        ),
        migrations.AddField(
            model_name="board",
            name="is_voting_active",
            field=models.BooleanField(db_column="voting_active", default=False),
        ),
        migrations.AddField(
            model_name="sectionprogress",
            name="is_completed",
            field=models.BooleanField(db_column="completed", default=False),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="competency_level",
            field=models.IntegerField(
                default=0,
                help_text="TWI competency: 0=None, 1=Awareness, 2=Supervised, 3=Competent, 4=Trainer",
            ),
        ),
        migrations.AddField(
            model_name="xmatrixcorrelation",
            name="is_confirmed",
            field=models.BooleanField(
                db_column="confirmed",
                default=False,
                help_text="Auto-suggested correlations start unconfirmed; clicking confirms",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentattempt",
            index=models.Index(
                fields=["user", "is_passed"], name="learn_asses_user_id_ee908f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionprogress",
            index=models.Index(
                fields=["user", "is_completed"], name="learn_secti_user_id_a99a38_idx"
            ),
        ),
    ]
