# Generated by Django 5.2.12 on 2026-03-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0051_employee_resourcecommitment_actiontoken'),
        ('files', '0002_alter_userfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='artifacts',
            field=models.ManyToManyField(blank=True, related_name='training_records', to='files.userfile'),
        ),
        migrations.AddField(
            model_name='trainingrequirement',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Linked controlled document (nullable for informal training)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requirements', to='agents_api.controlleddocument'),
        ),
        migrations.AddField(
            model_name='trainingrequirement',
            name='document_version',
            field=models.CharField(blank=True, help_text='Document version when training was last aligned', max_length=20),
        ),
    ]
