# Generated by Django 5.2.12 on 2026-03-05 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0052_trainingrecord_artifacts_and_more'),
        ('core', '0011_employee_resourcecommitment_actiontoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPAReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('containment', 'Containment'), ('investigation', 'Investigation'), ('corrective', 'Corrective Action'), ('verification', 'Verification'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('source_type', models.CharField(blank=True, choices=[('ncr', 'Nonconformance Record'), ('audit_finding', 'Audit Finding'), ('customer_complaint', 'Customer Complaint'), ('spc_alarm', 'SPC Alarm'), ('management_review', 'Management Review'), ('supplier_issue', 'Supplier Issue')], max_length=30)),
                ('source_id', models.UUIDField(blank=True, help_text='UUID of the source record', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('containment_action', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('verification_method', models.TextField(blank=True)),
                ('verification_result', models.TextField(blank=True)),
                ('effectiveness_check_date', models.DateField(blank=True, null=True)),
                ('recurrence_check', models.BooleanField(default=False)),
                ('cost_of_poor_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_capas', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capa_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_reports', to='core.project')),
                ('rca_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_reports', to='agents_api.rcasession')),
            ],
            options={
                'verbose_name': 'CAPA Report',
                'db_table': 'iso_capas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPAStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='agents_api.capareport')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iso_capa_status_changes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='capareport',
            index=models.Index(fields=['owner', 'status'], name='iso_capas_owner_i_dadfd4_idx'),
        ),
        migrations.AddIndex(
            model_name='capareport',
            index=models.Index(fields=['source_type', 'source_id'], name='iso_capas_source__568584_idx'),
        ),
    ]
