# Generated by Django 5.2.12 on 2026-03-05 03:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0053_capareport_capastatuschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Correlation ID for tracing')),
                ('parent_correlation_id', models.UUIDField(blank=True, db_index=True, help_text='Parent entity correlation ID', null=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant ID (SEC-001 §5.2). Null for system-wide logs.', null=True)),
                ('event_name', models.CharField(db_index=True, help_text='Event name (EVT-001 format)', max_length=255)),
                ('actor', models.CharField(default='system', help_text='User or system that performed the action', max_length=255)),
                ('actor_ip', models.GenericIPAddressField(blank=True, help_text='IP address of actor', null=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict, help_text='State before change')),
                ('after_snapshot', models.JSONField(blank=True, default=dict, help_text='State after change')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Delta of changes')),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for change')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('entry_hash', models.CharField(db_index=True, editable=False, help_text='SHA-256 hash of entry content', max_length=64)),
                ('previous_hash', models.CharField(blank=True, default='', help_text='Hash of previous entry (chain link)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Immutable creation timestamp')),
                ('document_type', models.CharField(db_index=True, help_text='Signable type key (ncr, capa, document, review, audit, training, fmea)', max_length=30)),
                ('document_id', models.UUIDField(db_index=True, help_text='UUID of the signed document')),
                ('meaning', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('reviewed', 'Reviewed'), ('authored', 'Authored'), ('witnessed', 'Witnessed')], help_text='21 CFR Part 11 §11.50: signature meaning', max_length=20)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser/client user agent at signing time')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iso_electronic_signatures',
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['document_type', 'document_id'], name='idx_esig_doc'), models.Index(fields=['signer', 'created_at'], name='idx_esig_signer_time'), models.Index(fields=['tenant_id', 'created_at'], name='idx_esig_tenant_time')],
                'constraints': [models.UniqueConstraint(fields=('signer', 'document_type', 'document_id', 'meaning'), name='unique_signature_per_meaning')],
            },
        ),
    ]
