# Generated by Django 5.2.12 on 2026-03-09 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0061_copq_paf_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='a3report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='a3report',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3_records', to='agents_api.site'),
        ),
        migrations.AddField(
            model_name='capareport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capareport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_records', to='agents_api.site'),
        ),
        migrations.AddField(
            model_name='controlleddocument',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlleddocument',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='agents_api.site'),
        ),
        migrations.AddField(
            model_name='fmea',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmeas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fmea',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmea_records', to='agents_api.site'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to='agents_api.site'),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconformancerecord',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_records', to='agents_api.site'),
        ),
        migrations.AddField(
            model_name='rcasession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rca_sessions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rcasession',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rca_records', to='agents_api.site'),
        ),
        migrations.AddField(
            model_name='trainingrequirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrequirement',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='agents_api.site'),
        ),
        migrations.AlterField(
            model_name='a3report',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capareport',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlleddocument',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fmea',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fmeas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalaudit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonconformancerecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rcasession',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rca_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingrequirement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requirements', to=settings.AUTH_USER_MODEL),
        ),
    ]
