# Generated by Django 5.2.12 on 2026-03-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0062_qms_site_and_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonconformancerecord",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
