# Generated by Django 5.2.12 on 2026-03-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents_api', '0063_add_ncr_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformancerecord',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs', to='agents_api.supplierrecord'),
        ),
    ]
