# Generated by Django 5.2.12 on 2026-03-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0072_a3_last_critique"),
        ("core", "0023_qms_phase_c_registers"),
    ]

    operations = [
        migrations.AddField(
            model_name="a3report",
            name="notebook",
            field=models.ForeignKey(
                blank=True,
                help_text="Notebook this A3 belongs to (tactical execution layer)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="a3_reports",
                to="core.notebook",
            ),
        ),
    ]
