# Generated by Django 5.2.12 on 2026-03-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents_api", "0074_qms_graph_linkage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercomplaint",
            name="linked_process_node_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="UUIDs of ProcessNode records this complaint relates to — opt-in",
            ),
        ),
        migrations.AddField(
            model_name="internalaudit",
            name="linked_process_node_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="UUIDs of ProcessNode records in scope of this audit — opt-in",
            ),
        ),
        migrations.AddField(
            model_name="nonconformancerecord",
            name="linked_process_node_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="UUIDs of ProcessNode records this NCR relates to — opt-in, not required",
            ),
        ),
    ]
