# Generated by Django 5.2.10 on 2026-03-03 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('soc2_controls', models.JSONField(default=list)),
                ('duration_ms', models.FloatField(default=0)),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'syn_audit_compliance_check',
                'ordering': ['-run_at'],
                'indexes': [models.Index(fields=['check_name', '-run_at'], name='compliance_check_name_time'), models.Index(fields=['status', '-run_at'], name='compliance_status_time')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_checks', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('pass_rate', models.FloatField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('full_report', models.JSONField(default=dict)),
                ('public_report', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'syn_audit_compliance_report',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['-period_start'], name='compliance_report_period')],
            },
        ),
    ]
