# Generated by Django 5.2.10 on 2026-03-03 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_compliancecheck_compliancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short description of the change', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what is being changed and why')),
                ('change_type', models.CharField(choices=[('feature', 'Feature'), ('enhancement', 'Enhancement'), ('bugfix', 'Bug Fix'), ('hotfix', 'Hotfix'), ('security', 'Security'), ('infrastructure', 'Infrastructure'), ('migration', 'Migration'), ('documentation', 'Documentation'), ('plan', 'Plan'), ('debt', 'Debt Closure')], db_index=True, help_text='Category of change (CHG-001 §4.1)', max_length=20)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', help_text='Risk classification (CHG-001 §4.2)', max_length=10)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Priority level per DEBT-001.md', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('risk_assessed', 'Risk Assessed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('testing', 'Testing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current lifecycle state (CHG-001 §5.1)', max_length=20)),
                ('is_emergency', models.BooleanField(db_index=True, default=False, help_text='Emergency change flag — bypasses normal approval (CHG-001 §9)')),
                ('justification', models.TextField(blank=True, help_text='Business justification for the change')),
                ('affected_files', models.JSONField(default=list, help_text='List of files to be modified')),
                ('implementation_plan', models.JSONField(default=dict, help_text='Steps for implementing the change')),
                ('rollback_plan', models.JSONField(default=dict, help_text='Steps for reverting the change if it fails')),
                ('testing_plan', models.JSONField(default=dict, help_text='Steps for verifying the change after implementation')),
                ('issue_url', models.URLField(blank=True, help_text='Link to source issue (GitHub, internal tracker)')),
                ('parent_change_id', models.UUIDField(blank=True, db_index=True, help_text='Parent change request (for sub-tasks)', null=True)),
                ('related_change_ids', models.JSONField(default=list, help_text='List of related change request UUIDs')),
                ('debt_item', models.CharField(blank=True, help_text='Reference to DEBT.md item being closed', max_length=255)),
                ('commit_shas', models.JSONField(default=list, help_text='Git commit SHAs associated with this change')),
                ('log_md_ref', models.CharField(blank=True, help_text='Reference to log.md section', max_length=255)),
                ('compliance_check_ids', models.JSONField(default=list, help_text='UUIDs of ComplianceCheck records that triggered or relate to this change')),
                ('drift_violation_ids', models.JSONField(default=list, help_text='UUIDs of DriftViolation records this change remediates')),
                ('audit_entry_ids', models.JSONField(default=list, help_text='IDs of SysLogEntry records related to this change')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(help_text='Who created the change request', max_length=255)),
                ('approver', models.CharField(blank=True, help_text='Who approved the change', max_length=255)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Correlation ID for audit trail linkage')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant identifier for multi-tenant isolation', null=True)),
            ],
            options={
                'verbose_name': 'Change Request',
                'verbose_name_plural': 'Change Requests',
                'db_table': 'syn_audit_change_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['change_type', '-created_at'], name='chg_type_created'), models.Index(fields=['status', '-created_at'], name='chg_status_created'), models.Index(fields=['risk_level', '-created_at'], name='chg_risk_created'), models.Index(fields=['is_emergency'], name='chg_emergency'), models.Index(fields=['correlation_id'], name='chg_correlation'), models.Index(fields=['author', '-created_at'], name='chg_author_created')],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('multi_agent', 'Multi-Agent'), ('single_agent', 'Single Agent'), ('expedited', 'Expedited'), ('automated', 'Automated')], help_text='Type of risk assessment performed', max_length=20)),
                ('security_score', models.FloatField(default=0, help_text='Security risk score (1-5)')),
                ('availability_score', models.FloatField(default=0, help_text='Availability risk score (1-5)')),
                ('integrity_score', models.FloatField(default=0, help_text='Processing integrity risk score (1-5)')),
                ('confidentiality_score', models.FloatField(default=0, help_text='Confidentiality risk score (1-5)')),
                ('privacy_score', models.FloatField(default=0, help_text='Privacy risk score (1-5)')),
                ('overall_score', models.FloatField(default=0, help_text='Overall risk score (max of dimensions)')),
                ('overall_recommendation', models.CharField(choices=[('approve', 'Approve'), ('approve_with_conditions', 'Approve with Conditions'), ('reject', 'Reject')], default='approve', help_text='Aggregate recommendation from all votes', max_length=30)),
                ('conditions', models.JSONField(default=list, help_text='Required conditions/mitigations if approve_with_conditions')),
                ('summary', models.TextField(blank=True, help_text='Human-readable summary of the risk assessment')),
                ('is_retroactive', models.BooleanField(default=False, help_text='True if this is a retroactive assessment for an emergency change')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessed_by', models.CharField(default='system', help_text='Who or what performed the assessment', max_length=255)),
                ('change_request', models.ForeignKey(help_text='The change request being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='audit.changerequest')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'db_table': 'syn_audit_risk_assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_role', models.CharField(choices=[('security_analyst', 'Security Analyst'), ('architect', 'Architect'), ('operations', 'Operations'), ('quality', 'Quality')], help_text='Role perspective of the voting agent', max_length=30)),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('approve_with_conditions', 'Approve with Conditions'), ('reject', 'Reject')], help_text="Agent's recommendation", max_length=30)),
                ('risk_scores', models.JSONField(default=dict, help_text='Risk scores per dimension: {security: 1-5, availability: 1-5, ...}')),
                ('rationale', models.TextField(help_text='Structured justification for the recommendation')),
                ('conditions', models.JSONField(default=list, help_text='Required mitigations if approve_with_conditions')),
                ('voted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('risk_assessment', models.ForeignKey(help_text='The risk assessment this vote belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='audit.riskassessment')),
            ],
            options={
                'verbose_name': 'Agent Vote',
                'verbose_name_plural': 'Agent Votes',
                'db_table': 'syn_audit_agent_vote',
                'ordering': ['voted_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this log entry was created')),
                ('actor', models.CharField(help_text='Who or what created this log entry', max_length=255)),
                ('action', models.CharField(choices=[('plan_created', 'Plan Created'), ('submitted', 'Submitted'), ('risk_assessed', 'Risk Assessed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implementation_started', 'Implementation Started'), ('testing_completed', 'Testing Completed'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled'), ('comment', 'Comment'), ('linked', 'Linked'), ('retroactive_review', 'Retroactive Review')], db_index=True, help_text='Type of action being logged', max_length=30)),
                ('from_state', models.CharField(blank=True, help_text='Previous state of the change request', max_length=30)),
                ('to_state', models.CharField(blank=True, help_text='New state of the change request', max_length=30)),
                ('details', models.JSONField(default=dict, help_text='Structured details: commit_sha, log_md_ref, issue_url, test_results, etc.')),
                ('message', models.TextField(blank=True, help_text='Human-readable description of what happened')),
                ('change_request', models.ForeignKey(help_text='The change request this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='audit.changerequest')),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'db_table': 'syn_audit_change_log',
                'ordering': ['timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['change_request', 'timestamp'], name='chglog_request_time'), models.Index(fields=['action', '-timestamp'], name='chglog_action_time')],
            },
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['change_request', '-assessed_at'], name='risk_change_time'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['overall_recommendation'], name='risk_recommendation'),
        ),
        migrations.AddIndex(
            model_name='agentvote',
            index=models.Index(fields=['risk_assessment', 'agent_role'], name='vote_assessment_role'),
        ),
    ]
