# Generated by Django 5.2.12 on 2026-03-05 16:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_planning_linkage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short description of the incident', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the incident and its impact')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, help_text='Incident severity (INC-001 §3.1)', max_length=10)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved'), ('post_mortem', 'Post-Mortem'), ('closed', 'Closed')], db_index=True, default='detected', help_text='Current lifecycle state (INC-001 §5.1)', max_length=15)),
                ('category', models.CharField(choices=[('outage', 'Outage'), ('degradation', 'Degradation'), ('security', 'Security'), ('data', 'Data Integrity'), ('dependency', 'Dependency'), ('other', 'Other')], default='other', help_text='Incident category (INC-001 §3.2)', max_length=15)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the incident was detected')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When staff acknowledged the incident', null=True)),
                ('investigating_at', models.DateTimeField(blank=True, help_text='When investigation began', null=True)),
                ('mitigating_at', models.DateTimeField(blank=True, help_text='When mitigation/fix began', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the incident was resolved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When post-mortem was completed and incident closed', null=True)),
                ('reported_by', models.CharField(default='system', help_text='Who or what reported the incident', max_length=255)),
                ('assigned_to', models.CharField(blank=True, default='', help_text='Staff member assigned to the incident', max_length=255)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, help_text='Correlation ID for audit trail linkage', null=True)),
                ('root_cause', models.TextField(blank=True, default='', help_text='Root cause analysis (INC-001 §8.2)')),
                ('resolution_summary', models.TextField(blank=True, default='', help_text='How the incident was resolved')),
                ('post_mortem_notes', models.TextField(blank=True, default='', help_text='Post-mortem analysis, lessons learned, prevention measures')),
                ('change_request', models.ForeignKey(blank=True, help_text='Remediation ChangeRequest (INC-001 §8.3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='audit.changerequest')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'syn_audit_incident',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this log entry was created')),
                ('actor', models.CharField(help_text='Who or what created this log entry', max_length=255)),
                ('action', models.CharField(choices=[('detected', 'Detected'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved'), ('post_mortem', 'Post-Mortem'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('comment', 'Comment'), ('reassigned', 'Reassigned'), ('severity_changed', 'Severity Changed')], db_index=True, help_text='Type of action being logged', max_length=20)),
                ('from_state', models.CharField(blank=True, help_text='Previous state of the incident', max_length=20)),
                ('to_state', models.CharField(blank=True, help_text='New state of the incident', max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Structured details: severity change, CR link, etc.')),
                ('message', models.TextField(blank=True, help_text='Human-readable description of what happened')),
                ('incident', models.ForeignKey(help_text='The incident this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='audit.incident')),
            ],
            options={
                'verbose_name': 'Incident Log',
                'verbose_name_plural': 'Incident Logs',
                'db_table': 'syn_audit_incident_log',
                'ordering': ['timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', 'status'], name='inc_sev_status'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-detected_at'], name='inc_detected'),
        ),
        migrations.AddIndex(
            model_name='incidentlog',
            index=models.Index(fields=['incident', 'timestamp'], name='inclog_incident_time'),
        ),
        migrations.AddIndex(
            model_name='incidentlog',
            index=models.Index(fields=['action', '-timestamp'], name='inclog_action_time'),
        ),
    ]
