# Generated by Django 5.2.12 on 2026-03-06 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_incident_incidentlog_incident_inc_sev_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('overall_coverage', models.FloatField(blank=True, help_text='Overall line coverage %', null=True)),
                ('tier1_coverage', models.FloatField(blank=True, help_text='Tier 1 (Customer Trust) coverage %', null=True)),
                ('tier2_coverage', models.FloatField(blank=True, help_text='Tier 2 (Revenue Path) coverage %', null=True)),
                ('tier3_coverage', models.FloatField(blank=True, help_text='Tier 3 (Feature Surface) coverage %', null=True)),
                ('tier4_coverage', models.FloatField(blank=True, help_text='Tier 4 (Infrastructure) coverage %', null=True)),
                ('calibration_pass_rate', models.FloatField(blank=True, help_text='Calibration case pass rate %', null=True)),
                ('calibration_cases_run', models.IntegerField(default=0, help_text='Number of calibration cases executed')),
                ('calibration_cases_passed', models.IntegerField(default=0, help_text='Number of calibration cases that passed')),
                ('endpoint_coverage', models.FloatField(blank=True, help_text='Endpoint smoke test coverage %', null=True)),
                ('golden_file_count', models.IntegerField(default=0, help_text='Number of golden files in agents_api/tests/golden/')),
                ('complexity_violations', models.IntegerField(default=0, help_text='Files exceeding 3000-line limit without exemption')),
                ('ratchet_baseline', models.FloatField(default=0.0, help_text='Coverage floor — next report must meet or exceed this')),
                ('is_certificate', models.BooleanField(default=False, help_text='True for monthly calibration certificates')),
                ('details', models.JSONField(default=dict, help_text='Per-module breakdown and additional metrics')),
            ],
            options={
                'verbose_name': 'Calibration Report',
                'verbose_name_plural': 'Calibration Reports',
                'db_table': 'syn_audit_calibration_report',
                'ordering': ['-date'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['-date'], name='calibration_report_date')],
            },
        ),
    ]
