# Generated by Django 5.2.12 on 2026-03-06 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_add_calibration_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('security', 'Security'), ('availability', 'Availability'), ('integrity', 'Integrity'), ('confidentiality', 'Confidentiality'), ('privacy', 'Privacy'), ('operational', 'Operational'), ('compliance', 'Compliance')], max_length=20)),
                ('likelihood', models.IntegerField(help_text='1-5: probability of occurrence')),
                ('severity', models.IntegerField(help_text='1-5: impact if it occurs')),
                ('detectability', models.IntegerField(help_text='1-5: difficulty of detection (5=hardest)')),
                ('rpn', models.IntegerField(default=0, help_text='Risk Priority Number (L×S×D, max 125)')),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('mitigating', 'Mitigating'), ('accepted', 'Accepted'), ('mitigated', 'Mitigated'), ('closed', 'Closed')], default='identified', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True, default='')),
                ('owner', models.CharField(help_text='Person or role responsible', max_length=100)),
                ('related_crs', models.JSONField(blank=True, default=list, help_text='UUIDs of related ChangeRequests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_cr', models.ForeignKey(blank=True, help_text='Originating ChangeRequest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_entries', to='audit.changerequest')),
            ],
            options={
                'verbose_name': 'Risk Entry',
                'verbose_name_plural': 'Risk Entries',
                'db_table': 'syn_audit_risk_entry',
                'ordering': ['-rpn', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='risk_entry_status'), models.Index(fields=['-rpn'], name='risk_entry_rpn')],
            },
        ),
    ]
