# Generated by Django 5.2.12 on 2026-04-14 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_alter_notebook_baseline_analysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RackSession",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("title", models.CharField(default="Untitled Rack", max_length=255)),
                        ("description", models.TextField(blank=True)),
                        (
                            "session_type",
                            models.CharField(
                                choices=[
                                    ("sandbox", "Sandbox"),
                                    ("artifact", "Artifact"),
                                    ("workflow", "Workflow"),
                                    ("dashboard", "Dashboard"),
                                ],
                                default="sandbox",
                                max_length=20,
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("draft", "Draft"),
                                    ("active", "Active"),
                                    ("archived", "Archived"),
                                ],
                                default="draft",
                                max_length=20,
                            ),
                        ),
                        ("state", models.JSONField(blank=True, default=dict)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="rack_sessions_ext",
                                to="core.project",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="rack_sessions_ext",
                                to="core.tenant",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="rack_sessions_ext",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "rack_sessions",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
