# Generated by Django 5.2.12 on 2026-03-29 15:25

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_webhook_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookendpoint",
            name="secret",
            field=core.encryption.EncryptedCharField(max_length=500),
        ),
    ]
