# Generated by Django 5.2.12 on 2026-04-14 18:41

import core.encryption
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0024_tenant_isolation_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="DSWResult",
                    fields=[
                        (
                            "id",
                            models.CharField(max_length=50, primary_key=True, serialize=False),
                        ),
                        ("result_type", models.CharField(max_length=50)),
                        ("data", core.encryption.EncryptedTextField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("title", models.CharField(blank=True, max_length=255)),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="dsw_results_ext",
                                to="core.project",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="dsw_results_ext",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "agents_api_dswresult",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="SavedModel",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("description", models.TextField(blank=True)),
                        ("model_type", models.CharField(max_length=100)),
                        ("model_path", models.CharField(max_length=500)),
                        ("dsw_result_id", models.CharField(blank=True, max_length=50)),
                        ("metrics", models.TextField(blank=True)),
                        ("feature_names", models.TextField(blank=True)),
                        ("target_name", models.CharField(blank=True, max_length=100)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("training_config", models.JSONField(blank=True, default=dict)),
                        ("data_lineage", models.JSONField(blank=True, default=dict)),
                        ("version", models.IntegerField(default=1)),
                        (
                            "parent_model",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="dsw_retrained_versions",
                                to="dsw.savedmodel",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="dsw_saved_models",
                                to="core.project",
                            ),
                        ),
                        (
                            "tenant",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="dsw_saved_models",
                                to="core.tenant",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="dsw_saved_models",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "agents_api_savedmodel",
                        "ordering": ["-created_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
