# Generated by Django 5.2.12 on 2026-05-06 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Primary key (UUID v4)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for CTG tracing (CTG-001 §5)",
                        unique=True,
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID for causal chain (CTG-001 §5)",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID for multi-tenant isolation (SEC-001 §5.2). Null for system-wide entities.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Record creation timestamp (AUD-001)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp (AUD-001)"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who created this record",
                        max_length=255,
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who last modified this record",
                        max_length=255,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag (DAT-001 §9)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deletion timestamp (DAT-001 §9)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User ID who deleted this record",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata (MOD-001 §10)",
                    ),
                ),
                (
                    "canvas_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Which canvas layout was used. Null for API/CLI runs.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "inputs",
                    models.JSONField(
                        default=dict,
                        help_text="Frozen snapshot of everything that went in.",
                    ),
                ),
                (
                    "outputs_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Summary of what came out, for listing/search.",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("actor", models.CharField(db_index=True, max_length=255)),
                (
                    "is_scratch",
                    models.BooleanField(
                        default=False,
                        help_text="Scratch work stays scratch until explicitly promoted.",
                    ),
                ),
            ],
            options={
                "db_table": "job_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"], name="job_job_actor_8adaf9_idx"
                    ),
                    models.Index(
                        fields=["canvas_id", "-created_at"],
                        name="job_job_canvas__97d557_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Correlation ID for tracing",
                    ),
                ),
                (
                    "parent_correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Parent entity correlation ID",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Tenant ID (SEC-001 §5.2). Null for system-wide logs.",
                        null=True,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True,
                        help_text="Event name (EVT-001 format)",
                        max_length=255,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        default="system",
                        help_text="User or system that performed the action",
                        max_length=255,
                    ),
                ),
                (
                    "actor_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of actor", null=True
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="State before change"
                    ),
                ),
                (
                    "after_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="State after change"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, help_text="Delta of changes"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", help_text="Reason for change"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context"
                    ),
                ),
                (
                    "entry_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="SHA-256 hash of entry content",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of previous entry (chain link)",
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Immutable creation timestamp",
                    ),
                ),
                (
                    "output_key",
                    models.CharField(
                        help_text='Named result, e.g. "cpk", "histogram", "violations_list".',
                        max_length=100,
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("metric", "Metric"),
                            ("chart", "Chart"),
                            ("table", "Table"),
                            ("text", "Text"),
                            ("dataset", "Dataset"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value_numeric",
                    models.FloatField(
                        blank=True,
                        help_text="For PCL-writable metric values.",
                        null=True,
                    ),
                ),
                (
                    "value_json",
                    models.JSONField(default=dict, help_text="Full output payload."),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("observed", "Observed"),
                            ("calculated", "Calculated"),
                            ("simulated", "Simulated"),
                            ("projected", "Projected"),
                        ],
                        default="calculated",
                        max_length=20,
                    ),
                ),
                (
                    "measure_slug",
                    models.SlugField(
                        blank=True,
                        help_text="If this output wrote to PCL, which measure slug.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outputs",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "db_table": "job_output",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "output_key"],
                        name="job_output_job_id_5f03b5_idx",
                    )
                ],
            },
        ),
    ]
