# Generated by Django 5.2.12 on 2026-05-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="plugin_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Which plugin produced this job. Null for legacy/API runs.",
                max_length=100,
                null=True,
            ),
        ),
    ]
